### ISSUE TITLE
"Box" around markdown cells in slide show mode

### ISSUE THREAD

**Issue by jorisvandenbossche** [damianavila/RISE#101]
I used RISE to present last weekend, and I really like it!

But something that I noticed: markdown cells had a box around them in slide show mode  (both in firefox as in chrome, on linux), while I don't think this is intentional?

**Comment by jorisvandenbossche** [comment]
I don't have this issue on windows. Is there anything I could check to find the reason for this?

**Comment by damianavila** [comment]
This was fixed on master here: https://github.com/damianavila/RISE/pull/92

Btw, it is weird you did not see in on win... using IE or other browsers?

Please try master again and let me know if solve your issues... thanks!

**Comment by jorisvandenbossche** [comment]
Ah, I didn't see that one, sorry. 
Regarding to the linux/windows, I installed it from master last week on linux, and only tried it today on windows, so that explains the difference :-)
