### ISSUE TITLE
Let start_slideshow_at =  'selected' also exit the slideshow at the selected cell

### ISSUE THREAD

**Issue by jorisvandenbossche** [damianavila/RISE#102]
You now have the option of letting your slideshow start at the selected cell when going into slide show mode (https://github.com/damianavila/RISE#configure-your-own-options).

I wondered if it could also be an option (or combined with `start_slideshow_at`) to go to the selected cell when exiting RISE, instead of going back to the beginning of the notebook.

**Comment by damianavila** [comment]
Probably easy to do, I marked as enhancement...

**Comment by aaronbarzilai** [comment]
+1, I was just about to make the same request when I found this thread

**Comment by parmentelat** [comment]
+1 - as originally stated in #241 

this would really be a life saver as far as I am concerned :)

**Comment by damianavila** [comment]
Nicely and thoughtfully implemented by @parmentelat 
Closing here.
