### ISSUE TITLE
Slideshow button disappears when plugged into monitor 4x3 

### ISSUE THREAD

**Issue by dartdog** [damianavila/RISE#106]
Love the slides,, but when I went to present and plugged in my computer the little graph icon to switch to slide mode vanished, even after reboot I have  a 16x9 display (HDMI out) but the projector was 4x3 vga.. I noticed that Catherine Devlin experienced the same surprise in her Pycon lightning talk(presumably with a mac), I'm using Linux and Chrome..So I had to just walk through the notebook, not the worst surprise.. (since I don't have the same projector handy hard to reproduce.

**Comment by damianavila** [comment]
@dartdog, we just merge configurable height and width on master. Please check this section(at the end): https://github.com/damianavila/RISE#configure-your-own-options. That (and crtl +/- to zoom in/out) should solve any issue with different resolutions.
