### ISSUE TITLE
Anyway to suppress Code in the cell? 

### ISSUE THREAD

**Issue by dartdog** [damianavila/RISE#107]
so just display the output on the slide? Often the audience may be non-tech and we mostly want to  show text and produced output? I can do this for pdf by using a no-code template..

**Comment by adl** [comment]
There are some [notebook extensions](https://github.com/ipython-contrib/IPython-notebook-extensions) that do that.  Install either `usability/hide_input` or [`usability/hide_input_all`](https://github.com/ipython-contrib/IPython-notebook-extensions/wiki/hide_input_all) to hide one or all code cells.

**Comment by dartdog** [comment]
On I Python/Jupyter 3+ looking at notebook extensions (Thanks for that pointer!) I see hide_input _all but no hide_input which I assume deals more on a cell by cell basis? So I gather not yet done, any hints how to do?

**Comment by adl** [comment]
`hide_input` is not documented on the wiki, but the extension is present in the code with this exact name.  I'm using both.

**Comment by damianavila** [comment]
Closing to keep the discussion centered in #32.
