### ISSUE TITLE
Pressing b inserts ipython notebook codecell when in livereveal

### ISSUE THREAD

**Issue by roblem** [damianavila/RISE#111]
Pressing b on the keyboard when in presentation mode inserts an ipython codecell, even with the b key disabled in the keyboard section of main.js.

This turns out to be a problem for me since my remote presenter device sends b on certain keypresses.  I have confirmed, however, that this issue is present even if only using the keyboard.

**Comment by damianavila** [comment]
I would like to avoid messing with the notebook shortcut unless is strictly necessary.
You can solve your issue adding this line patch

```javascript
@@ -245,9 +245,11 @@ function setupKeys(mode){
   if (mode === 'reveal_mode') {
     IPython.keyboard_manager.command_shortcuts.set_shortcut("shift-enter", "ipython.execute-in-place")
     IPython.keyboard_manager.edit_shortcuts.set_shortcut("shift-enter", "ipython.execute-in-place")
+    IPython.keyboard_manager.command_shortcuts.remove_shortcut("b")
   } else if (mode === 'notebook_mode') {
     IPython.keyboard_manager.command_shortcuts.set_shortcut("shift-enter", "ipython.run-select-next")
     IPython.keyboard_manager.edit_shortcuts.set_shortcut("shift-enter", "ipython.run-select-next")
+    IPython.keyboard_manager.command_shortcuts.set_shortcut("b", "ipython.insert-cell-after")
   }
 }
```

In the future, we will provide some mechanism to add custom code to RISE, see #95
