### ISSUE TITLE
Errors when trying to install on the latest jupyterhub in a docker image

### ISSUE THREAD

**Issue by pdonorio** [damianavila/RISE#115]
Hello, 
i am trying to rebuild a notebook server with the necessary pydata stack (on python 2 kernel) installed via anaconda. I'd like to use this project to present slides directly via notebook.

I am using Docker, here it is the public image 
https://registry.hub.docker.com/u/cineca/jupydatanb/

When adding the commands to install this plugin
(see the latest version of the dockerfile:
https://github.com/cineca-scai/lectures/blob/docker/docker/notebook/Dockerfile#L68)

i get the following error on build

```
Step 21 : RUN git clone https://github.com/damianavila/RISE.git
 ---> Running in 9122f7a8d857
Cloning into 'RISE'...
 ---> 6e55ca1b6143
Removing intermediate container 9122f7a8d857
Step 22 : RUN cd RISE && python2 setup.py install
 ---> Running in 0e08d83fe0cb
/srv/ipykernel/src/ipython/IPython/html.py:10: UserWarning: The `IPython.html` package has been deprecated. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  warn("The `IPython.html` package has been deprecated. "
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from IPython.html.nbextensions import install_nbextension
ImportError: No module named nbextensions
INFO[0005] The command [/bin/sh -c cd RISE && python2 setup.py install] returned a non-zero code: 1
```

Do you have any suggestion? 
It seems that something has changed in the latest ipython library.

Note:
i didn't have this problems with your same repository on another image i builded a few weeks ago, but using python3

Thank you, this repository is very useful!

**Comment by pdonorio** [comment]
Update:

I made some heavy modifications. 
Starting the image from ubuntu and using only conda the installations goes fine.
I also forked the project to update keyboard configurations
(is there a better way?)
https://github.com/cineca-scai/lectures/blob/docker/docker/notebook/Dockerfile

Here the link to the old version, based on jupyterhub project, which does not work:
https://github.com/cineca-scai/lectures/blob/1382cfab3a0aac095fea9671b9da0d82f4759038/docker/notebook/Dockerfile

I have no idea about why the new version is fine...

**Comment by damianavila** [comment]
Lately, there was a huge splitting in the ipython repo... and AFAIK, jupyterhub uses the ipython before the splitting... so maybe this is the cause of the error you are seeing... it is something to investigate further. Thanks for the report.

>I also forked the project to update keyboard configurations
(is there a better way?)

We are thinking in a way to provide some kind of customization, see the discussion here: https://github.com/damianavila/RISE/issues/95

**Comment by pdonorio** [comment]
> Lately, there was a huge splitting in the ipython repo

You are right, i can see in the official website http://ipython.org a stable (3.1) and a dev on github (4.0)

So the jupyter docker image is based on the dev version! And this is probably why we get errors about "deprecated" functions... Crazy!?!

> We are thinking in a way to provide some kind of customization

Great, i will follow that issue then :+1: 
Thank you!!

**Comment by cfljam** [comment]
Im also struggling with this same error , building https://registry.hub.docker.com/u/cfljam/pyrat which depends on ipython/scipystack. It built OK last week, fails now.

**Comment by damianavila** [comment]
The ipython/scipystack is using the 3.x release: https://registry.hub.docker.com/u/ipython/scipystack/dockerfile/

So you have to install the 3.x RISE branch: https://github.com/damianavila/RISE/releases/tag/3.x

Hope that helps... let me know if not...

**Comment by cfljam** [comment]
Thanks!
Fixed by https://github.com/cfljam/pyRat/commit/46cb3f33a447a5373672d29cfdf2d07d241db8b1

and https://registry.hub.docker.com/u/cfljam/pyrat/ built OK

**Comment by pdonorio** [comment]
I also managed to make my new image with
pydata stack on python3/latest jupyter and this amazing plugin.

See: https://github.com/pdonorio/notebookers/tree/master/containers
