### ISSUE TITLE
Some Markdown headlines produce an unwanted scrollbar

### ISSUE THREAD

**Issue by ThomasA** [damianavila/RISE#116]
If I place a level 1 `#headline` alone in a Markdown cell, it produces a scrollbar on the right. It seems as if the cell is rendered a bit too low in slideshow mode.
![skaermbillede fra 2015-06-02 13 41 11](https://cloud.githubusercontent.com/assets/971307/7935541/1117dd32-0932-11e5-9f94-34b593f18e4c.png)

If I enter some more text in the cell below the headline, the problem disappears.

**Comment by damianavila** [comment]
Yep, I saw this the other day... we should fix the css, probably an `overflow:auto` making trouble... I will research on it...
