### ISSUE TITLE
RISE is not always enabled in notebooks

### ISSUE THREAD

**Issue by ThomasA** [damianavila/RISE#117]
I am sorry this is a very "fuzzy" issue description, but I have not yet figured out exactly what reproduces this.
I have a (somewhat largish) notebook that I successfully used to run a slideshow for teaching two days ago. Now, when I open the exact same file again, the "slideshow button" that usually enables slideshow mode simply does not appear. The only difference between now and then is that I executed most of the code cells in the notebook during the slideshow the other day and saved it afterwards. If I re-open the previous version of the notebook, from before I ran the slideshow, the "slideshow button" reappears. I have checked that the problematic version of the notebook *is* "trusted" by Jupyter.
I can send the two versions of the notebook for comparison but would prefer to do so privately.

**Comment by damianavila** [comment]
@ThomasA yes, if you can send me the two notebooks for comparison it would be great.
Also, please give me yout IPython.sys_info() too... thanks!

**Comment by ThomasA** [comment]
I have now emailed you the files.

**Comment by damianavila** [comment]
Thanks, I will try to take a look ASAP...

**Comment by macd** [comment]
I am seeing a similar issue.  On my local Ubuntu 14.04 I have installed RISE and it works fine when I start with "ipython notebook".  I installed it on a cloud instance which I set up to be an nbserver following the directions on the ipython site.  After starting up the server and connecting to it, I do not see the slideshow button.  The notebook is small.  Both versions are using the latest anaconda3 stuff.  Is there anything special that should be done for cloud nbservers?  Thanks.

On the cloud instance, I have
In [3]: IPython.sys_info()
Out[3]: "{'commit_hash': '8b0eef4',\n 'commit_source': 'installation',\n 'default_encoding': 'UTF-8',\n 'ipython_path': '/home/ubuntu/anaconda3/lib/python3.4/site-packages/IPython',\n 'ipython_version': '3.2.0',\n 'os_name': 'posix',\n 'platform': 'Linux-3.13.0-53-generic-x86_64-with-debian-jessie-sid',\n 'sys_executable': '/home/ubuntu/anaconda3/bin/python3',\n 'sys_platform': 'linux',\n 'sys_version': '3.4.3 |Anaconda 2.2.0 (64-bit)| (default, Jun  4 2015, '\n                '15:29:08) \\n'\n                '[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]'}"

On my local machine:
In [2]: IPython.sys_info()
Out[2]: "{'commit_hash': '8b0eef4',\n 'commit_source': 'installation',\n 'default_encoding': 'UTF-8',\n 'ipython_path': '/home/ubuntu/anaconda3/lib/python3.4/site-packages/IPython',\n 'ipython_version': '3.2.0',\n 'os_name': 'posix',\n 'platform': 'Linux-3.13.0-55-generic-x86_64-with-debian-jessie-sid',\n 'sys_executable': '/home/ubuntu/anaconda3/bin/python3',\n 'sys_platform': 'linux',\n 'sys_version': '3.4.3 |Anaconda 2.2.0 (64-bit)| (default, Jun  4 2015, '\n                '15:29:08) \\n'\n                '[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]'}"

**Comment by damianavila** [comment]
Should be the same... do you have any traceback from the js console??

**Comment by macd** [comment]
Here is the output from the js console.  It is pretty opaque to me, hope it
helps you

rawcell.js?v=20150624053249:82 Raw Cell Format toolbar preset loaded.
slideshow.js?v=20150624053249:43 Slideshow extension for metadata editing loaded.
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer th.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
security.js?v=20150624053249:94 HTML Sanitizer td.style changed Object
session.js?v=20150624053249:52 Session: kernel_created (1c8e004c-82a0-4ed6-8290-dcd70b8e479a)
kernel.js?v=20150624053249:440 Starting WebSockets: wss://52.12.116.235:9999/api/kernels/e9032f8a-858f-436e-bc5e-f48d6518882a
kernel.js?v=20150624053249:98 Kernel: kernel_connected (e9032f8a-858f-436e-bc5e-f48d6518882a)
kernel.js?v=20150624053249:98 Kernel: kernel_ready (e9032f8a-858f-436e-bc5e-f48d6518882a)

**Comment by damianavila** [comment]
Well, it is not loading RISE at all... can you prvide more info about:

1) How did you install the extension on the server??
2) the output for:

`ls -la $HOME/.ipython/profile_default`

and

`ls -la $HOME/.ipython/profile_default/nbconfig/`

You should see a livereveal.json file there.

Also give me:

`cat  /home/damian/.ipython/profile_default/nbconfig/notebook.json`


If you installed the extension with other profile, just give put the other profile in the command I suggested. 

Thanks!

**Comment by macd** [comment]
Hi Damian,

Apologies... I totally missed the fact that I had to install RISE into a
profile.  I reinstalled
into the nbserver profile and now all is well.  Many thanks for your quick
help and
diagnosis.  I really appreciate it!

Best Regards,
Don

**Comment by damianavila** [comment]
Nice to know it is working... I will leave the issue opened because I have to dig in the @ThomasA issue yet... just trying to find some time to take a look...

**Comment by damianavila** [comment]
@ThomasA, there is a timeout issue because your notebook are taking a lot to load... you can solve the issue adding this to your `custom.js` file... I mean, at `.ipython/profile_default/static/custom/custom.js` add:
```javascript
// to prevent timeout
requirejs.config({
    waitSeconds: 60
});
```
Hope it helps!

**Comment by ghosthoughts** [comment]
I am facing the issue even after adding the timeout; I am sure the notebook loads well within the new timeout - 60 seconds.

Also, the button oftens appears. But a lot of times, it does not. I am using __Firefox__ if that is of any help.

The JavaScript console of Firefox records the following output __in case of failed load__:

    Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.min.js:1:0
    Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery.min.js:5:0
    "Default extension for cell metadata editing loaded." default.js:48:9
    "Raw Cell Format toolbar preset loaded." rawcell.js:82:5
    "Slideshow extension for metadata editing loaded." slideshow.js:43:9
    Use of Mutation Events is deprecated. Use MutationObserver instead. jquery.min.js:5:0
    "HTML Sanitizer" "p.style changed" Object { change: "changed", tagName: "p", attribName: "style", oldValue: "text-align: center;", newValue: "text-align: center" } security.js:94:13
    "HTML Sanitizer" "p.style changed" Object { change: "changed", tagName: "p", attribName: "style", oldValue: "text-align: center;", newValue: "text-align: center" } security.js:94:13
    "HTML Sanitizer" "p.style changed" Object { change: "changed", tagName: "p", attribName: "style", oldValue: "text-align: center;", newValue: "text-align: center" } security.js:94:13
    "HTML Sanitizer" "p.style changed" Object { change: "changed", tagName: "p", attribName: "style", oldValue: "text-align: center;", newValue: "text-align: center" } security.js:94:13
    "HTML Sanitizer" "p.style changed" Object { change: "changed", tagName: "p", attribName: "style", oldValue: "text-align: center;", newValue: "text-align: center" } security.js:94:13
    "HTML Sanitizer" "p.style changed" Object { change: "changed", tagName: "p", attribName: "style", oldValue: "text-align: center;", newValue: "text-align: center" } security.js:94:13
    "HTML Sanitizer" "p.style changed" Object { change: "changed", tagName: "p", attribName: "style", oldValue: "text-align: center;", newValue: "text-align: center" } security.js:94:13
    "HTML Sanitizer" "p.style changed" Object { change: "changed", tagName: "p", attribName: "style", oldValue: "text-align: center;", newValue: "text-align: center" } security.js:94:13
    "HTML Sanitizer" "p.style changed" Object { change: "changed", tagName: "p", attribName: "style", oldValue: "text-align: center;", newValue: "text-align: center" } security.js:94:13
    "HTML Sanitizer" "p.style changed" Object { change: "changed", tagName: "p", attribName: "style", oldValue: "text-align: center;", newValue: "text-align: center" } security.js:94:13
    "Session: kernel_created (fd0f7b0e-6350-4f0b-ae07-159cbeadf538)" session.js:52:13
    "Starting WebSockets:" "ws://localhost:8888/api/kernels/57174d09-468c-4e5e-a263-3e054dcaa57b" kernel.js:440:9
    "Failed to load extension(s):" Array [ "nbextensions/livereveal/main" ] TypeError: Function.prototype.toString called on incompatible object
    Stack trace:
    @http://localhost:8888/nbextensions/livereveal/main.js?v=20150717172845:36:1
    newContext/context.execCb@http://localhost:8888/static/components/requirejs/require.js?v=640929dac3c23a448d2eebc37bc32062:1658:24
    newContext/Module.prototype.check@http://localhost:8888/static/components/requirejs/require.js?v=640929dac3c23a448d2eebc37bc32062:869:47
    newContext/Module.prototype.enable@http://localhost:8888/static/components/requirejs/require.js?v=640929dac3c23a448d2eebc37bc32062:1151:17
    newContext/Module.prototype.init@http://localhost:8888/static/components/requirejs/require.js?v=640929dac3c23a448d2eebc37bc32062:782:21
    callGetModule@http://localhost:8888/static/components/requirejs/require.js?v=640929dac3c23a448d2eebc37bc32062:1178:17
    newContext/context.completeLoad@http://localhost:8888/static/components/requirejs/require.js?v=640929dac3c23a448d2eebc37bc32062:1552:21
    newContext/context.onScriptLoad@http://localhost:8888/static/components/requirejs/require.js?v=640929dac3c23a448d2eebc37bc32062:1679:21
     utils.js:37:17
    "Kernel: kernel_connected (57174d09-468c-4e5e-a263-3e054dcaa57b)" kernel.js:98:13
    "Kernel: kernel_ready (57174d09-468c-4e5e-a263-3e054dcaa57b)" kernel.js:98:13

__In case of a successful load (the button appears)__, the console of Firefox records this:

    Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.min.js:1:0
    Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery.min.js:5:0
    "Default extension for cell metadata editing loaded." default.js:48:9
    "Raw Cell Format toolbar preset loaded." rawcell.js:82:5
    "Slideshow extension for metadata editing loaded." slideshow.js:43:9
    Use of Mutation Events is deprecated. Use MutationObserver instead. jquery.min.js:5:0
    "HTML Sanitizer" "p.style changed" Object { change: "changed", tagName: "p", attribName: "style", oldValue: "text-align: center;", newValue: "text-align: center" } security.js:94:13
    "HTML Sanitizer" "p.style changed" Object { change: "changed", tagName: "p", attribName: "style", oldValue: "text-align: center;", newValue: "text-align: center" } security.js:94:13
    "HTML Sanitizer" "p.style changed" Object { change: "changed", tagName: "p", attribName: "style", oldValue: "text-align: center;", newValue: "text-align: center" } security.js:94:13
    "HTML Sanitizer" "p.style changed" Object { change: "changed", tagName: "p", attribName: "style", oldValue: "text-align: center;", newValue: "text-align: center" } security.js:94:13
    "HTML Sanitizer" "p.style changed" Object { change: "changed", tagName: "p", attribName: "style", oldValue: "text-align: center;", newValue: "text-align: center" } security.js:94:13
    "HTML Sanitizer" "p.style changed" Object { change: "changed", tagName: "p", attribName: "style", oldValue: "text-align: center;", newValue: "text-align: center" } security.js:94:13
    "HTML Sanitizer" "p.style changed" Object { change: "changed", tagName: "p", attribName: "style", oldValue: "text-align: center;", newValue: "text-align: center" } security.js:94:13
    "HTML Sanitizer" "p.style changed" Object { change: "changed", tagName: "p", attribName: "style", oldValue: "text-align: center;", newValue: "text-align: center" } security.js:94:13
    "HTML Sanitizer" "p.style changed" Object { change: "changed", tagName: "p", attribName: "style", oldValue: "text-align: center;", newValue: "text-align: center" } security.js:94:13
    "HTML Sanitizer" "p.style changed" Object { change: "changed", tagName: "p", attribName: "style", oldValue: "text-align: center;", newValue: "text-align: center" } security.js:94:13
    "Loaded extension: livereveal/main" utils.js:29:21
    "Session: kernel_created (291a999c-bef6-446d-9307-208264e50b3a)" session.js:52:13
    "Starting WebSockets:" "ws://localhost:8888/api/kernels/3ac98eb7-d952-4de7-bb3a-bb3240f34d70" kernel.js:440:9
    "Kernel: kernel_connected (3ac98eb7-d952-4de7-bb3a-bb3240f34d70)" kernel.js:98:13
    "Kernel: kernel_ready (3ac98eb7-d952-4de7-bb3a-bb3240f34d70)"

So the error is actually recorded in the console, but I couldn't interpret it; I hope you can do something with it.

**Comment by ghosthoughts** [comment]
I noticed another curious thing - this never happens in Chromium; the button appears at 100% success rate.

The output from JavaScript console from Chromium is:

    Default extension for cell metadata editing loaded.
    rawcell.js?v=20150717172845:82 Raw Cell Format toolbar preset loaded.
    slideshow.js?v=20150717172845:43 Slideshow extension for metadata editing loaded.
    security.js?v=20150717172845:94 HTML Sanitizer p.style changed Object
    :8888/static/base/js/security.js?v=20150717172845:94 HTML Sanitizer p.style changed Object
    :8888/static/base/js/security.js?v=20150717172845:94 HTML Sanitizer p.style changed Object
    :8888/static/base/js/security.js?v=20150717172845:94 HTML Sanitizer p.style changed Object
    :8888/static/base/js/security.js?v=20150717172845:94 HTML Sanitizer p.style changed Object
    :8888/static/base/js/security.js?v=20150717172845:94 HTML Sanitizer p.style changed Object
    :8888/static/base/js/security.js?v=20150717172845:94 HTML Sanitizer p.style changed Object
    :8888/static/base/js/security.js?v=20150717172845:94 HTML Sanitizer p.style changed Object
    :8888/static/base/js/security.js?v=20150717172845:94 HTML Sanitizer p.style changed Object
    :8888/static/base/js/security.js?v=20150717172845:94 HTML Sanitizer p.style changed Object
    :8888/static/services/sessions/session.js?v=20150717172845:52 Session: kernel_created (fd0f7b0e-6350-4f0b-ae07-159cbeadf538)
    :8888/static/services/kernels/kernel.js?v=20150717172845:440 Starting WebSockets: ws://localhost:8888/api/kernels/57174d09-468c-4e5e-a263-3e054dcaa57b
    :8888/static/base/js/utils.js?v=20150717172845:29 Loaded extension: livereveal/main
    http://localhost:8888/notebooks/logo.png Failed to load resource: the server responded with a status of 404 (Not Found)
    :8888/static/services/kernels/kernel.js?v=20150717172845:98 Kernel: kernel_connected (57174d09-468c-4e5e-a263-3e054dcaa57b)
    :8888/static/services/kernels/kernel.js?v=20150717172845:98 Kernel: kernel_ready (57174d09-468c-4e5e-a263-3e054dcaa57b)

So may be this is a Firefox thing. I will test on IE later and let you know.

**Comment by damianavila** [comment]
That's interesting... something to investigate further... thanks for all your test.

**Comment by jhrsn** [comment]
I also saw the issue related to timeout with a large notebook, in Safari, Chrome, and Firefox. It was solved by breaking the notebook into smaller pieces. Thanks for the timeout fix, I'll give it a try.

**Comment by ghosthoughts** [comment]
Ok. Surprisingly, IE worked quite well; the button appeared everytime. Along with it, I tested Firefox on Windows too, with same disappointing results - Quite a lot of times, Firefox failed to display the button with the same error.

So this indeed has something to do with Firefox.

About the size of the notebook, I used 5 varying sizes of notebook, one of which was empty. So I dont think size has to do something with this error.

Take your time, and see if you come up with something. I may be able to dig in further in my free time.

**Comment by damianavila** [comment]
Thanks again.... can you also post your firefox version?

**Comment by ghosthoughts** [comment]
Its the lastest: `39.0`.

**Comment by ThomasA** [comment]
I have not had time to try the timeout workaround yet, but I can confirm that I also experienced this issue in Firefox. My Firefox is currently 39.0 (Ubuntu) but may have been auto-updated since I last saw this issue.
I will try it in Chromium as well to see if that makes any difference.

**Comment by lengelhardt** [comment]
I am having the same issue.  I created a notebook last month that uses RISE for a presentation, and everything worked perfectly (using firefox).  I just tried using the same notebook today (again using firefox), and the slideshow button was gone.  In the meantime I had updated ipython, so I thought that might be the problem.  I tried opening the notebook using Chrome, and it worked perfectly.  I am using a Mac (OSX 10.10.4) and firefox 39.0.  Thank you for pointing out that Chrome solves the problem!

**Comment by damianavila** [comment]
I will try to investigate during the weekend... thanks again for the info.

**Comment by damianavila** [comment]
OK, I can replicate the issue in firefox, in Cromium works perfectly:

```
TypeError: module is undefined main.min.js:11977:20
"Failed to load extension:" Array [ "nbextensions/livereveal/main" ] TypeError: Function.prototype.toString called on incompatible object
Stack trace:
@http://localhost:8889/nbextensions/livereveal/main.js:36:1
newContext/context.execCb@http://localhost:8889/static/components/requirejs/require.js?v=4c293cc603dabc2eb7b3fd6e2e271ffa:1670:24
newContext/Module.prototype.check@http://localhost:8889/static/components/requirejs/require.js?v=4c293cc603dabc2eb7b3fd6e2e271ffa:869:47
newContext/Module.prototype.enable@http://localhost:8889/static/components/requirejs/require.js?v=4c293cc603dabc2eb7b3fd6e2e271ffa:1161:17
newContext/Module.prototype.init@http://localhost:8889/static/components/requirejs/require.js?v=4c293cc603dabc2eb7b3fd6e2e271ffa:782:21
callGetModule@http://localhost:8889/static/components/requirejs/require.js?v=4c293cc603dabc2eb7b3fd6e2e271ffa:1188:17
newContext/context.completeLoad@http://localhost:8889/static/components/requirejs/require.js?v=4c293cc603dabc2eb7b3fd6e2e271ffa:1564:21
newContext/context.onScriptLoad@http://localhost:8889/static/components/requirejs/require.js?v=4c293cc603dabc2eb7b3fd6e2e271ffa:1691:21
```

the problem seems to be here:
```javascript
define('base/js/utils',[
    'jquery',
    'codemirror/lib/codemirror',
    'moment',
    // silently upgrades CodeMirror
    'codemirror/mode/meta',
], function($, CodeMirror, moment){
    "use strict";
    
    /**
     * Load a single extension.
     * @param  {string} extension - extension path.
     * @return {Promise} that resolves to an extension module handle
     */
    var load_extension = function (extension) {
        return new Promise(function(resolve, reject) {
            require(["nbextensions/" + extension], function(module) {
                console.log("Loaded extension: " + extension);
                try {
                    module.load_ipython_extension();
                } finally {
                    resolve(module);
                }
            }, function(err) {
                reject(err);
            });
        });
    };

    /**
     * Load multiple extensions.
     * Takes n-args, where each arg is a string path to the extension.
     * @return {Promise} that resolves to a list of loaded module handles.
     */
    var load_extensions = function () {
        return Promise.all(Array.prototype.map.call(arguments, load_extension)).catch(function(err) {
            console.error("Failed to load extension" + (err.requireModules.length>1?'s':'') + ":", err.requireModules, err);
        });
    };

    /**
     * Wait for a config section to load, and then load the extensions specified
     * in a 'load_extensions' key inside it.
     */
    function load_extensions_from_config(section) {
        section.loaded.then(function() {
            if (section.data.load_extensions) {
                var nbextension_paths = Object.getOwnPropertyNames(
                                            section.data.load_extensions);
                load_extensions.apply(this, nbextension_paths);
            }
        });
    }
```

I think this could be related with this change: https://github.com/jupyter/notebook/pull/193

@jdfreder, @takluyver, @bollwyvl ideas are welcomed :wink:

**Comment by takluyver** [comment]
I don't think it's related to that change, I think it's live_reveal attempting to set `IPython.notebook.get_cell_elements` to a new function that's causing the error. If I run this in the JS console, I see the same error message:

```javascript
IPython.notebook.get_cell_elements = function() { return this.container.find("div.cell"); }
```

This appears to be a problem because we [seal](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/seal). This isn't new - we [do it in 3.x too](https://github.com/ipython/ipython/blob/rel-3.2.1/IPython/html/static/notebook/js/notebook.js#L151), but maybe Firefox changed the behaviour of sealed objects to prevent monkeypatching their methods. That's not unreasonable, but gah, Javascript.

**Comment by takluyver** [comment]
I was hoping that using [preventExtensions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/preventExtensions) instead of seal might make this work, but apparently not. I think the issue is that the method is part of the object prototype, not the object itself.

I've got it working by changing this:

```javascript
IPython.notebook.get_cell_elements = function () { ...
```

To this:

```javascript
Object.getPrototypeOf(IPython.notebook).get_cell_elements = function () { ...
```

I don't know what other implications that might have, but it appears to work in my quick testing.

**Comment by damianavila** [comment]
>This appears to be a problem because we seal. This isn't new - we do it in 3.x too, but maybe Firefox changed the behaviour of sealed objects to prevent monkeypatching their methods. That's not unreasonable, but gah, Javascript.

Booooo JS...

>To this:
>Object.getPrototypeOf(IPython.notebook).get_cell_elements = function () { ...
>I don't know what other implications that might have, but it appears to work in my quick testing.

OK, I guess we should test it! Thanks for your feedback!

**Comment by feiyuw** [comment]
I also met this issue, thanks @takluyver , your solution is OK for me.

**Comment by damianavila** [comment]
OK, I will test it by myself (so we can have 3 positives) and make a PR if it is working OK...
