### ISSUE TITLE
enable bookmarklet use

### ISSUE THREAD

**Issue by bollwyvl** [damianavila/RISE#123]
I've recently been doing yet more notebooks-as-slides advocacy, and love showing RISE.

Working with try.jupyter.org is a great way to give people a taste with no setup, but RISE obviously isn't available there. However, with just a bit of work, RISE could be made to work entirely off of rawgit as a bookmarklet

Here's my prototype:
```html
<a href="javascript:require(["https://cdn.rawgit.com/damianavila/RISE/master/livereveal/main.js"], function(f){f.load_ipython_extension()})">
```

Everything is super duper until the static locations for some of the other assets show up:
![2015-07-06_1055](https://cloud.githubusercontent.com/assets/45380/8525230/9eb13fd4-23cd-11e5-9463-1937505844d9.png)

I think all it would take is passing `require` as the first argument to `define` in `main.js`, as [described here](http://requirejs.org/docs/api.html#modulenotes), and `toURL` will take care of the rest. Happy to PR, if this is a thing that other people would find useful!

**Comment by damianavila** [comment]
>Happy to PR, if this is a thing that other people would find useful!

Of course... the PR will be welcome :wink:

**Comment by damianavila** [comment]
Done!! Thanks again @bollwyvl
