### ISSUE TITLE
Could not install RISE

### ISSUE THREAD

**Issue by ymote** [damianavila/RISE#130]
Hi,

I have problem installing the RISE. Here is the error info. Is there any updated setup script? Thanks.

root@9147d0f093b9:/home/RISE# python setup.py install
/srv/ipykernel/src/ipython/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from IPython.html.nbextensions import install_nbextension
ImportError: No module named nbextensions

root@9147d0f093b9:/home/RISE# jupyter --version
4.1.0.dev

**Comment by damianavila** [comment]
I have a branch working with Jupyter but still not merged, you can check it here: https://github.com/damianavila/RISE/tree/update_jupyter

It will land soon... let me know any issues if you test this branch.

**Comment by ymote** [comment]
It works now. Thanks.

**Comment by damianavila** [comment]
Branch merged into master, closing here...
