### ISSUE TITLE
Module Import Error..?

### ISSUE THREAD

**Issue by startakovsky** [damianavila/RISE#131]
I seem to have an import error on this machine. When I do a `locate nbextensions` I see `IPython/html/nbextensions.py`.

How do I get this to work?

    vagrant@vagrant-ubuntu-trusty-64:~/RISE$ python setup.py install
    Traceback (most recent call last):
      File "setup.py", line 2, in <module>
        from notebook.nbextensions import install_nbextension
    ImportError: No module named notebook.nbextensions

**Comment by startakovsky** [comment]
It seems to have worked just by copying the `RISE/livereveal` directory to my `.ipython/nbextensions`, thanks! Though this is still an issue I think.

**Comment by damianavila** [comment]
Master is working with the jupyter notebook package, I guess you are using IPython 3.2.1 or older?

**Comment by damianavila** [comment]
This remembers me I have to update the README with the branches for each version...
