### ISSUE TITLE
Problems installing RISE on a macos

### ISSUE THREAD

**Issue by pnugues** [damianavila/RISE#136]
Hello, 

I am trying to install RISE on a mac and after one day of work, I could not succeed.

Here are my commands:
bash-3.2$ pwd
/Users/pierre/RISE-master
bash-3.2$ ls
README.md	livereveal	package.json	setup.py	src
bash-3.2$ sudo JUPYTER_CONFIG_DIR=~pierre/.jupyter/ python3 setup.py install
Password:
bash-3.2$ sudo JUPYTER_CONFIG_DIR=~pierre/.jupyter/ python setup.py install
bash-3.2$ jupyter
bash-3.2$ jupyter --version
4.0.2
bash-3.2$ cd ..
bash-3.2$ pwd
/Users/pierre
bash-3.2$ jupyter notebook
[I 17:05:31.824 NotebookApp] The port 8888 is already in use, trying another random port.
[I 17:05:31.833 NotebookApp] Serving notebooks from local directory: /Users/pierre
[I 17:05:31.834 NotebookApp] 0 active kernels 
[I 17:05:31.834 NotebookApp] The IPython Notebook is running at: http://localhost:8889/
[I 17:05:31.834 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).

And I do not have the RISE icon on the notebooks...
Is there a way to debug the install process?

Thank you for your help.

**Comment by flinz** [comment]
same problem here, OSX 10.10.3 and python 2.7.9.
I tried the manual installation as described too.

I suspect something might be screwy on OSX, since pip also created a directory ``~/Library/Jupyter`` with contents:
```
nbsignatures.db
notebook_secret
(dir) runtime
```

Any way to debug jupyter startup/see which extensions are found?

**Comment by damianavila** [comment]
can you post the output from:
`ls -la ~pierre/.jupyter/`
and
`ls -la ~pierre/.jupyter/nbconfig`

**Comment by flinz** [comment]
I'll take the freedom of posting mine too

``~/.jupyter/``
```
-rw-r--r--    1 username  staff    26 Aug 12 15:31 migrated
drwxr-xr-x    3 username  staff   102 Aug 12 15:32 nbconfig
drwxr-xr-x    3 username  staff   102 Aug 12 15:40 nbextensions
```

``~/.jupyter/nbconfig``
```
-rw-r--r--  1 username  staff   58 Aug 12 15:40 notebook.json
```

``more ~/.jupyter/nbconfig/notebook.json``
```
{
  "load_extensions": {
    "livereveal/main": true
  }
}
```

``~/.jupyter/nbextensions``
```
drwxr-xr-x  7 username  staff  238 Aug 12 15:40 livereveal
```

**Comment by pnugues** [comment]
Here it is:
bash-3.2$ pwd
/Users/pierre/.jupyter
bash-3.2$ ls -ls
total 8
8 -rw-r--r--  1 pierre  staff   26 13 aoû 15:36 migrated
0 drwxr-xr-x  3 pierre  staff  102 13 aoû 15:42 nbconfig
bash-3.2$ pwd
/Users/pierre/.jupyter
bash-3.2$ ls -la
total 8
drwxr-xr-x    4 pierre  staff   136 13 aoû 15:42 .
drwxr-xr-x+ 152 pierre  staff  5168 13 aoû 16:42 ..
-rw-r--r--    1 pierre  staff    26 13 aoû 15:36 migrated
drwxr-xr-x    3 pierre  staff   102 13 aoû 15:42 nbconfig
bash-3.2$ cd nbconfig/
bash-3.2$ pwd
/Users/pierre/.jupyter/nbconfig
bash-3.2$ ls -la
total 8
drwxr-xr-x  3 pierre  staff  102 13 aoû 15:42 .
drwxr-xr-x  4 pierre  staff  136 13 aoû 15:42 ..
-rw-r--r--  1 pierre  staff   58 13 aoû 17:03 notebook.json
bash-3.2$

**Comment by flinz** [comment]
@pnugues why did you close the issue? did you solve it?

**Comment by pnugues** [comment]
no, I simply hit the wrong button.

**Comment by damianavila** [comment]
Interestingly, in linux, the nbextension folder is located at `~/.local/share/jupyter/` and according to [this](http://jupyter.readthedocs.org/en/latest/system.html#envvar-JUPYTER_PATH) it should be in `~/Library/Jupyter` on Mac... maybe there it is the issue... can you move the nbextension folder to `~/Library/Jupyter` and try again? (remember to hard-reload the page or use "incognito" mode to avoid cache-related issues).

**Comment by flinz** [comment]
@damianavila this didn't seem to fix the issue, for me at least - still no slideshow button appearing.

**Comment by damianavila** [comment]
OK, can you give me details on:

* Jupyter version 
* Browser version
* JS console messages

Thanks!

**Comment by pnugues** [comment]
Here are the versions:

pierre:~ pierre$ jupyter --version
4.0.2
My browser is Firefox 41.0b1 (I also tested it with Chrome and Safari and I could not see the RISE button either)

I am not sure how to get all the JS output.

Here are the commands:
pierre:~ pierre$ jupyter notebook
[I 17:02:39.531 NotebookApp] Serving notebooks from local directory: /Users/pierre
[I 17:02:39.532 NotebookApp] 0 active kernels 
[I 17:02:39.532 NotebookApp] The IPython Notebook is running at: http://localhost:8888/
[I 17:02:39.532 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 17:04:56.473 NotebookApp] Kernel started: 713cdc0a-10f1-462e-9772-2b37def53996


Here is what I get in the JS console:

Default extension for cell metadata editing loaded. main.min.js:23888:9
Raw Cell Format toolbar preset loaded. main.min.js:23974:5
Slideshow extension for metadata editing loaded. main.min.js:24022:9
Session: kernel_created (605e815d-95be-4734-adca-34e08a180fe5) main.min.js:23176:13
Starting WebSockets: "ws://localhost:8888/api/kernels/713cdc0a-10f1-462e-9772-2b37def53996" main.min.js:22497:9
Loaded extension: widgets/notebook/js/extension main.min.js:12030:17
loaded widgets extension.js:81:9
Kernel: kernel_connected (713cdc0a-10f1-462e-9772-2b37def53996) main.min.js:22155:13
Kernel: kernel_ready (713cdc0a-10f1-462e-9772-2b37def53996) main.min.js:22155:13

**Comment by flinz** [comment]
Jupyter
```
 % jupyter --version
4.0.2
```

Chrome
```
45.0.2454.26 beta
```

JS Console (Chrome gave no output at all, weird, so here is output from firefox ``33.0.3``)
```
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead main.min.js:86
Use of Mutation Events is deprecated. Use MutationObserver instead. main.min.js:90
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. main.min.js:90
"Default extension for cell metadata editing loaded." main.min.js:23888
"Raw Cell Format toolbar preset loaded." main.min.js:23974
"Slideshow extension for metadata editing loaded." main.min.js:24022
"Session: kernel_created (071b576f-1d06-4485-a00f-d2615d110227)" main.min.js:23176
"Starting WebSockets:" "ws://localhost:8888/api/kernels/a0a118ce-6c7c-45eb-828d-f9bbb2d97c32" main.min.js:22497
"Kernel: kernel_connected (a0a118ce-6c7c-45eb-828d-f9bbb2d97c32)" main.min.js:22155
"Loaded extension: widgets/notebook/js/extension" main.min.js:12030
"loaded widgets" extension.js:81
"Kernel: kernel_ready (a0a118ce-6c7c-45eb-828d-f9bbb2d97c32)"
```

**Comment by damianavila** [comment]
OK... RISE is not loaded... now thinking about this... some days ago this was merged: https://github.com/jupyter/notebook/pull/251

But the fix is not released yet... so if you move the `~/.jupyter/nbconfig/notebook.json` into `~/.jupyter/` (one level up in you own jupyter dir) it should load fine, at least it worked for me (remember to hard-reload or use incognito).

Let me know if it helps...

**Comment by flinz** [comment]
I can confirm that moving nbconfig.json up one level, as recommended, fixes the issue.
I can also confirm that installing the dev version from the github master (via ``pip install git+git://github.com/jupyter/notebook.git@master``) also fixes the issue via https://github.com/jupyter/notebook/pull/251.

**Comment by pnugues** [comment]
For me too, moving nbconfig.json up one level fixes the issue.

Thank you for your help and time.

**Comment by sboisen** [comment]
Likewise, moving nbconfig.json up one level fixed my problem (which was no button to launch the slideshow display).
