### ISSUE TITLE
No Enter/Exit button in Chrome (stable and dev)

### ISSUE THREAD

**Issue by 2grep** [damianavila/RISE#144]
Similar to issues #136 and #137, no Enter/Exit button, but also, the ctrl-r doesn't work.

I'm running Jupyter 1.0.0, jupyter_client 4.0.0, jupyter_console 4.0.2, and jupyter_core 4.0.4. I have been using RISE for over a year and recently switched to Anaconda and took the opportunity to make the jump to Jupyter. I took the opportunity to also upgrade RISE. Now the Enter/Exit button has disappeared in Chrome stable (Version 45.0.2454.85 (64-bit)) and Chrome dev channel (Version 47.0.2503.0 dev (64-bit)).

The Enter/Exit button is present in Safari (version 8.0.8) and works.

I did read issue #136 and I have tried moving notebook.json up one level from ~/.jupyter/nbconfig to ~/.jupyter but still no button. Other extensions installed to the same location (OS X default: ~/Library/Jupyter/nbextensions) do work (e.g., css_selector). I have cleared every cache in Chrome every way I can think of, including restarting Chrome, shift-F5, shift-reload, via Developer Tools, and in Settings. I have tried incognito mode and even tried downloading a fresh Chrome, and launching from the command line with extensions disabled. No joy.

Any thoughts?

**Comment by damianavila** [comment]
@2grep thanks for raising this... there seems to be several issue affecting us... but I guess this is chrome/chromium-related... since it is working in Safari according to you. Can you also test on firefox?
I will try to install the Chrome you are using and take a look... thanks!

**Comment by 2grep** [comment]
Wow, been a while since I used Firefox! I can report I am *not* getting a Enter/Exit button in Firefox 20.0 or 38.0.5. The button is also only loading intermittently in Safari. But, right now, Firefox 38, Chrome 47, and Safari 8 are all looking at the same version of the same notebook, and only Safari is showing an Enter/Exit button.

**Comment by damianavila** [comment]
OK, let's start again... and sorry if I am a little bit annoying...

```python
import notebook
notebook.version_info
```

then... `tree ~/.jupyter`, `cat ~/.jupyter/nbconfig/notebook.json` and `tree ~/Library/Jupyter/nbextensions`

then... start the notebook in incognito with the js console opened and paste all the js console output...

also... start the notebook with:

`JUPYTER_CONFIG_DIR=~/.jupyter jupyter notebook`

later... start the notebook with:

`JUPYTER_DATA_DIR=~/Library/Jupyter/nbextensions jupyter notebook`

and finally:

`JUPYTER_CONFIG_DIR=~/.jupyter UPYTER_DATA_DIR=~/Library/Jupyter/nbextensions jupyter notebook`

replace `~` with you /home/<you> if the above commands does not work...

Obviously, make it when you have some time... :wink: 

Thanks!

**Comment by 2grep** [comment]
ok, will do, please don't close this, I'll shoot for some time this weekend or early next week.

**Comment by damianavila** [comment]
>please don't close this, 

Of course, I will not close... we have to figured out the thing...

Thanks for working on this...

>Here's the first part

I will check it, thanks again...

**Comment by damianavila** [comment]
OK, I looked into your notebook.... first question, how did you install RISE?
ALSO... did you `git pull origin` before installing, or even better, what is the output of `git show`?

Because there is a missing file in your installation which let me think you maybe have an outdated codebase...

**Comment by 2grep** [comment]
Thanks for taking a look.

Ok, I uploaded the raw contents of my test notebook again to [the same gist](https://gist.github.com/2grep/78bcc152b8513dbd0cbf), just updated with the output from the javascript console in incognito mode at the bottom, and the output of `git show`. My apologies for the formatting, I don't understand why github isn't formating raw cells correctly. But the javascript console and such look okay if you click "raw".

I installed RISE by clicking the "Clone to Desktop" link on GitHub and then running setup.py from the directory.

**Comment by damianavila** [comment]
OK, you have something in the custom.js file that probably is making trouble...
Can you post the content of `/Users/niels/.jupyter/custom/custom.js`
You probably have an old livereveal reference there... I am pretty sure if you remove that file (or the livereveal-related stuff), it should work... I hope :wink:

**Comment by 2grep** [comment]
That was it!

```
// LIVE_REVEAL START

// to prevent timeout
requirejs.config({
    waitSeconds: 60
});

$([IPython.events]).on('app_initialized.NotebookApp', function(){

     require(['nbextensions/livereveal/main'],function(livereveal){
       // livereveal.parameters('theme', 'transition', 'fontsize', static_prefix);
       //   * theme can be: simple, sky, beige, serif, solarized
       //   (you will need aditional css for default, night, moon themes).
       //   * transition can be: linear, zoom, fade, none
       livereveal.parameters('solarized-dark', 'zoom');
       console.log('Live reveal extension loaded correctly');
     });

});

// LIVE_REVEAL END
```

**Comment by damianavila** [comment]
Great!!
Thanks for let me know... I will close this one now, but this was really helpful to know exactly all the kind of info I have to ask for... probably I will write a little script to "diagnose" all these things. Thanks again!

**Comment by mjbright** [comment]
Hi Damian,

I think there's need of more general checking of extensions or kernels ..

I mean that there should be some way that the notebook can read some sort
of manifest and check that the extension or kernel is OK.
On a WIndows PC, I have a few zombie kernel entries from failed attempts
(or rather "successful kernel installs" that don't work).

Just throwing this out there, I should probably open an issue for this ...

Thanks for a great extension (I've never had any problem installing RISE by
the way),
Mike.

**Comment by damianavila** [comment]
>I think there's need of more general checking of extensions or kernels ..

Yep, we need to probably look into that in the near future...
