### ISSUE TITLE
Switching from presentation to notebook mode requires page reload

### ISSUE THREAD

**Issue by mcrovella** [damianavila/RISE#145]
Hi, I've been using RISE for about 9 months now and it's great. However I've never been able to switch back from presentation mode to notebook mode without reloading the page. When I leave presentation mode using option-R I get just a blank screen, ie looks like this:

![image](https://cloud.githubusercontent.com/assets/5775205/10004641/c83f6598-6080-11e5-92e7-98721685be40.png)

This requires then that I reload the page. 

Here's the requested info:

1)

[mac:RISE] % git show
commit d9f1c0d5ade93f61b50e97b03ee07c44d1356123
Merge: 7916199 2c48736
Author: Damián Avila <damianavila82@yahoo.com.ar>
Date:   Tue Sep 8 12:47:49 2015 -0300

    Merge pull request #139 from damianavila/hotfix/scrolling
    
    Add config option to scrolling slides.

2)

I installed RISE via python setup.py install.    

3) 

This is on Chrome version 45.0.2454.93

4) 

Javascript console before switching to presentation mode:

![image](https://cloud.githubusercontent.com/assets/5775205/10004535/332624ba-6080-11e5-905d-9bd4cca35dc9.png)

Javascript console after switching to presentation mode: no change.
Javascript console after switching back to notebook mode: also no change.

**Comment by ndawe** [comment]
I have the same issue after upgraded Jupyter.

**Comment by damianavila** [comment]
I was not able to reproduce it yet... @ndawe, if you have additional info besides what is was reported (specially any js console output if there is any), it will be welcome! Thanks!

**Comment by ndawe** [comment]
Here is the only js console output:

![screenshot from 2015-09-29 12 14 01](https://cloud.githubusercontent.com/assets/202816/10153854/dccd4592-66a3-11e5-822a-49456c381a74.png)

```
jupyter --version
4.0.6
ipython --version
4.0.0
```

Is that a problem? Should I uninstall ipython before installing jupyter? And then install RISE again?

**Comment by ndawe** [comment]
Chrome version 45.0.2454.101 (64-bit)

**Comment by ndawe** [comment]
After exiting the presentation mode, the URL is still something like http://localhost:8888/notebooks/tutorial.ipynb#/slide-0-0 and I need to remove the "#/slide-0-0" and reload.

**Comment by damianavila** [comment]
Exactly the same Chrome version and I can not reproduce it... @mcrovella, @ndawe, do you see this alo in other browsers or just Chrome/ium?
Also, in the blank page you get after exiting RISE mode, can you show me the "Elements" inside the JS console? Something like this:

![ele](https://cloud.githubusercontent.com/assets/1640669/10182606/4b5f854e-66fc-11e5-82ff-e58f252caffb.png)

Thanks!

**Comment by ndawe** [comment]
Strange. I'll get back to you with more details after tomorrow. I'm giving a presentation and I don't want to break anything now.

**Comment by damianavila** [comment]
> I'm giving a presentation and I don't want to break anything now.

That's ok,good luck with your presentation!

**Comment by mcrovella** [comment]
I have an update on this.   

It occurs when I use 'transition': 'fade'

It does NOT occur when I use 'transition': 'zoom'

The contents of my `~/.jupyter/nbconfig/livereveal.json` are:

`{
    "theme": "beige",
    "transition": "fade",
    "start_slideshow_at": "selected",
    "scroll": true
}`

**Comment by mcrovella** [comment]
Here is the screengrab of the JS console.

![image](https://cloud.githubusercontent.com/assets/5775205/10265395/5858c55a-69fc-11e5-8c8e-7ee306a4bf1e.png)

**Comment by damianavila** [comment]
>It occurs when I use 'transition': 'fade'

Oh... that could be a clue... let me investigate... :wink:

**Comment by mcrovella** [comment]
Yes, fixes the problem for me!   Thanks!

**Comment by ndawe** [comment]
Thanks! Fixed!
