### ISSUE TITLE
Any concise way to install RISE "globally" for Jupyterhub

### ISSUE THREAD

**Issue by Gnimuc** [damianavila/RISE#146]
i want to install RISE for several users which is created by jupyterhub, those paths look like:

```
/home/foo/
/home/bar/
/home/baz/
```

i can manually install RISE for those users by copying, for example, `/root/.local/share/jupyter/nbextensions` into `/home/foo/.local/share/jupyter/` firstly, and then running `JUPYTER_CONFIG_DIR=/home/foo/.jupyter python setup.py install`.

this is because each user created by jupyterhub has itsown `.local`, but `RISE` always install `nbextensions` in the path `/root/.local`.

i'm wondering is there a concise way to do this? am i missing something? 

thanks in advance ;)

**Comment by damianavila** [comment]
We should enable an option to install in --user. We use `install_nbextension` under the hood so it is just a matter of provide that option... marking as enhancement...

**Comment by damontallen** [comment]
Is RISE not compatible with the current release of IPython?  I followed the installation instructions in the README and got,

    Traceback (most recent call last):
      File "setup.py", line 2, in <module>
        from notebook.nbextensions import install_nbextension
    ImportError: No module named notebook.nbextensions

or is there something missing from the instructions?

**Comment by Gnimuc** [comment]
@damianavila are you using python3? if so, try running `python3 setup.py install`.

**Comment by damianavila** [comment]
>Is RISE not compatible with the current release of IPython? I followed the installation instructions in the README and got,

It should be... the current release of Jupyter have the notebook package, so you should not have an error like that in the current stable release, check here: https://github.com/jupyter/notebook/blob/master/notebook/nbextensions.py

@damontallen Do you have the `notebook` package installed?

**Comment by damianavila** [comment]
>@damianavila are you using python3?

@Gnimuc yes.. why?

**Comment by Gnimuc** [comment]
@damianavila sorry, I just mistakenly @ you :D

**Comment by damontallen** [comment]
@damianavila <https://github.com/damianavila> Sorry, I just tried python
2.7.  Python3 seems to have done it.  Thank you for all your hard work.

**Comment by damianavila** [comment]
>Thank you for all your hard work.

You are welcome!

**Comment by damianavila** [comment]
Closing this one in favor of #230 to avoid duplication.
