### ISSUE TITLE
Installing Rise with pip?

### ISSUE THREAD

**Issue by tschm** [damianavila/RISE#147]
Hi, I try to download and install Rise using pip (I would strongly prefer anaconda). Here's what I get...

Collecting git+http://github.com/damianavila/RISE.git (from -r /home/thomas/github/pymosek/requirements.txt (line 2))
  Cloning http://github.com/damianavila/RISE.git to /tmp/pip-KOo_6K-build
    Complete output from command python setup.py egg_info:
    usage: -c [-h] {install} ...
    -c: error: invalid choice: 'egg_info' (choose from 'install')
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 2 in /tmp/pip-KOo_6K-build

**Comment by damianavila** [comment]
@tschm Currently working in a branch to get a pip installable thing and conda packages as well...
I will let you know when it is ready...

**Comment by DavidPowell** [comment]
I am also keen to get a one line installation solution based on pip or conda, because I am trying to include RISE into a docker image I am creating, which is currently a bit complex.

**Comment by damianavila** [comment]
I know... I will be in vacation for a week, but I plan to deal with this when I come back...

**Comment by TMorville** [comment]
Hi Damian, and thanks for the effort! 

I am on the same wagon. After switching from Canopy to Anaconda (to get Python 3.x) I am getting used to installing with conda. 

If i use python setup.py install RISE does not seem to get registred in the Anaconda environment, even though my "which python" points to the anaconda bin. 

Anyway, a conda compatible installation would be great! Looking forward to using your package.

**Comment by akaihola** [comment]
@damianavila, could you push that branch here? I'd love to contribute if needed.

**Comment by ThomasA** [comment]
+1

**Comment by akaihola** [comment]
@damianavila, also, do you think this could be used: https://github.com/jdfreder/jupyter-pip

**Comment by akaihola** [comment]
I created an experimental pip compliant `setup.py`, see https://github.com/akaihola/RISE/commits/master

**Comment by damianavila** [comment]
PR merged, closing here...
