### ISSUE TITLE
Hiding Python code but not the output

### ISSUE THREAD

**Issue by tschm** [damianavila/RISE#150]
Hi, I want to hide some of the Python used to produce a graph but not the graph. Is there a way to achieve this?
thomas

**Comment by debsankha** [comment]
There is an IPython notebook plugin for that:
https://github.com/ipython-contrib/IPython-notebook-extensions/wiki/Hide-Input-All

**Comment by guidov** [comment]
This is also an very nice extension for this purpose and is easy to install:
https://github.com/kirbs-/hide_code

**Comment by damianavila** [comment]
Additionally, the hide functionality seems to be finally approaching the notebook in the future... ref: https://github.com/jupyter/notebook/issues/534

Closing as duplicate of #32
