### ISSUE TITLE
No theme applied to jupyter notebooks running under VirtualBox (accessed via port forward)

### ISSUE THREAD

**Issue by mjbright** [damianavila/RISE#152]
I'm using livereveal successfully under Windows, with themes working correctly.

However, I also have within a vagrant created virtual box
- a native (Anaconda/Python3) Jupyter
  The port 8888 is exposed outside VirtualBox as port 8880
- a Jupyter running under Docker (an image derived from jupyter/demo (docker-demo-images))
  The port 8888 is exposed outside Docker as port 8878 and then outside VirtualBox as port 8870

Both of these environments also work correctly with livereveal **but** the selected Sky theme is not applied - I just get black and white slides.

It looks to me like my configuration files are correct but it's as if the livereveal.json (in same /home/vagrant/.jupyter/nbconfig/ directory as notebook.json) isn't read.

Could this be due to the port forwarding?
Or is there some configuration to check? (seems OK compared to my Windows install).

**Comment by damianavila** [comment]
Interesting...

Can you `ls` the `/home/vagrant/.jupyter` and `/home/vagrant/.jupyter/nbconfig/` and also post the content of the notebook.json and livereveal.json files?

**Comment by mjbright** [comment]
Hi Damian,

Thanks, here's the files info.

Regards,
Mike.

vagrant@localhost ~ $ ls -altr /home/vagrant/.jupyter/


total 40


-rw-rw-r--  1 vagrant vagrant   105 Sep 26 19:28
jupyter_notebook_config.json


-rw-rw-r--  1 vagrant vagrant 19080 Sep 26 19:55 jupyter_notebook_config.py


-rw-rw-r--  1 vagrant vagrant    26 Sep 26 21:10 migrated


drwxrwxr-x  3 vagrant vagrant  4096 Oct  2 19:08 .


drwxr-xr-x  2 vagrant vagrant  4096 Oct  7 21:43 nbconfig


drwxr-xr-x 13 vagrant vagrant  4096 Oct  8 19:11 ..



vagrant@localhost ~ $ ll  -atr /home/vagrant/.jupyter/nbconfig/


total 24


-rw-rw-r-- 1 vagrant vagrant   63 Sep 26 19:28 tree.json


drwxrwxr-x 3 vagrant vagrant 4096 Oct  2 19:08 ..


-rw-rw-r-- 1 vagrant vagrant  197 Oct  7 21:30 livereveal.json


-rw-rw-r-- 1 vagrant vagrant  124 Oct  7 21:43 notebook.json.all


-rw-rw-r-- 1 vagrant vagrant   59 Oct  7 21:43 notebook.json


drwxr-xr-x 2 vagrant vagrant 4096 Oct  9 11:58 .

vagrant@localhost ~ $ cat /home/vagrant/.jupyter/nbconfig/livereveal.json


{


  "minScale": true,


  "theme": "Sky",


  "history": true,


  "slideNumber": true,


  "width": 1024,


  "controls": true,


  "height": 728,


  "start_slideshow_at": "selected",


  "transition": "zoom"


}


vagrant@localhost ~ $ cat /home/vagrant/.jupyter/nbconfig/notebook.json


{


  "load_extensions": {


    "livereveal/main": true


  }


}

On 9 October 2015 at 14:03, Damián Avila <notifications@github.com> wrote:
>
> Interesting...
>
> Can you ls the /home/vagrant/.jupyter and
/home/vagrant/.jupyter/nbconfig/ and also post the content of the
notebook.json and livereveal.json files?

**Comment by mjbright** [comment]
Hi again,

I tried again, with --debug mode and I saw the following line:


[W 12:07:22.356 NotebookApp] 404 GET
/nbextensions/livereveal/reveal.js/css/theme/Sky.css?v=20151009120623
(10.0.2.2) 4.74ms referer=
http://localhost:8880/notebooks/Presentations/2015-Oct-17_Pyconfr_Pau_IPython_vers_Jupyter/2015-Oct-17_Pyconfr_Pau_IPython_vers_Jupyter.ipynb

Hmm, effectively I don't see that file under /home/vagrant ... I'm sure I
did the other day ... searching ....


On 9 October 2015 at 14:13, Michael Bright <mjbrightfr@gmail.com> wrote:
>
>
> Hi Damian,
>
> Thanks, here's the files info.
>
> Regards,
> Mike.
>
> vagrant@localhost ~ $ ls -altr /home/vagrant/.jupyter/


> total 40


> -rw-rw-r--  1 vagrant vagrant   105 Sep 26 19:28
jupyter_notebook_config.json


> -rw-rw-r--  1 vagrant vagrant 19080 Sep 26 19:55
jupyter_notebook_config.py


> -rw-rw-r--  1 vagrant vagrant    26 Sep 26 21:10 migrated


> drwxrwxr-x  3 vagrant vagrant  4096 Oct  2 19:08 .


> drwxr-xr-x  2 vagrant vagrant  4096 Oct  7 21:43 nbconfig


> drwxr-xr-x 13 vagrant vagrant  4096 Oct  8 19:11 ..
>
>

> vagrant@localhost ~ $ ll  -atr /home/vagrant/.jupyter/nbconfig/


> total 24


> -rw-rw-r-- 1 vagrant vagrant   63 Sep 26 19:28 tree.json


> drwxrwxr-x 3 vagrant vagrant 4096 Oct  2 19:08 ..


> -rw-rw-r-- 1 vagrant vagrant  197 Oct  7 21:30 livereveal.json


> -rw-rw-r-- 1 vagrant vagrant  124 Oct  7 21:43 notebook.json.all


> -rw-rw-r-- 1 vagrant vagrant   59 Oct  7 21:43 notebook.json


> drwxr-xr-x 2 vagrant vagrant 4096 Oct  9 11:58 .
>
> vagrant@localhost ~ $ cat /home/vagrant/.jupyter/nbconfig/livereveal.json


> {


>   "minScale": true,


>   "theme": "Sky",


>   "history": true,


>   "slideNumber": true,


>   "width": 1024,


>   "controls": true,


>   "height": 728,


>   "start_slideshow_at": "selected",


>   "transition": "zoom"


> }


> vagrant@localhost ~ $ cat /home/vagrant/.jupyter/nbconfig/notebook.json


> {


>   "load_extensions": {


>     "livereveal/main": true


>   }


> }
>
> On 9 October 2015 at 14:03, Damián Avila <notifications@github.com> wrote:
> >
> > Interesting...
> >
> > Can you ls the /home/vagrant/.jupyter and
/home/vagrant/.jupyter/nbconfig/ and also post the content of the
notebook.json and livereveal.json files?

**Comment by mjbright** [comment]
OK, looks like a CASE-typo in my original livereveal.json ... which of
course wasn't a problem under the toy Windows file system! but is on a real
file system.

/home/vagrant/.local/share/jupyter/nbextensions/livereveal/reveal.js/css/theme/sky.css

Thanks for getting me to think !
It's working now.

**Comment by damianavila** [comment]
Great!! Closing now...
