### ISSUE TITLE
Simplify configuration with kernels different from python

### ISSUE THREAD

**Issue by fcremo** [damianavila/RISE#153]
Using RISE with the bash kernel I had trouble changing reveal.js configuration since AFAIK that requires running python code or manually editing `livereveal.json`.
Besides, having a single configuration file for all notebooks is not flexible.
I made a patch (https://github.com/fcremo/RISE/commit/c4cce3153f5cb0eedcf6cc88fabb523560027bbb) that adds the possibility of putting the configuration in the notebook metadata.

It would be nice to have a clean way to include additional configuration in the notebook cells so that settings such as the theme and the transition animation could be changed during the presentation.
A possibility could be to add a new "slide type" containing a js object.

**Comment by damianavila** [comment]
The idea of a new slyde type is probably more difficult to implement because involves changes uptream... but the config patch you made makes sense as another entry point to config the slideshow... so I would be inclined to accept a PR adding this option...

**Comment by damianavila** [comment]
Close by #156
