### ISSUE TITLE
Trouble installing RISE

### ISSUE THREAD

**Issue by ThomasA** [damianavila/RISE#160]
I have previously had trouble with RISE (see #117) so now that I needed it again, I decided to install it anew.
I have created a fresh conda environment (using Continuum Anaconda) in which I try to install RISE. In am now running Python 2.7.10 with `jupyter-notebook` 4.0.6. I have pulled the latest version of RISE (latest commit is b6b197eef9b72fa0050f61b841da58377946229d). I have run `python setup.py install`. The latter returned no output, but RISE appeared to be installed correctly afterwards:

    $ ls ~/.local/share/jupyter/nbextensions/livereveal/
    main.css  main.js  main.orig.css  reset_reveal.css  reveal.js

    $ cat ~/.jupyter/nbconfig/notebook.json 
    {
      "load_extensions": {
        "livereveal/main": true
      }
    }

However, when I start Jupyter and open a notebook (and I have tried this using Firefox as well as Chromium - in case something like #117 had re-surfaced) there is no slideshow button where it used to be. The JavaScript console says:

    main.min.js:23893 Default extension for cell metadata editing loaded.
    main.min.js:23979 Raw Cell Format toolbar preset loaded.
    main.min.js:24027 Slideshow extension for metadata editing loaded.
    main.min.js:30216 No exact match found for python3, using only kernel that matches language=python Object
    main.min.js:23181 Session: kernel_created (5f27d2c3-9961-45ad-8b14-b63370051336)
    main.min.js:22502 Starting WebSockets: ws://localhost:8888/api/kernels/e1d64915-88bf-406b-923f-c3743acea70c
    :8888/custom/custom.js?v=20151019211609:65 Uncaught TypeError: livereveal.parameters is not a function
    main.min.js:22160 Kernel: kernel_connected (e1d64915-88bf-406b-923f-c3743acea70c)
    main.min.js:22160 Kernel: kernel_ready (e1d64915-88bf-406b-923f-c3743acea70c)
    main.min.js:12030 Loaded extension: widgets/notebook/js/extension
    :8888/nbextensions/widgets/notebook/js/extension.js?v=20151019211609:81 loaded widgets
    sci_pack_visualisation.ipynb:1 Font from origin 'null' has been blocked from loading by Cross-Origin Resource Sharing policy: Invalid response. Origin 'http://localhost:8888' is therefore not allowed access.

So there appears to be some 'livereveal'-related errors, but I don't know what they mean...

**Comment by ThomasA** [comment]
Bonus info: it behaves the same if I try with Python 3.4.3 instead.

**Comment by ThomasA** [comment]
Now I tried deleting `~/.jupyter/nbconfig/notebook.json` and the directory `~/.local/share/jupyter/nbextensions/livereveal/` and then installed RISE from scratch. It still does not work and complains about the same things in the JavaScript console.

**Comment by ThomasA** [comment]
Maybe the `custom.js` that it seems to choke on is a left-over from an old install that I should delete?
I have now tried deleting `~/.jupyter/custom/custom.js`, but apparently this was not the `custom.js` being used. The JavaScript console still shows *some* `custom.js` choking on "livereveal.parameters is not a function", but how can I locate the `custom.js` script in use here?

**Comment by ThomasA** [comment]
OK, found the error: I located and deleted the problematic `custom.js` in `~/.ipython/profile_default/static/custom/custom.js`. Now RISE is working again after another run of `setup.py`.
This confused me as I thought `jupyter-notebook` would only be using the configuration in `~/.jupyter` after the rename, but apparently it is picking up config from `~/.ipython/` as well.

**Comment by damianavila** [comment]
Sorry to not attend on this... I was on holidays for a week, nice you find the issue! Thanks!
