### ISSUE TITLE
Does this work with Jupyter 4?

### ISSUE THREAD

**Issue by ijstokes** [damianavila/RISE#163]
The steps work to install RISE, but it doesn't look like it shows up in my Notebook. Just wondering if this is something that should work or might work at some point in the future.

**Comment by ijstokes** [comment]
Should have searched existing issues. #160  addressed my issue.

**Comment by bs1234** [comment]
I'm using Jupyter 4.06 and work ok for me.

Probably superfluous but need to shut down and restart the notebook ;)

Details:
The version of the notebook server is 4.0.6 and is running on:
Python 3.4.3 |Anaconda 2.0.1 (64-bit)| (default, Mar  6 2015, 12:06:10) [MSC v.1600 64 bit (AMD64)]
