### ISSUE TITLE
Add a backgroung image to the slideshow

### ISSUE THREAD

**Issue by nusselt85** [damianavila/RISE#167]
Is it possible to add a background image for the slideshow?
In reveal.js the data-background="image.png" is used but I have not be able to make it work

**Comment by damianavila** [comment]
It should be possible but you probably need to hack on the source code... we did not provide data-background capabilities yet...

**Comment by soamaven** [comment]
This would be a very welcome awesome. I wish I knew css to help implement this customization through the notebook metadata.

Am going to attempt to create a custom theme with my desired background image, would you recommend this approach for a css novice?

**Comment by soamaven** [comment]
I learned as much css as I could overnight... I tried to copy one of the .css themes and simply edit the "body" div to be 
`body {
  background: url('image.png');
 background-position: cover
}`

I then used the metadata method to call this new them. No luck. 
Having trouble with calling some of the other themes with this method however, so maybe its not the .css code here

**Comment by seddon-software** [comment]
You can add a background image (with a linear gradient) as below, by adding code to the custom.css file.  The file must be in the directory:
  *    ~/.jupyter/custom/custom.css

<pre>
.rise-enabled {
    background-color: azure !important;
    font-size: 125% !important;
    background-image: url(CRS-Enterprises.jpg), linear-gradient(30deg, #7ab8ec, white 75%, white);
    background-position: right top;
    background-repeat: no-repeat;
    background-origin: content-box;
    padding: 5px 5px 5px 5px;
}
</pre>

**Comment by soamaven** [comment]
If I don't have a custom.css file, should this be the only content of a new file named custom.css?

**Comment by damianavila** [comment]
We provide now a new mechanism to add a background image, see #296 and #310. Closing here.

**Comment by Foadsf** [comment]
One workaround is to use HTML adding a background image:


```
<div style="background-image: url(pics/bg1.png); background-repeat: no-repeat; background-size: contain; height: auto; width: 100%; ">
 this is
some 

text on top of the background 

image
</div>
```
