### ISSUE TITLE
RISE fonctionality

### ISSUE THREAD

**Issue by jcrichard** [damianavila/RISE#171]
Is it normal that function like pause (when press B) or the view (when press ESC) and so one are not available with RISE like it is with static nbconverter ?

Thanks

**Comment by damianavila** [comment]
I could be some clashes with the keys used in the live notebook, so you can expect some keys are changes... if you git the help butoom, you will see the available keys on RISE...

**Comment by jcrichard** [comment]
Thank you D'amiante. My point is for example if you want to have the all slide view usually with Escape I do it. But i

**Comment by jcrichard** [comment]
I can't do the same with RISE

**Comment by damianavila** [comment]
you can do it with `w` iirc...

**Comment by jcrichard** [comment]
Ok I will try. Thank you for Rise this is awesome

**Comment by jcrichard** [comment]
Ok it is working. Sorry I did'nt see the w...
I still have a problem with the slide font_size, it is too big. Can I change it with metadata or other ?

Thank you

**Comment by damianavila** [comment]
You should be able to change the font playing with width and height... or modifying the less/css in the source code...

**Comment by jcrichard** [comment]
Ok thank you very much.  Sorry I am not comfortable with htlm / css. 
It's working.

**Comment by damianavila** [comment]
Ok thank you very much. Sorry I am not comfortable with htlm / css. 
It's working.

Nice, closing here...
