### ISSUE TITLE
Adding header or footer to slides

### ISSUE THREAD

**Issue by nigeljyng** [damianavila/RISE#173]
Is there any way to add a header or footer to every slide? Other than hacking the source code.

Thanks for the great work, Damian.

**Comment by damianavila** [comment]
pinging @fpliger :wink: he did some work on this, but not sure if he abstracted the thing enough to make a PR (I hope so...)

**Comment by fpliger** [comment]
Ah.. I'm guilty on this. :)

I did some work that [I guess] can be reused and [hopefully] turned into a PR. @nigeljyng what are your time constraints? I'm on many different deadlines ATM... :/

**Comment by nigeljyng** [comment]
Early January would be nice, if that's feasible for you!

**Comment by jmansour** [comment]
Hey folks.  End up getting any traction on this feature?

**Comment by jneines** [comment]
I would like to give a +1 on this. I'm looking into using RISE as another option for company level presentations and therefore need to follow corporate identity design. It's important to be able to place logos, Author, company and date at a specific location visible throughout the presentation. Furthermore a section title should be visible at the top of the screen as well. This definitly sounds like using header and footer areas for this.

I'm currently looking into using a custom.js to relocate header elements (h1,h2,..) out of the slides context to make this happen via jquery based insertBefore and insertAfter, but with limited success. Is there a RISE specific javascript event, which I could hook on to when slideshow mode is enabled? Does the idea sound reasonable after all?

**Comment by damianavila** [comment]
> s there a RISE specific javascript event, which I could hook on to when slideshow mode is enabled? 

You can probably use some of the Reveal.js events... or maybe use some of the notebook machinary to signal that...

>Does the idea sound reasonable after all?

It is one approach, probably not the one I would choose. @fpliger do you have the branch you were working on this doing experimentation? It would be nice to make it public so others can continue the work :wink: Thanks!

**Comment by fpliger** [comment]
>> Does the idea sound reasonable after all?

> It is one approach, probably not the one I would choose. @fpliger do you have the branch you were working on this doing experimentation? It would be nice to make it public so others can continue the work 😉 Thanks!

Oh man.. I've changed laptop in the meanwhile. Will check but not feeling very lucky there.

**Comment by damianavila** [comment]
> Oh man.. I've changed laptop in the meanwhile. Will check but not feeling very lucky there.

Thanks OK...let's see if we are lucky... otherwise if you can drop the ideas (if you remember them). Thanks!

**Comment by fpliger** [comment]
@damianavila  found something... 😄 

The main idea was to extend the [Revealer](https://github.com/damianavila/RISE/blob/4d187419d6c1ff7a5a6bab81ed8a76668c815830/rise/static/main.js#L209-L305) with hooks to load modifiers (js+css) that can be appended to head in order to customize the content. I'd see this more as a config file that the user can customize and the `Revealer` will read.. but in my case I've just patched that function manually. 

Hope this helps

**Comment by jneines** [comment]
Glad you found something. Any chance you could share some sample code? JavaScript and the whole implementation behind Reveal.js and RISE is not my comfort zone. I was hoping to find a suitable place to just drop in necessary changes and addons. My hope was that I could create a custom.js and custom.css file, which could be activated when entering the presentation mode and perform some rearrangements. I can't seem to find a suitable event to hook on to. Any test to successfully trigger own code in custom.js didn't get me to the point where I had a "living" Reveal object, which I could modify in behaviour. I've managed to see the all the methods of a Reveal object in Chromes developer tools, but any try to use one of the methods revealed an unknown method of a null object. Probably seems I have a notable lack of JavaScript knowledge which needs to be closed first.

**Comment by damianavila** [comment]
> Hope this helps

Thanks for the input @fpliger!

**Comment by damianavila** [comment]
#296 and #310 solved this request, closing now.

**Comment by Faris-Faiz** [comment]
Uncle Roger opened this issue bruh
