### ISSUE TITLE
Speaker view does not display slides

### ISSUE THREAD

**Issue by raphaelcastaneda** [damianavila/RISE#174]
Once in a reveal slideshow, pressing the `S` key opens the reveal.js speaker view, however the windows for current and upcoming slides display the normal jupyter notebook page.

Workaround:
I've found that it is possible within the tiny slide views to open up slideshow mode, and advance the "upcoming slide" window by 1 slide. This works, but it is quite annoying to do each time.

**Comment by damianavila** [comment]
.Workaround:
I've found that it is possible within the tiny slide views to open up slideshow mode, and advance the "upcoming slide" window by 1 slide. This works, but it is quite annoying to do each time.

Yeah, inception... It is in my plans to support it... no timeframe yet...

**Comment by schlichtanders** [comment]
I just saw that currently the speaker views seems to be disabled completely, 
any plans to support in the near future?

**Comment by damianavila** [comment]
> any plans to support in the near future?

Not the first priority right now, but it would be a nice to have, I agree.

**Comment by mbewley** [comment]
+1 - would like speaker notes to work! Planning on switching from powerpoint to Jupyter + RISE for technical talks and lectures, but I tend to use speaker notes a fair bit.

**Comment by leftys** [comment]
+1 - this feature is really crucial for me

**Comment by dmarx** [comment]
:+1:

**Comment by mbrennan** [comment]
Any progress on this?  Can one show speaker notes in a RISE presentation?

**Comment by damianavila** [comment]
> Any progress on this? Can one show speaker notes in a RISE presentation?

No progress yet...

**Comment by mbrennan** [comment]
I noticed that speaker notes are available in the "full installation" of reveal.js here:  https://github.com/hakimel/reveal.js#full-setup.  Is there a way to have the presentation from Jupyter Notebook served up by a separate reveal.js node instance so the notes can be made available?

**Comment by damianavila** [comment]
> Is there a way to have the presentation from Jupyter Notebook served up by a separate reveal.js node instance so the notes can be made available?

Nop, we already ship reveal.js and it contains the notes plugin, BUT we need to modify that plugin to show us the slideshow view instead of the notebook view.

**Comment by lballabio** [comment]
+1

**Comment by damianavila** [comment]
Good news: https://github.com/damianavila/RISE/pull/412, but shhh... it is a surprise for my talk at JupyterCon, jeje...
