### ISSUE TITLE
change theme not work?

### ISSUE THREAD

**Issue by WeiLiPenguin** [damianavila/RISE#177]
When I want to change to another theme, it not work and show some information under the terminal:

```
404 GET /nbextensions/livereveal/reveal.js/css/theme/Sky.css?v=20160112180652 (127.0.0.1) 9.82ms referer=http://localhost:8888/notebooks/Untitled.ipynb
```

Is that means RISE try to find the css file under `/nbextensions/`, but the css file was install under `.local/share/jupyter/nbextensions/` ?

So what I did wrong with the settings?

I also check with:

``` python
from __future__ import print_function
from jupyter_core.paths import jupyter_data_dir, jupyter_path
print(jupyter_data_dir())
print(jupyter_path())
```

it return:

```
/home/myname/.local/share/jupyter
['/home/myname/.local/share/jupyter', '/home/myname/bin/miniconda2/envs/work/share/jupyter', '/usr/local/share/jupyter', '/usr/share/jupyter']
```

ipython version: 4.0.1

Please help me! Thanks!

**Comment by damianavila** [comment]
@WeiLiPenguin the sky theme is working for me with master and notebook 4.2.1, how did you try to change the config to actually use it?

**Comment by damianavila** [comment]
Tested several times, including latest release with notebook 5 and it works as expected. Closing here.
