### ISSUE TITLE
strange equation bug in markdown

### ISSUE THREAD

**Issue by augustot2** [damianavila/RISE#181]
After installing RISE, I'm having a strange bug, that in the end of every equation, apears a long pipe in the end of it
![equation](https://cloud.githubusercontent.com/assets/8473997/12823661/63caee4a-cb54-11e5-9402-9e0e1c87b9c9.png)

**Comment by damianavila** [comment]
Can you post the notebook somewhere to take a look? Thanks!

**Comment by augustot2** [comment]
http://nbviewer.jupyter.org/github/augustot2/notebooks/blob/master/static_cond.ipynb

**Comment by augustot2** [comment]
![strange](https://cloud.githubusercontent.com/assets/8473997/12846171/13b55d02-cbf2-11e5-9587-caae47c3eaf2.png)

**Comment by willwray** [comment]
Looks like a chrome 48 rounding issue interacting with mathjax

http://stackoverflow.com/questions/35171714/ipython-jupyter-notebook-producing-ghost-line-in-all-equations

> This is a change in Chrome, affecting MathJax 2.5, which ships with Jupyter Notebook 4.1. Notebook 4.2 will bundle MathJax 2.6, which will fix this problem. In the meantime, you can tell the notebook to use latest MathJax from the CDN, by adding to ~/.jupyter/jupyter_notebook_config.py:

>c.NotebookApp.mathjax_url = "https://cdn.mathjax.org/mathjax/latest/MathJax.js"
Other browsers do not appear to be affected.

http://stackoverflow.com/questions/34277967/chrome-rendering-mathjax-equations-with-a-trailing-vertical-line

**Comment by augustot2** [comment]
thx, i will change to firefox for now on.
