### ISSUE TITLE
button not showing up with big input

### ISSUE THREAD

**Issue by parmentelat** [damianavila/RISE#182]
Hey folks

Here's what I can see on my end. With a reasonably small slideshow I get everything working as expected, but with a much larger input:
- at first upon loading, I get a small note at the bottom of the page saying `Loading [MathJax]/extensions/Safe.js`; is stays for a little while, like maybe 8 seconds
- then my input shows up, but the magic button to turn on slideshow is not present
- the Console at this point has in particular this message that might be relevant:

```
ipywidgets package not installed.  Widgets are not available.
main.min.js:12049 Failed to load extensions: Array[2] 
Error: Load timeout for modules: nbextensions/widgets/notebook/js/extension,nbextensions/livereveal/main(…)(anonymous function) @ main.min.js:12049
```

To give you a sense:
- this input is originally a pack of powerpoint about 400-slides that I am in the process of automatically translating into a notebook, knowing that the translator at this point is very rough.
- first half of that (actually 223 slides) : works  fine
- second half of that (actually 164 slides) : works fine too

So it feels like it's not a problem with the contents, but with the size.
And it also suggests that the way all the stuff is pulled by the browser is a little congested or not totally asynchoneous or something along those lines.

I can provide the inputs if that helps

PS.
I just gave it another try with other network - better - conditions; and I can now load the full stack OK.
But then if I just artificially double the input size (by concatenating the same contents twice), I run into the issue again.

Thank you for your kind feedback - and for the awesome tool, of course :)

**Comment by parmentelat** [comment]
Not sure if that's relevant, but just in case

```
~/git/RISE $ type jupyter
jupyter is hashed (/opt/local/Library/Frameworks/Python.framework/Versions/3.5/bin/jupyter)
~/git/RISE $ jupyter --version
4.0.6
~/git/RISE $ python3
Python 3.5.1 (default, Dec  8 2015, 13:20:16)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.1.76)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ipywidgets
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'ipywidgets'
```

Is this to say that I should have pip3-installed ipywidgets ?

**Comment by nolefp** [comment]
I actually had the same issue, not with a slideshow but just a really long notebook with lots of graphics. It wouldn't load for forever, then it was supper slow, and then it started loading without the nbextenions i had on, like table of contents, etc...

**Comment by damianavila** [comment]
@parmentelat do you have any example notebook I can test so I can reproduce the behavior? Thanks!

**Comment by parmentelat** [comment]
Sorry, it looks like this one fell off my radar entirely...

I do not have the source in question anymore, when hitting the issue I split the material into smaller pieces as it was my only way out. 

Reading this again one year later with a little more experience, this feels like this issue belonged more in the notebook area than rise proper.

**Comment by damianavila** [comment]
> Reading this again one year later with a little more experience, this feels like this issue belonged more in the notebook area than rise proper.

Yep, that is my understanding as well... I guess I will close this one and let the others to re-open it if the behavior appears consistently again.
