### ISSUE TITLE
scrolling vertically

### ISSUE THREAD

**Issue by ephes** [damianavila/RISE#185]
Hi,

I have some big code cells that won't fit vertically on one slide. Unfortunately I've found no way to scroll in presentation mode, but maybe I'm just missing some configuration option :).

best regards,
jochen

**Comment by Velcin** [comment]
One solution is to toggle the option "scroll" to the value "true" in the "main.js" file.

I guess you can also edit the config file in jupyter.

julien

**Comment by ephes** [comment]
Thanks, I tried that, but it didn't work.

**Comment by hfinger** [comment]
For me that works, thanks. What I did was the following. I opened a notebook and executed:
```
from notebook.services.config import ConfigManager
cm = ConfigManager()
cm.update('livereveal', {
        'width': 1024,
        'height': 768,
        'scroll': true,
})
```
Then I had to restart jupyter notebook so that these changes took effect. After that I have a scrollbar during the presentation.

**Comment by soamaven** [comment]
Changing the main file at `.local/share/jupyter/nbextensions/livereveal/main.js` to have scroll be `true` fixes this for me. 

I would support that this should be set to `true` by **default**, since this is the case for static slide shows with `reveal.js` and _more importantly_, since I don't know of a way to know before-hand what will fit onto the screen.

**Comment by damianavila** [comment]
After several and long discussions with a lot of people, we have arrived to the conclusion that scrolling on reveal.js based slideshows brings more problems than benefits, so I will not add the scrolling as a default option BUT we should clearly document how to get scrolling slides with the config option available. I will mark this as a docs issue and prioritize properly.

**Comment by rahuldave** [comment]
Where do you set the "true"? My main.js (under .ipython) reads:

```
var config = new configmod.ConfigWithDefaults(config_section, {
    controls: true,
    progress: true,
    history: true,
    scroll: true,
    width: 1140,
    height: 855, // 4:3 ratio
    minScale: 1.0, //we need this for codemirror to work right
    theme: 'simple',
    transition: 'linear',
    slideNumber: true,
    start_slideshow_at: 'beginning',
});
```

Meanwhile `~/.jupyter/nbconfig/livereveal.json` reads:

```
{
  "start_slideshow_at": "selected",
  "theme": "serif",
  "transition": "zoom",
  "width": 1024,
  "height": 768,
  "scroll": true
}
```

Either way it ought to work, but no scrollbar on restart....

**Comment by damianavila** [comment]
Can you try hard setting your browser or clear the browser cache... because if the scroll option is true in livereveal.json, you should see the scrollbar after reloading the page.

**Comment by fproldan** [comment]
@rahuldave You did it work?

My livereveal.json is:
```
{
  "start_slideshow_at": "selected", 
  "transition": "zoom", 
  "height": 768, 
  "width": 1024, 
  "theme": "simple", 
  "scroll": true
}     
``` 
I cleared the browser cache and restart jupyter but the scroll didn't work

Thanks

**Comment by damianavila** [comment]
@fproldan there is a beta for the next release: http://www.damian.oquanta.info/posts/rise-400b1-is-available-please-test-it.html
I tested on that beta and works for me, please report back if it is not working with the beta.

**Comment by fproldan** [comment]
@damianavila I searched for all of the main.js under rise after i found the right one, and now it works like a charm!
Sorry for bother you.
Regards!

**Comment by damianavila** [comment]
@fproldan no problem, but you should be modifying main.js, the config mechanism allow you to have scrolling behavior... that did not work for you in the beta?

**Comment by dmardanbeigi** [comment]
I have edited the main.js file which was inside /usr/local/lib/python2.7/site-packages/rise/static and have also added the code below into my notebook: 
`from traitlets.config.manager import BaseJSONConfigManager
path = "/Users/XXX/.jupyter/nbconfig"
cm = BaseJSONConfigManager(config_dir=path)
cm.update('livereveal', {
              'scroll': True,'width': 1024,
              'height': 768,})`

However the vertical scrolling is not working on safari and chrome!

**Comment by damianavila** [comment]
> However the vertical scrolling is not working on safari and chrome!

So it works in firefox and not in the others? Can you provide the chrome version number?

**Comment by dmardanbeigi** [comment]
chrome Version 55.0.2883.95 (64-bit) and safari Version 10.0.2 (12602.3.12.0.1) on mac. Non of them work. I haven't tried firefox

**Comment by damianavila** [comment]
OK, I will try to check those version, thanks for the update!

**Comment by twiecki** [comment]
I have also tried all three techniques and am up-to-date on RISE, but none bring back the scroll bar. This is on Chrome + OSX.

**Comment by twiecki** [comment]
@damianavila Is there an older version I can downgrade to that preceded changing the default?

**Comment by damianavila** [comment]
@twiecki, will check this issues in the next few days... older versions may work but I did not tested.

**Comment by wzpan** [comment]
Same problem on Chrome/Safari/Firefox on my Mac.

**Comment by damianavila** [comment]
Timing issue... PR fixing this lives here: https://github.com/damianavila/RISE/pull/258

**Comment by damianavila** [comment]
> Timing issue... PR fixing this lives here: #258

Fixed by #259.

**Comment by danmalter** [comment]
Scrolling works for me with the following code if you take out `"start_slideshow_at": "selected", ` in `~/.jupyter/nbconfig/livereveal.json.`  For some reason I noticed that with `"start_slideshow_at": "selected", ` in the .js file, the scrolling only worked if you started from the first slide.  If you started from a later slide, the scrolling would not work.

```
{
  "theme": "serif",
  "transition": "zoom",
  "width": 1024,
  "height": 768,
  "scroll": true
}
```

**Comment by damianavila** [comment]
> the scrolling only worked if you started from the first slide. If you started from a later slide, the scrolling would not work.

Interesting, can you open a new issue to explore this problem @danmalter? Thanks!
