### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by QCaudron** [damianavila/RISE#186]
After entering RISE mode using Alt + R, and then exiting again, my shortcuts ( shift + Enter, Ctrl + Enter ) seem to stop working. Any help, much appreciated. Thanks !

I've just installed RISE today. IPython is on 4.1.2, Jupyter is 1.0.0.

#179 looks relevant !

**Comment by damianavila** [comment]
This is no longer an issue on master, probably fixed by #179, closing here.
