### ISSUE TITLE
Changing configuration doesn't affect unless re-opening the notebook

### ISSUE THREAD

**Issue by jluttine** [damianavila/RISE#194]
I have the following in one of my cells:
```
from notebook.services.config import ConfigManager
cm = ConfigManager()
cm.update('livereveal', {
              'width': 1024,
              'height': 768,
})
```
I execute the cell and enter RISE mode, but it has no effect. If I close the tab and re-open the notebook, then it takes effect. I think executing config cells should affect immediately?

**Comment by damianavila** [comment]
Since the params at read from the config when the notebook load, you need to reload the page to apply the changes... but we should be loading the config before entering the slideshow mode, so we can change things immediately...

**Comment by damianavila** [comment]
I put a PR to solve this, check: https://github.com/damianavila/RISE/pull/201

**Comment by damianavila** [comment]
PR merged, closing here.
