### ISSUE TITLE
Space for output cells

### ISSUE THREAD

**Issue by seddon-software** [damianavila/RISE#196]
Is it possible to pre-allocate space for output cells in the presentation.  At the moment slideshow centres the slide vertically, but when code is run it often disappears off the bottom of the slide.  I'd prefer the input cell be displayed as high up on the screen as possible, but I can't work out how to do that with custom CSS.

**Comment by seddon-software** [comment]
OK, I've found a workaround.

**Comment by damianavila** [comment]
@seddon-software Can you share the workaround for others? Thanks!
