### ISSUE TITLE
Slideshow not working

### ISSUE THREAD

**Issue by Boosted09Foci** [damianavila/RISE#197]
I have the reveal installed in my nbextensions.

The slideshow button is on my notebook toolbar.  However,  I have no option to set my cells as a "slide"??  Do I need to reinstall?

**Comment by ThomasA** [comment]
I think it is a feature of Jupyter Notebook to hide this. Look for an option in Jupyter's menus to display the slideshow toolbar. I expect that will do the trick.

On 17. jun. 2016 16.16.48 CEST, Boosted09Foci <notifications@github.com> wrote:
>I have the reveal installed in my nbextensions.
>
>The slideshow button is on my notebook toolbar.  However,  I have no
>option to set my cells as a "slide"??  Do I need to reinstall?
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/damianavila/RISE/issues/197

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Boosted09Foci** [comment]
The menu within the notebook? or do I need to look in the menu directory?

**Comment by Boosted09Foci** [comment]
Found it! 

I had to manually copy the lastest livereveal folder into the .python/nbextensions directory.  

To make each cell a slide go to the following in the notebook:

view >> Cell Toolbar >> Slideshow

Thanks for the help!

**Comment by ThomasA** [comment]
The option is in one of Jupyter's menus in an open notebook. I do not have my computer with me now, so I cannot check where. 

On 17. jun. 2016 17.13.06 CEST, Boosted09Foci <notifications@github.com> wrote:
>The menu within the notebook? or do I need to look in the menu
>directory?
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/damianavila/RISE/issues/197#issuecomment-226796503

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ThomasA** [comment]
That's the menu I was thinking of. Great that you found it.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by damianavila** [comment]
https://github.com/damianavila/RISE/issues/159 to track the need for info...

**Comment by Saho12** [comment]
Can some please help me on this 
https://github.com/damianavila/RISE/issues/420#issuecomment-626047346

It is quite urgent for me.
