### ISSUE TITLE
CSS Styling

### ISSUE THREAD

**Issue by seddon-software** [damianavila/RISE#198]
I'm having trouble understanding how to style presentation slides such that each slide's header is placed at the top of the screen.  At present, each slide is vertically centred.  I've searched all the loaded CSS classes, using the Chrome debugger, but I can't find the CSS positioning style or class.  I get the impression the heights are calculated by your code.  Could you explain which CSS is used to position the slide, so I can modify it to position at the top of the screen please.

**Comment by seddon-software** [comment]
I'm having trouble understanding how to style presentation slides such that each slide's header is placed at the top of the screen. At present, each slide is vertically centred. I've searched all the loaded CSS classes, using the Chrome debugger, but I can't find the CSS positioning style or class. I get the impression the heights are calculated by your code. Could you explain which CSS is used to position the slide, so I can modify it to position at the top of the screen please.

**Comment by jneines** [comment]
I'm looking at the exact same thing currently and would like to reactivate this discussion a bit. My current approach was to use the different HTML heading tags for this. Markdown # mapping to h1, ## mapping to h2 and so forth. I created a custom.css in ~/.jupyter/custom/ for this ad tried to overwrite the active css settings for these tags with a fixed location to force rendering at the top of the screen. 

E.g.

h1 { location: fixed !important; top: 0px; }

However this does not lead to the desired behaviour. Some other setting seems to prevent the adjustments to be respected, and I have currently no idea where to look for this.

**Comment by damianavila** [comment]
There are a lot of stuff which is automatically calculated/applied by Reveal.js... can you put an example here with notebook and custom.css so I can start looking into it. Thanks!

**Comment by damianavila** [comment]
Discussion is already happening in #95, closing here.
