### ISSUE TITLE
cell toolbar/selection is not available

### ISSUE THREAD

**Issue by fredthedead** [damianavila/RISE#199]
I have just installed RISE on Jupyter 4.1.0, I am getting the start/stop slideshow button - but not the cell selection buttons (to select which cells should go into the slideshow). 

I went through the previous resolved issues regarding the jupyter directory levels and tried the solutions suggested there without success.

**Comment by ThomasA** [comment]
Did you try the solution in #197? You can find the menu item to enable it as shown in the image here:
![skaermbillede fra 2016-07-05 11-31-09](https://cloud.githubusercontent.com/assets/971307/16580366/61767476-42a4-11e6-9c67-b53acb36cd6c.png)

**Comment by damianavila** [comment]
Closing, we need a mention at the README: https://github.com/damianavila/RISE/issues/159
