### ISSUE TITLE
Code lines inside a Markdown cell cutoff

### ISSUE THREAD

**Issue by daniil-konovalenko** [damianavila/RISE#202]
Code lines inside Markdows cells are cut.

![image](https://cloud.githubusercontent.com/assets/11165516/17075836/231c46f2-50a9-11e6-9afb-43281b585f50.png)

Occurs in Chrome, Opera

**Comment by damianavila** [comment]
Thanks for the report, I will take a look.

**Comment by damianavila** [comment]
Tested in latest release and this is no longer a problem. Closing now.
