### ISSUE TITLE
RISE is unresponsive to different screen sizes

### ISSUE THREAD

**Issue by engyasin** [damianavila/RISE#207]
the live slideshow is hiding some parts of the slide when changing the window of the browser (chrome) (windows 7 32bit , python 2.7 , jupyter 4.0)
 no problem when maximizing the window , but with some kinds of projector the screen size change and cause this issue..
any help :) 
![image](https://cloud.githubusercontent.com/assets/15736151/17478498/db55a222-5d74-11e6-9a50-5aaaf5423bf5.png)

**Comment by damianavila** [comment]
On this section https://github.com/damianavila/RISE#configure-your-own-options you will have some info about how to customize height and width, I guess it is the best option for you, just use the projector screen size and check if it fits better.

**Comment by parmentelat** [comment]
and/or use your browser's shortcuts to zoom in/out, like on a mac command+ and command- can help too

**Comment by damianavila** [comment]
> and/or use your browser's shortcuts to zoom in/out, like on a mac command+ and command- can help too

That's correct as well, we should probably add this note to the README.

**Comment by damianavila** [comment]
Closed by #339
