### ISSUE TITLE
Installation instructions for beta

### ISSUE THREAD

**Issue by willingc** [damianavila/RISE#215]
Hi @damianavila,

Trying out RISE beta today. Ran into a small install issue. I needed to remove my ``.jupyter`` config info to get the conda extension to load properly. Also needed to ``conda install jupyterlab``.

Will let you know how the rest goes 👍

**Comment by willingc** [comment]
Beta feedback:

- [ ] pressing End Tour does not close window 
<img width="489" alt="screen shot 2016-08-11 at 3 42 38 am" src="https://cloud.githubusercontent.com/assets/2680980/17586311/ca675b60-5f75-11e6-9e05-f103cfd2cc3f.png">

**Comment by damianavila** [comment]
@willingc this does not look like RISE :wink:, it seems nbpresent... am I right?

**Comment by willingc** [comment]
@damianavila Could be. I'm not very familiar with nbpresent. 

Which would bring up my next question, what steps need to be done to enable RISE? :D

**Comment by damianavila** [comment]
This is the RISE repo and the UI has not changed at all.

You can install RISE with conda now: `conda install -c damianavila82 rise`

and you have other installation alternatives here: https://github.com/damianavila/RISE#installation

Then you have nbpresent who lives here: https://github.com/Anaconda-Platform/nbpresent
and this is another slideshow machinery written by Nick Bollweg and it is inspired by RISE but it is a totally different codebase and have other mechanism to interact with the user.

**Comment by willingc** [comment]
Thanks @damianavila. I got it sorted out on the plane flight. Both are cool. 🎉
