### ISSUE TITLE
Calico buttons are gone after installing Rise

### ISSUE THREAD

**Issue by Stef-aap** [damianavila/RISE#217]
hello Damián,

I just installed Rise, looks very nice, but the installation removed my Calico buttons.
These buttons are loaded in ..\.ipython\profile_default\static\custom\custom.js.
So it looks that the custom.js is not executed anymore.
I've restarted everything but that doesn't help.
Any clue how to get Calico working again or how to uninstall Rise ?

thanks,
Stef

**Comment by damianavila** [comment]
We have been discussion in the jupyter mailing list, let continue the discussion there until we get more info. Then we can put the info here for others.

**Comment by damianavila** [comment]
Solved in the mailing list: https://groups.google.com/forum/#!topic/jupyter/o2cJCij842w, closing here.
