### ISSUE TITLE
Newer Reveal.js

### ISSUE THREAD

**Issue by superbobry** [damianavila/RISE#220]
Could you please update the bundled Reveal.js to 3.3.0?

I've tried doing it manually, but apparently this breaks some of the style hacks.

**Comment by damianavila** [comment]
It is in my todo list for the next milestone (along with some other related changes).

**Comment by superbobry** [comment]
I've managed to this in my fork. Would you accept a PR?

**Comment by damianavila** [comment]
>I've managed to get the latest Reveal.js working in my fork. Would you accept a PR?

Of course!

**Comment by damianavila** [comment]
Latest RISE release include latest available Reveal.js (3.5.0). Closing now.
