### ISSUE TITLE
Not compatible with scratchpad extension

### ISSUE THREAD

**Issue by virtuald** [damianavila/RISE#223]
Tested in chrome, with latest versions of juptyer, RISE, etc. 

When displaying a slideshow, the scratchpad button shows up in the right corner, but sadly when it displays it doesn't work. It appears that SHIFT-ENTER is stolen by the slideshow and directed towards the active cell on the slide, instead of at the scratchpad. 

Let me know what other information you need to debug. Might be their bug too (filed at https://github.com/minrk/nbextension-scratchpad/issues/8).

**Comment by damianavila** [comment]
I will take a look... thanks for the report!

**Comment by kurtmckee** [comment]
I recommend closing this ticket as stale.

**Comment by damianavila** [comment]
We never requested specific logs, but this is pretty old by now. Closing it and we will re-open if the original author asks for that.
