### ISSUE TITLE
build issue on python 3.6

### ISSUE THREAD

**Issue by yuyichao** [damianavila/RISE#237]
DISCLAIMER: I'm not really sure what's recommended on python 3.6.

The build script currently fail on python 3.6 with a `C` (fallback) locale because it seems that the default decoder is `ascii` instead of `utf8` in that case and the read of the utf8 encoded README in the build script error because of it. Since the encoding is known to be utf8, does it make sense to read with that encoding directly in the build script?

**Comment by damianavila** [comment]
> DISCLAIMER: I'm not really sure what's recommended on python 3.6.

Not sure as well...

> Since the encoding is known to be utf8, does it make sense to read swith that encoding directly in the build script?

Maybe? Not sure how would be a reliable solution for this issue...

**Comment by kurtmckee** [comment]
I recommend closing this ticket as stale.
