### ISSUE TITLE
conda install on python 3.6

### ISSUE THREAD

**Issue by jankoslavic** [damianavila/RISE#239]
Hi! I use this great package for class presentations. However, I just saw that conda install fails (pip install works) for python 3.6.:

UnsatisfiableError: The following specifications were found to be in conflict:
  - python 3.6*

(I have installed Anaconda 4.3.0)

**Comment by damianavila** [comment]
I need to build the 3.6 packages.

**Comment by choldgraf** [comment]
FYI I'm running into this problem too!

**Comment by bulli92** [comment]
same for me.
Would be nice to have an indication in the README for which python versions it is supposed to work. Couldn't find anything.

Otherwise ... best package ever. Love it!

**Comment by damianavila** [comment]
Hopefully I will have the packages ready by the of next week.

**Comment by rzuritamilla** [comment]
@damianavila: I love RISE
I just tried to install RISE for python 3 (using the latest version of Anaconda) but it fails. 
Have you had time to look into this? Where can we find the packages for Python3?

**Comment by damianavila** [comment]
>Hopefully I will have the packages ready by the of next week.

@rzuritamilla, still need to package it. Probably next week, but I do not want to make promises...

**Comment by Jul13** [comment]
it seems to me that xz is now available on 3.6, could you please try to compile RISE now for conda?

Everybody loves your package, thank you for the work !

**Comment by damianavila** [comment]
I am merging a really big PR (#260) in the next few days and I will release a new version (with py36 support) after that.

**Comment by choldgraf** [comment]
Just wanna chime in with a quick note that RISE is awesome and super useful and @damianavila is a boss for making it better. Thanks!

**Comment by damianavila** [comment]
I have pushed the new release (RISE 5.0.0) with py36 builds in my conda channel: https://anaconda.org/damianavila82/rise/files?version=5.0.0

Sorry for the delay!
