### ISSUE TITLE
Losing selected cell upon return from reveal

### ISSUE THREAD

**Issue by parmentelat** [damianavila/RISE#241]
Hi

Not quite sure if I'm doing everything right but what I can see on my setup currently is:
* I have "start_slideshow_at": "selected"
* having a selected cell, let's say in the middle of my slideshow notebook
* I turn on reveal with alt-r: it starts right where I expect it to
* checking a bit around this position
* then pressing Alt-r again to go back to 'normal' mode

And I always end up at this point at the **beginning** of the notebook, with **no cell outlined as selected** (although at that point `Jupyter.notebook.get_selected_cell()` seems to be set all right)

I would really like to return to the regular notebook mode at the currently selected cell, because I do this back and forth virtually all the time and so going back to beginning of notebook is a substantial impediment in this workflow.

Any hint on how I can hope to achieve this ?

And thanks btw for that tremendous tool :)

**Comment by damianavila** [comment]
> I have "start_slideshow_at": "selected"

Well, if you have that config option, that should do the trick... where are you putting the config? metadata or config file? Can you paste the content of the config file, see here: https://github.com/damianavila/RISE#configure-your-own-options for more details

**Comment by parmentelat** [comment]
@damianavila : I do the configuration through the notebook metadata, where it reads

```
  "livereveal": {
    "start_slideshow_at": "selected",
    "transition": "cube",
    "width": 1280,
    "height": 1024,
    "theme": "simple"
  },
```

Again the issue I have is **not** when the slideshow **starts**, it is when I go back to the regular notebook view/mode for editing. I do see the slide show starting at the selected cell.

BTW: going back and forth between regular notebook and reveal is something that I typically need to do each time the grouping of cells into slides needs to be tweaked; is there any way to do this while remaining under reveal ? would really speed things up for me; it feels like I am missing something obvious here..

**Comment by damianavila** [comment]
> Again the issue I have is not when the slideshow starts, it is when I go back to the regular notebook view/mode for editing.

OK, now I understand better, this issue is already opened and marked as enhancement here: https://github.com/damianavila/RISE/issues/102

**Comment by parmentelat** [comment]
OK indeed, sorry for having missed it in the first place, I am closing this one then
