### ISSUE TITLE
images are not center aligned

### ISSUE THREAD

**Issue by schlichtanders** [damianavila/RISE#245]
when running a slide show including markdown image tags ``![image](path/to/image)``
the image is aligned rather to the left

![images_notcentred](https://cloud.githubusercontent.com/assets/4255480/24210108/63b4e32a-0f28-11e7-8812-89ce2d4bd360.PNG)

If I wrap the image tag into a center tag like ``<center>![image](path/to/image)</center>`` it is centered
![images_centred](https://cloud.githubusercontent.com/assets/4255480/24210258/d6f31f00-0f28-11e7-9e09-a78b7332e71a.PNG)

I admit, it is more intuitive to let images follow the same pattern as text (which always flow left), however my jupyter centres images by default. So it might be at least good to mention this behaviour in the README.md and note that one can easily use ``<center></center>``.

**Comment by schlichtanders** [comment]
I start to really like the feature that the images are not centred by default!

That makes it a bit easier to add custom alignments

**Comment by damianavila** [comment]
> So it might be at least good to mention this behaviour in the README.md and note that one can easily use <center></center>.

I agree, happy to merge a PR with that note :wink:

**Comment by damianavila** [comment]
PR merged, so closing it.

**Comment by taschini** [comment]
Leaving a blank line seems to work on Chrome as well:
```
<center>

![image](path/to/image)
</center>
```

**Comment by DavidNemeskey** [comment]
Ran into this problem now. `<center>` apparently stopped working with `![]()`; so I had to use `<img src>`.

**Comment by chicharl** [comment]
where exactly can I place the code <center>![image](path/to/image)</center> in order to center the images during presentation of the slide deck?

**Comment by Goblin80** [comment]
If you don't like the output of `<center>`, you can use wrap your image/element with a `div` and adjust it's `margin` to your liking.

```
<div style="margin-left: 20%;">
    ...
</div>
``

**Comment by firasm** [comment]
`center` is deprecated in HTML5 so may stop working at any time. 

Here's the html syntax:

```
<img src="images/bus_stop.jpg" width=60% style="margin-left:auto; margin-right:auto">
```

**Comment by tjnd89** [comment]
You can further condense this to 

    <img src="images/bus_stop.jpg" style="margin:auto">

which will make it look good in your notebook but not in an exported HTML. I had to add an additional CSS property

    <img src="images/bus_stop.jpg" style="display:block; margin:auto">

To make it work "everywhere".
