### ISSUE TITLE
RISE doesn't install on Python 3.6 because a dependency on xz 5.0.5 (python 3.5*)

### ISSUE THREAD

**Issue by mbakker7** [damianavila/RISE#250]
Just tried to install on Python 3.6 with conda but get the error message:

UnsatisfiableError: The following specifications were found to be in conflict:
  - python 3.6*
  - rise -> python 3.5* -> xz 5.0.5
Use "conda info <package>" to see the dependencies for each package.

**Comment by khalo-sa** [comment]
I can confirm this issue. Getting the same error when executing "conda install -c damianavila82 rise" on Anaconda 4.3.14 / Python 3.6.1.

**Comment by j3mdamas** [comment]
I also got this:

```
[joao@computer02 ~]$ conda install rise -c damianavila82
Fetching package metadata ...............
Solving package specifications: .


UnsatisfiableError: The following specifications were found to be in conflict:
  - python 3.6*
  - rise -> python 3.5* -> openssl 1.0.1*
  - rise -> python 3.5* -> xz 5.0.5
Use "conda info <package>" to see the dependencies for each package.
```

`pip install RISE` also worked for me. Thanks @khalo-sa

**Comment by damianavila** [comment]
Same issue: https://github.com/damianavila/RISE/issues/239,
Let's just keep one open.
