### ISSUE TITLE
Add package to conda-forge channel

### ISSUE THREAD

**Issue by bladwig1** [damianavila/RISE#253]
This is a really cool package.  It needs to be up on the conda-forge channel.

**Comment by damianavila** [comment]
Currently it is available on my own channel, I will probably put it on conda-forge as well in the future.

**Comment by Juanlu001** [comment]
First attempt: https://github.com/conda-forge/staged-recipes/pull/5098 :)

**Comment by damianavila** [comment]
> First attempt: conda-forge/staged-recipes#5098 :)

Superseded by https://github.com/conda-forge/rise-feedstock.

Packages live in conda-forge (https://anaconda.org/conda-forge/rise/) and my channel (https://anaconda.org/damianavila82/rise) as well.
