### ISSUE TITLE
Selecting first cell of current slide with keyboard shortcut

### ISSUE THREAD

**Issue by caedn** [damianavila/RISE#254]
Is there a recommended way to do that? Currently it's not possible to activate a cell by hitting j/k. This means I have to either click each cell or move over them with shift j/k then deselect them by moving off them and move on them again before I can run/edit them.

I'd like to talk about the code first and then run the cell to discuss the output without using the mouse.

**Comment by damianavila** [comment]
Need to check the behavior, but why you have to move it. Is it too much to ask you to post some gif or video of the behavior you are seeing to fully understand the issue? Thanks!

**Comment by caedn** [comment]
__My goal__: 

Select the first cell on a slide with the keyboard so I can interactively run it during the presentation.

__How I currently have to do it__:

Either click on it with the mouse, or:

- select a cell with the keyboard by moving over it with `shift-j/k` (to get any selection at all)
- (this also selects everything I happen to move over until I hit the right cell)
- deselect everything but one cell by moving with `j/k`
- move back to the target cell with `j/k`
- hit `shift-enter` to run the cell

![select-cell](https://cloud.githubusercontent.com/assets/23618713/25553875/85581222-2cbf-11e7-8957-362e8d472161.gif)

As you can see hitting `j` or `k` without already having something selected does nothing. To get any selection I have to use the "extend selection" shortcuts (`shift-j/k`). The problem is this also selects multiple cells and can move the selection off the slide.

__The problem with this method__:

It's a lot of keystrokes to accomplish something you have to do constantly. It will also move the selection off the slide if you hit `shift-j/k` or `j/k` too often which results in the slide becoming blank.

__How I would like to do it__:

- Hit a key (say `j`) to select the first cell (as if clicking on it)
- hit `shift-enter` to run the cell

**Comment by damianavila** [comment]
Thanks for the detailed description, it helps a lot.

One more question: 

> Hit a key (say j) to select the first cell (as if clicking on it)

Do you want that for every slide (the current slide) or just the first one?

**Comment by caedn** [comment]
No problem, thank you for the great project! 

Every slide would be more useful. the first few slides are usually only markdown anyway.

**Comment by parmentelat** [comment]
I would even advocate that imho it would make sense if the first cell in a slide was selected automatically each time there is a change of slide

I am not sure to fully realize the side-effects of adopting this rule, but for me at least I think user experience would be greatly smoothened

**Comment by damianavila** [comment]
>I would even advocate that imho it would make sense if the first cell in a slide was selected automatically each time there is a change of slide

You mean select the first cell every time the slide change from X to X+1, right? I guess that could be configurable, not sure about making it as the default experience.

**Comment by parmentelat** [comment]
Yes, that is what I mean

I understand this may be deemed intrusive to some users and usages, but I would be very happy to enable this option if it was available

Thinking this over, I could also propose a slightly different approach that would work for me too: it would be to select the first **code** cell in the slide but only if there is one, and so to leave the selection intact when the slide has no code cell.

This way the typical first talk-only slides would go unaffected. Would that be more likely to be adopted as a default strategy ?

**Comment by damianavila** [comment]
> Thinking this over, I could also propose a slightly different approach that would work for me too: it would be to select the first code cell in the slide but only if there is one, and so to leave the selection intact when the slide has no code cell.

That could be an option, I still feel it intrusive but let me think a little bit more...

**Comment by andrzejkrawczyk** [comment]
Hello,

im bumping this up. 

The behavior mentioned in first post for configuration would be great deal.
It helps navigate through slides, so when somebody uses Slides/Subslide + fragments we achieve nice flow of navigation and jumping to next part of presentation, but without selected first cell and being able to execute it forces to use mouse.

I tried the few post above proposition of using shift+j/k but it's working atleast bad and no selecting anything.

Best regards,
Andrzej

**Comment by damianavila** [comment]
@andrzejkrawczyk, there is a PR for this I am reviewing/testing today... this enhancement will be available in the next release.

**Comment by ThomasA** [comment]
I think @parmentelat's proposal of only selecting the first code cell and only if a code cell is present on the slide is the best version. Always selecting the first cell on a slide even if there are only Markdown slides present would seem very disturbing to me if it means that the blue rectangle shows up. IMO that would detract from the visual appearance of text-only slides.

**Comment by parmentelat** [comment]
I've been using this for a while now, and am rather happy with the overall result (this plus the other pending PRs); 
so @damianavila please please let us wrap this up :)

**Comment by damianavila** [comment]
> I think @parmentelat's proposal of only selecting the first code cell and only if a code cell is present on the slide is the best version. Always selecting the first cell on a slide even if there are only Markdown slides present would seem very disturbing to me if it means that the blue rectangle shows up. IMO that would detract from the visual appearance of text-only slides.

We have the two options in the PR @parmentelat landed... btw, I have just merge that one, so closing here.

**Comment by andrzejkrawczyk** [comment]
Hello,

after merging the solution to this issue, how I can update my RISE extension to have the fix? Should I just delete RISE and install it again from documentation instruction or it is done other way?

Best Regards

**Comment by damianavila** [comment]
@andrzejkrawczyk, you can install in developer mode using these instructions:

https://damianavila.github.io/RISE/dev/develop.html

But I would hardly recommend you to wait for the next release (containing this enhancement) planned for this week. Cheers.

**Comment by andrzejkrawczyk** [comment]
@damianavila it work's like charm. Thank you very much! I will use it at my tommorow & thursday python course! Thanks
