### ISSUE TITLE
Auto-launch rise using URL param

### ISSUE THREAD

**Issue by choldgraf** [damianavila/RISE#264]
It'd be useful if you could auto-launch RISE from within a notebook by using a URL parameter of some kind. This would be useful for hosting RISE notebooks from a jupyterhub or Binder. You could give a link like:

`mybinder.org/v2/gh/user/repo/master?rise=true`

and it'd just auto-launch RISE from the the first cell if it were found. WDYT?

**Comment by damianavila** [comment]
Interesting idea. Need to think about the possible implementation, though.

**Comment by choldgraf** [comment]
Here's one implementation @yuvipanda put together for a talk he gave:

http://paws-public.wmflabs.org/paws-public/User:YuviPanda/JupyterHub.ipynb?format=slides

I think that particular solution was tailored to his JHub though.

**Comment by yuvipanda** [comment]
I think the way I would like this to work in rise is for it to check for a
metadata entry or something and auto start itself. That way in binder if
someone just provided a path to a notebook with that metadata entry set
it'll auto launch in rise. Don't think query parameters are the right
solution.

**Comment by choldgraf** [comment]
e.g.:

```
...
'livereveal', {
              'theme': 'sky',
              ...
              'autoload': 'true'
              ...}
```
?

**Comment by damianavila** [comment]
>e.g. in the notebook's metadata file:

In the notebook metadata seems like a good idea to me.

**Comment by damianavila** [comment]
PR was merged: https://github.com/damianavila/RISE/pull/272.
Closing this one.
