### ISSUE TITLE
Compatibility with other jupyter kernels

### ISSUE THREAD

**Issue by methodds** [damianavila/RISE#265]
Hi, 

I just tried using RISE with the [IRkernel](https://github.com/IRkernel/IRkernel) for R. While the button for entering the slideshow exists and works without any issues, the slide type selection for each cell is missing. Thus it is not possible to skip cells, define fragments etc.

Is this something that needs to be worked from the RISE side or the IRkernel side?

**Comment by damianavila** [comment]
The cell toll bar is decoupled from the kernel, so it should work for any kernel, including the R one.
How are you trying to show the cell tool bar options? Did you select from the menu View > CellToolBar > Slideshow?

**Comment by methodds** [comment]
Hey thanks for the hint! View > CellToolBar > Slideshow worked for me, I just had to do it once again for the R notebook. Everything works perfectly :)

**Comment by damianavila** [comment]
Great! Closing here.
