### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by pdonorio** [damianavila/RISE#268]
Hello,
would it be possible to provide anywhere some sort of list of features when a new release come up?

I've seen the new `5.0` and wondering what is new there.
Thank you a lot for your great work,
appreciate any feedback.

**Comment by damianavila** [comment]
I need to put a changelog, I agree... in the mean time, my blog post about the release summarizes (shortly) the changes: http://www.damian.oquanta.info/posts/rise-500-is-out.html

**Comment by pdonorio** [comment]
Thank you! 

Finally Python 3.6 with `conda` :D

**Comment by westurner** [comment]
- This'll generate an RST changelog from the git changelog. (It works great w/ gitflow tagged releases):
  - https://github.com/westurner/dotfiles/blob/develop/scripts/git-changelog.py
- Here's some notes from the Python Misc/NEWS changelog / releaselog discussion (re: towncrier, reno, JSON-LD for requirements traceability)
  - https://github.com/python/core-workflow/issues/6#issuecomment-287561415

**Comment by damianavila** [comment]
Closed by #339
