### ISSUE TITLE
Can't edit cell as slide

### ISSUE THREAD

**Issue by jcrichard** [damianavila/RISE#273]
Hi,

I have a problem on jupyter 6 / python3. I can see the slideshow button but I can't edit each cell to be able to set it as title / subtitle and so one. Do I miss something?

Thank you

**Comment by damianavila** [comment]
The slideshow option in the the view menu right now. From the README:

> In the notebook menu, the "View" option contains a "Cell Toolbar" sub-menu that gives you access to the metadata for each cell. If you select the Slideshow preset, you will see in the right corner of each cell a little box where you can select the cell type (similar as for the static reveal slides with nbconvert).

**Comment by jcrichard** [comment]
ahhh sorry I couldn't figured out. Thank you very much!!!

**Comment by damianavila** [comment]
np, glad you have it working now. Cheers.
