### ISSUE TITLE
how to remap Alt-R (was: Is Escape inactive on purpose in reveal mode ?)

### ISSUE THREAD

**Issue by parmentelat** [damianavila/RISE#290]
I would suggest that we reinstate the Escape keyboard shortcut for getting out of reveal just like Alt-R does already

Any objection to that ?

**Comment by parmentelat** [comment]
ok, so this was silly, Escape of course means get out of edit mode and go back to command mode, so this would ruin it I guess.

I guess I should rephrase this; Using Alt-R to go in and out of reveal is getting hard on my thumb, so I'd like to ease the pain; I don't seem to be able to map getting in and out of reveal to another keystroke in my `custom.js`, am I missing something

Note: I am editing the title for this issue to reflect this

**Comment by damianavila** [comment]
> Escape of course means get out of edit mode and go back to command mode, so this would ruin it I guess.

That's correct.

>  I don't seem to be able to map getting in and out of reveal to another keystroke in my custom.js, am I missing something

`custom.js`? You probably need to modify `main.js` here: https://github.com/damianavila/RISE/blob/master/rise/static/main.js#L630

**Comment by parmentelat** [comment]
No, I really mean `custom.js`, as I would expect RISE users to be able to do that without having to hack `main.js`; at first I thought that `main.js` would expose some global function that could then be bound to a keyboard shortcut using the usual jupyter tools, but I could not find any such function.

from another angle, I take it it is a standard need from a jupyter extension to be able to bind an extension-related function to a hotkey; there seems to be some elaborate means for an extension to expose itself to the configurator (see attached with a random extension); 

I'm not saying we need to go that far, but definitely being able to at least change that single key seems like a reasonable thing to expect, IMHO

![screen shot 2017-09-12 at 14 50 01](https://user-images.githubusercontent.com/4519227/30326867-39fcda1c-97ca-11e7-9908-05529538c4a9.png)

**Comment by damianavila** [comment]
> No, I really mean custom.js, as I would expect RISE users to be able to do that without having to hack main.js; at first I thought that main.js would expose some global function that could then be bound to a keyboard shortcut using the usual jupyter tools, but I could not find any such function.

There is some discussion to support custom js here: https://github.com/damianavila/RISE/issues/95#issuecomment-89747573

> I'm not saying we need to go that far, but definitely being able to at least change that single key seems like a reasonable thing to expect, IMHO

I agree we need to support a better way to handle shortcut customizations.

**Comment by parmentelat** [comment]
as an update on this issue

## solution 1.

I was able to achieve this very simply by exporting a global javascript variable name `RISE` whose actual value is the `revealMode` function;

from there I could simply do this in my `custom.js`

    define(['base/js/namespace',
	    'base/js/events'
           ],
           function(Jupyter, events)  {
	       Jupyter.keyboard_manager.command_shortcuts.add_shortcut('shift-r', {
		   help: 'Enter reveal.js thanks to RISE',
		   handler: RISE,
	       });
    })

So this works for me for now, but...

## solution 2.

It would of course be much nicer if I could refer to contents of the module through `define`; I've tried (without messing with `main.js` at all) something like

    define(['base/js/namespace',
	    'base/js/events',
           'rise/main',
           ],
           function(Jupyter, events, RISE)  {
	       Jupyter.keyboard_manager.command_shortcuts.add_shortcut('shift-r', {
		   help: 'Enter reveal.js thanks to RISE',
		   handler: RISE.revealMode,
	       });
    })

but that won't work, I seem to have either the wrong path for the rise module, or some other synchronization issue..

I'm with solution 1. for now, if that's of iinterest let me know and I'll send a PR

**Comment by damianavila** [comment]
> I'm with solution 1. for now, if that's of iinterest let me know and I'll send a PR

Yep, sure!
Btw, solution 2 is much better IMHO, it should be a problem with the path as you suggested, but I did not try it yet to give you more feedback.

**Comment by parmentelat** [comment]
I'm curious about this line
https://github.com/damianavila/RISE/blob/master/rise/static/main.js#L467
where revealMode gets called with 2 parameters 
I can't figure what they are for, is this just an harmless mistake, or what am I missing ?

**Comment by parmentelat** [comment]
for the record I asked a question about this issue on the jupyter ML
https://groups.google.com/forum/#!topic/jupyter/W3iGCyA_hTg

**Comment by parmentelat** [comment]
regardless of the above, I am finding that we should register Alt-R as a keyboard shortcut using Jupyter's command-mode keyboard manager, instead of the low-level mechanism that we currently have

I've been running that for a while now and could not see any undesirable effect
and on the bright side the shortcut shows up in Help->Keyboard Shortcuts with the rest of them

was there a compelling reason to go this way in the first place ?

**Comment by damianavila** [comment]
> I can't figure what they are for, is this just an harmless mistake, or what am I missing ?

Most probably a leftover from previous implementation.

**Comment by damianavila** [comment]
> for the record I asked a question about this issue on the jupyter ML

Great, thanks!

**Comment by damianavila** [comment]
> was there a compelling reason to go this way in the first place ?

The keyboard shortcut customization feature in the notebook is something recent... and it was not a thing when I implemented the low level machinery.

If we can piggyback in the notebook shortcut machinery, I am +1 on changes in that direction.

**Comment by parmentelat** [comment]
see #291

**Comment by damianavila** [comment]
PR was merged and #304 add some more minor pieces. Closing here.
