### ISSUE TITLE
optimizing Shift-Enter

### ISSUE THREAD

**Issue by parmentelat** [damianavila/RISE#292]
Still trying to minimize the amount of keystrokes .. ;)

I'm finding that we could still improve user experience, in doing so that Shift-Enter moves to the next cell whenever this one is already displayed

I'm currently playing with this idea, and might have a PR soon

at first sight what I'd like to have is (in addition to always evaluating the cell, of course)

* shift-enter on cells that are last on a slide: do nothing, like now
* shift-enter on cells that are last on their fragment: trigger next fragment
* shift-enter on other regular cells: move to next cell

I'm not quite sure yet how accurately I can manage the fragment thing, we'll see

Now I expect this new behaviour could be linked to some sort of configuration, although I'm not sure how much sense it makes to increase the number of settings. 

What do others think about that idea ?

**Comment by damianavila** [comment]
> Now I expect this new behaviour could be linked to some sort of configuration, although I'm not sure how much sense it makes to increase the number of settings.

I am open to increase the number of settings if it is needed.

> shift-enter on cells that are last on a slide: do nothing, like now

It is important to keep this behavior, otherwise execution will trigger the slide change. And it should be independent events. But you are proposing to keep that, so we are OK.

**Comment by damianavila** [comment]
Closed by #295.
