### ISSUE TITLE
coding standards, esp. in `main.js`

### ISSUE THREAD

**Issue by parmentelat** [damianavila/RISE#293]
I'm a little hindered by the code layout, especially in `main.js`
there are places with 2 spaces indent, some with 4, plus the whole body is not indented inside the main `define` call.

I'm not being dogmatic here, but in practical terms I find that I keep having to fight against emacs that wants to align things differently than the rest of the code, and this is becoming a hassle

I'd like to propose a big cleanup in this area, although I understand it's a pain wrt pending PRs, but a bit of planning could maybe make it possible ?

thoughts ?

**Comment by damianavila** [comment]
+ 1 on this... let me first merge some PRs, and maybe a release with the latest changes, and then we can do something like that.
