### ISSUE TITLE
clarifying configuration scheme

### ISSUE THREAD

**Issue by parmentelat** [damianavila/RISE#297]
Is there a place where we thoroughly describe the configuration mechanism ?

At this point I essentially know only about:

1.  adding stuff in the `livereveal` entry in the notebook metadata (as an aside this name should be changed to `rise` or `slideshow` because livereveal is not explicit at all for newcomers)

1. I kind of gathered there somehow is a jupyter-global way to tweak these settings on a per-user basis, although I would not know how to go about doing this actually

1.  and it's my feeling that some users have requested a way to configure stuff at a directory level, or something similar when, I suppose, dealing with a whole project.

is this a reasonable summary or am I missing something here ? 
could someone shed light on option 2. ?
would it make sense to add a section in the readme about all this ?

**Comment by damianavila** [comment]
> as an aside this name should be changed to rise or slideshow because livereveal is not explicit at all for newcomers)

I agree.

> is this a reasonable summary or am I missing something here ?

Yep, that is accurate.

> could someone shed light on option 2. ?

You can see an example here: https://damianavila.github.io/RISE/customize.html#using-python
That piece of python code write stuff on `/home/damian/miniconda3/envs/rise_latest/etc/jupyter/nbconfig`.

Essentially, you can see all the paths where you can put nbconfig files with `jupyter --paths`. In my case:
```
$ jupyter --paths
config:
    /home/damian/.jupyter
    /media/data/miniconda3/etc/jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /home/damian/.local/share/jupyter
    /media/data/miniconda3/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /run/user/1000/jupyter
```

The if you see at the config section, you can actually put nbconfig content on any of them and they will be picked accordingly with some specific hierarchy.

> would it make sense to add a section in the readme about all this ?

We can be more explicit in the docs about this different options.

**Comment by parmentelat** [comment]
this now is referred to from #307, we can close this one IMHO

**Comment by damianavila** [comment]
> we can close this one IMHO

Sure!
