### ISSUE TITLE
cut a release?

### ISSUE THREAD

**Issue by choldgraf** [damianavila/RISE#299]
So that we can implement a REST parameter that auto-launches RISE binder!!! pleeeeeeease :-)

**Comment by damianavila** [comment]
I am working this week into merging some stuff and I expect to cut a release by the next weekend.

Sounds good to you? :wink:

**Comment by choldgraf** [comment]
no problem!

**Comment by parmentelat** [comment]
Hey folks

I'd like to +1 on this :) 

Recently I have ben using pretty heavily the various pending changes, that went out real great, so I'm eager to have other chaps around me using this in some easier way than using my patched version ;)

**Comment by damianavila** [comment]
I did not forget about this... I am traveling right now with a new laptop and without some credentials 😢  so I will be able to to cut a release next Sunday, after coming back home.
I just wanted to let you know :wink:

**Comment by choldgraf** [comment]
no problem! thanks damian :-)

**Comment by choldgraf** [comment]
ahem :-)

**Comment by damianavila** [comment]
We already started to merge PRs.
I will release this week as I mentioned in the Jupyter weekly notes.
Thanks for your patience.

**Comment by damianavila** [comment]
Yes, I know... again, thanks for your patience :wink:

**Comment by damianavila** [comment]
The release is out. Blog post (and a proper changelog) coming (most probably) on Monday. But 5.1.0 is available right now from my conda channel (https://anaconda.org/damianavila82), with builds for the all the platforms and in py27, py35 and py36 flavors. You can also get it from pypi here: https://pypi.python.org/pypi/rise/5.1.0.

Thank you!!

cc @choldgraf @parmentelat

**Comment by damianavila** [comment]
And here is the blog post: http://www.damian.oquanta.info/posts/rise-510-is-out.html

Special thanks to @parmentelat and @choldgraf, as I said in the blog post.

**Comment by choldgraf** [comment]
woot! thanks @damianavila :-)
