### ISSUE TITLE
Slide break for larger cells

### ISSUE THREAD

**Issue by dseverdi** [damianavila/RISE#300]
Hi, I am using RISE for couple of weeks and I really like it. Could you tell me is there any way to break large cells automatically in presentation display? Usually, I can't demonstrate code and output at the same slide, so I have to improvise, but sometimes it it cumbersome. 

Thank you,

Cheers!

**Comment by damianavila** [comment]
Some people use scrolling slides for that purposes. You can activate the scrolling behavior with https://damianavila.github.io/RISE/customize.html#configuration-options and https://damianavila.github.io/RISE/customize.html#enable-a-right-scroll-bar. 

Alternative you can enable the scrolling modifying the notebook metadata as described here: https://damianavila.github.io/RISE/customize.html#using-notebook-metadata and using something like this:

```json
{
    ...
    "livereveal": {
        "scroll": true,
    },
    ...
}
```

Hope that helps with your use case.

**Comment by dseverdi** [comment]
Thank you very much,
it did what you suggested. 

Best regards,
dseverdi
