### ISSUE TITLE
Selecting first cell after moving to new slide / subslide

### ISSUE THREAD

**Issue by andrzejkrawczyk** [damianavila/RISE#302]
Hello,

im making a presentation using RISE, im wondering if there is any key shortcuts to select top cell after moving to cell of type "slide/subslide".

After pressing enter its nicely moving to new slides, but then I have to use mouse to select cell and executes them - it's making a bit more difficult and it would be nice to have only keyboard navigation.

Best Regards,
Andrzej

**Comment by damianavila** [comment]
You will be probably interesting in this issue: https://github.com/damianavila/RISE/issues/254. I think it covers you request, closing this one a dupe. Reopen if you disagree. Thanks.

**Comment by andrzejkrawczyk** [comment]
Hello,

yes #254 it's the same issue.

This can be closed.
