### ISSUE TITLE
make RISE configurable with jupyter_nbextensions_configurator

### ISSUE THREAD

**Issue by parmentelat** [damianavila/RISE#309]
[jupyter_nbextensions_configurator](https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator) would be a great way to let people configure RISE without needing to mess too much with config files and the like

I was precisely talking on that repo earlier today, so I took that chance to ask for guidance, see this thread here where Josh gave a lot of insights
https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator/issues/49

this would mostly involve writing a [yaml config file](https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator/blob/c48a0b579ba82de467e8e4bbb207882d83864637/README.md#yaml-file-format)

an option to consider at least, IMHO

**Comment by damianavila** [comment]
Open to establish interoperability with the configurator.

**Comment by parmentelat** [comment]
capturing 2 examples of interest, from Josh's post, for extension `collapsible_headings`


* [the yaml file](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/blob/5646a5b75467830e7fef739a42d6a7e88ac9f1a5/src/jupyter_contrib_nbextensions/nbextensions/collapsible_headings/collapsible_headings.yaml#L61-L88) 

* [the js code](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/blob/5646a5b75467830e7fef739a42d6a7e88ac9f1a5/src/jupyter_contrib_nbextensions/nbextensions/collapsible_headings/main.js#L882-L890) that activates the keybindings when enabled

which gives this - still for collapsible headings of course

![screen shot 2017-11-04 at 00 14 09](https://user-images.githubusercontent.com/4519227/32399299-2d0de7d4-c0f5-11e7-8dde-111291eac2ac.png)

**Comment by ewankirk** [comment]
This would be a very useful addition since a lot of people use the nbextensions_configurator.  I am trying to move our users from Powerpoint to RISE for technical presentations but asking them to edit json config files is probably too much.

**Comment by parmentelat** [comment]
Just a heads up: I have started to dust this off, and am planning on doing some progress in the near future. I have several comments and questions about that though:

* there is a need to ship 2 additional files with the installation; I have named them `rise.yaml` and `rise.png` in my current working tree, and they are located in `rise/static/` just like `main.js`; they need to be installed in the same directory as `main.js`; how should I go about doing that (for now I am moving forward just just manually created symlinks..)

* second, I am getting a little confused with something called `ConfigSection` and `ConfigWithDefaults`; in some contexts we have a plain javascript object (typically what is passed to `Reveal.configure`), and in some others we have these objects instead, and it is not exactly clear to me why we need both models. Any background information on that would be most welcome

* finally, a comment; it seems to me that the way we configure some settings, i.e. based on names like 'selected' or 'code', is not going to be as self-explanatory as if we were to display good old yes/no tick boxes. Which means that I might be lead to change the code a little so that the config can be done based on such booleans. 

It is too early for me to create a PR, but if there is interest here's a very first, not working step, towards this feature:  
https://github.com/parmentelat/RISE/commits/nbext-conf

in any case, feedback will be most welcome

**Comment by ewankirk** [comment]
Nice.  

 

One thing which would be very useful to have in the config would be the rise “font-scale” css parameter.  It’s currently hard coded at 160% but depending on what sort of definitions you have for things like title pages and fonts in your general jupyter css (and also the target display size) 160% can be too big or too small.  Changing that to a configurable variable would be very useful indeed.

**Comment by parmentelat** [comment]
To be honest I did not know about that particular setting, and I can't seem to spot it in the code either. Or did you mean `font-size` ? 

Once the general framework is in place is should not be too hard to extend the actual scope for the settings that can be configures this way; however, please note that

* the settings made through the configurator are global, they get stored in your $HOME dir and thus apply to all notebooks; as opposed to settings made in the notebook metadata, that only apply to one notebook
* changing css attributes from that sort of (javascript-driven) config pane might not be as obvious as settings that are natively javascript variables; 

Please note that there are several things that you can do already today to change the font-size:

* first and foremost, use your browser's builtin shortcuts - like on the mac `Command +` and `Command -` to interactively augment your font size; I find this very helpful
* you can also create a file named `myslices.css` in the same location as `myslides.ipynb`; that will let you override some css settings only for this notebook
* if the css file is names `rise.css` then it will apply to all the notebooks in the directory.

**Comment by parmentelat** [comment]
@ewankirk : if you could please be so kind as to edit your post to remove the repetition of my own text, it would be great :)

**Comment by ewankirk** [comment]
Done.  Sorry about that :-).

**Comment by parmentelat** [comment]
It's all right, it's just that it was cluttering the page a bit; thank you :)

I'm doing some progress as we speak, so if you have anything to add on the font topic, now would be the time to do so :)

**Comment by ewankirk** [comment]
As you say, you can create specific rise.css or <notebookname>.css files in the same directory but for various annoying and boring reasons involving custom ContentsManagers, that can't be done in our installation of Jupyter(hub).  The two areas where I find myself fiddling with fonts the most are lines 118 and 122 in main.less.  Maybe this shouldn't be a configuration item but sometimes you just want to fiddle around with font sizes so a particular presentation looks good but without the hassle of creating a custom css for the presentation.  But if it's a hassle to add then don't worry.  I have some hacky solutions which work for me.

**Comment by damianavila** [comment]
> One thing which would be very useful to have in the config would be the rise “font-scale” css parameter.

There is an open issue here to track this specific request if you want to continue discussing on the topic: https://github.com/damianavila/RISE/issues/255

**Comment by damianavila** [comment]
PR was merged but the issue never closed. Doing it now.
