### ISSUE TITLE
Packaging problem?

### ISSUE THREAD

**Issue by dhirschfeld** [damianavila/RISE#315]
```
C:\>conda install -c damianavila82 rise --force
Fetching package metadata ...............................
Solving package specifications: .

Package plan for installation in environment C:\Miniconda3\envs\quantdev:

The following NEW packages will be INSTALLED:

    rise: 5.1.0-py36_0 damianavila82

Proceed ([y]/n)? y

ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'damianavila82::rise-5.1.0-py36_0'.
CondaError: Cannot link a source that does not exist. C:\Miniconda3\pkgs\rise-5.1.0-py36_0\Scripts\.rise-post-link-script.py
Attempting to roll back.


CondaError: Cannot link a source that does not exist. C:\Miniconda3\pkgs\rise-5.1.0-py36_0\Scripts\.rise-post-link-script.py
```

**Comment by dhirschfeld** [comment]
Indeed, there is no `.rise-post-link-script.py` file in the `bz2` package:

![image](https://user-images.githubusercontent.com/881019/32523764-7bd7ea2e-c468-11e7-9324-b0524d5ce9ac.png)

**Comment by dhirschfeld** [comment]
***xref:*** conda/conda#4374 - maybe relevant?

**Comment by dhirschfeld** [comment]
Reverting to `conda=4.2.16` allowed the package to install, but the post-install script silently failed thereby requiring a `jupyter nbextension enable --py rise --sys-prefix` to enable it.

**Comment by damianavila** [comment]
Is this affecting only win, right? I can not replicate in osx. I used conda convert to generate the win packages... I will try replicate setting up a win VM and test native packages built in that environment. Thanks for the report.

**Comment by dhirschfeld** [comment]
Yeah, it looks like there are only `.sh` scripts for the post-install which won't work on Windows and there doesn't exist the `.rise-post-link-script.py` version which conda is apparently looking for.

From the linked issues it does seem like it might be related to conda convert.

**Comment by damianavila** [comment]
I have created new packages built on win without `convert`. Can you try it and check if the issue is solved for you? It is in the dev channel...
You should be able to install it with `conda install -c damianavila82/channel/dev rise`

**Comment by damianavila** [comment]
@dhirschfeld ping :wink:

**Comment by karelin** [comment]
Just tried RISE 5.1.0 from dev channel (Win8 x64): installs and works correctly, at least examples with new overlay/header/footer stuff. Awesome!

**Comment by damianavila** [comment]
OK, I have promoted the new built packages into the main channel. Thanks for the report!
