### ISSUE TITLE
The toolbar button is very wide

### ISSUE THREAD

**Issue by xmacex** [damianavila/RISE#319]
The _Enter/Exit Live Reveal Slideshow_ button in the toolbar is very wide.

![screen shot 2017-11-19 at 21 53 18](https://user-images.githubusercontent.com/879300/32995423-19d7e170-cd74-11e7-8670-4266d0d7c69a.png)

Being a button, it already implies a command. Further, the button is never actually used for exiting, only entering the slideshow.

This is a cosmetic (ie. important) issue, and becomes more of a functional issue when the user is installing other extensions which add buttons to the toolbar.

**Comment by xmacex** [comment]
I'm sending a pull request in just a little while.

**Comment by xmacex** [comment]
Oops I just learned that Jupyter Notebook extensions need to be installed with `jupyter-nbextension install rise --py --sys-prefix` (and maybe `jupyter nbextension enable rise --py --sys-prefix` too) after them, e.g. with `pip install --upgrade rise`. So the current button is.

![screen shot 2017-11-19 at 22 07 46](https://user-images.githubusercontent.com/879300/32995560-87588752-cd76-11e7-958c-db056c59e510.png)

**Comment by damianavila** [comment]
As I said int the important I think the icon + RISE word would be enough short and descriptive.

**Comment by damianavila** [comment]
Update: #324 implements the icon + the popup with "Enter/Exit RISE Slideshow".
