### ISSUE TITLE
How about adopting default: auto_select = 'code'

### ISSUE THREAD

**Issue by parmentelat** [damianavila/RISE#321]
it's all in the title

do we have any specific reason to stick with the current default that has auto-select basically turned off ? 

I'm asking because the presentations that I can see on binder generally have not bothered to set this otherwise obscure setting, and I feel like it's a bit of a pity

what do others think ?

**Comment by damianavila** [comment]
I think we could probably make auto_select defaults to true. Let's wait a little bit for others and if we don't have comments, we do it.

Additionally, I think we can discuss about other options that needs to to have other values by default, such as, `start_slideshow_at` (I think the default behavior should be "selected").

Is there any other we want to discuss about?

**Comment by parmentelat** [comment]
+1 for defaulting `start_slideshow_at` to `selected`

**Comment by parmentelat** [comment]
added a line on gitter so people have a chance to discuss this

**Comment by damianavila** [comment]
> added a line on gitter so people have a chance to discuss this

Thanks! Let's wait until the end of the week, and then we proceed with the changes if there is not -1.

**Comment by parmentelat** [comment]
just thinking aloud mostly but, would it make sense to also default autolaunch to true whenever a notebook has the 'livereveal' metadata chunk ?

**Comment by parmentelat** [comment]
to summarize the current proposal:

* `start_slideshow_at` would default to `'selected'` (agreement so far)
* `auto_select` would default to `'code'` (agreement do far)
* `autolaunch` could default to `true` if the notebook metadata has a non-empty `livereveal` chunk  (just proposed)

**Comment by damianavila** [comment]
mmm... I am not sure about autolaunch... I think is too much disruptive. I would be -0.5 on that one...

**Comment by parmentelat** [comment]
fair enough, as I said that was just an idea;
let's forget about that then, maybe some other time

**Comment by damianavila** [comment]
> let's forget about that then, maybe some other time

Maybe, with time, we can evaluate the usage for that option and how spread it is and with that info in mind we can revisit the idea.

**Comment by damianavila** [comment]
OK, I merged the PR, let's close this one now.
