### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by fran6w** [damianavila/RISE#322]
Hello,
I have installed RISE with conda.
I put Slide Type "Slide" on every cell.
The Show Presentation button shows a blank page with only the 4 navigation buttons (first, previous, next, notebook). Either on Chrome or Firefox or IE.
Thanks for your help,
Francis

(map) C:\Test\Anaconda3>conda list rise
 packages in environment at C:\Test\Anaconda3\envs\map:
 rise                      5.1.0                    py36_1    damianavila82

(map) C:\Test\Anaconda3>jupyter nbextension list
Known nbextensions:
  config dir: C:\Users\Francis\.jupyter\nbconfig
    notebook section
      jupyter-js-widgets/extension enabled
      - Validating: ok
  config dir: C:\Test\Anaconda3\envs\map\etc\jupyter\nbconfig
    notebook section
      rise/main enabled
      - Validating: ok
      jupyter-js-widgets/extension enabled
      - Validating: ok

**Comment by fran6w** [comment]
I finally could make it work using
jupyter nbextension enable rise --py --sys-prefix
Sorry

**Comment by damianavila** [comment]
No problem, wondering why it did not work for you since the conda package should take care of the post-script step (enabling). I have tested this successfully in win vm.
