### ISSUE TITLE
Is there a way to center images in a .md cell?

### ISSUE THREAD

**Issue by nateGeorge** [damianavila/RISE#332]
I'm trying to center images I've added in markdown cells with `<img src='image.png' class='output_png'>` and this: https://stackoverflow.com/a/37888447/4549682
```python
from IPython.core.display import HTML
HTML("""
<style>
.output_png {
    display: table-cell;
    text-align: center;
    vertical-align: middle;
}
</style>
""")
```
but it isn't working.  Is there a way to center images in md cells?

**Comment by nateGeorge** [comment]
Whoops, just `<center><img src='blah.png'></center>`

**Comment by fgroupindonesia** [comment]
my image still on left side of the paragraph. any ideas how to center it correctly?

**Comment by damianavila** [comment]
@fgroupindonesia if you have some example with your problem to look at, that will help us to give you better feedback.

**Comment by fgroupindonesia** [comment]
look at [this github (it's mine)](https://github.com/fgroupindonesia/socnetsdkv3). But the image still not centered.

**Comment by damianavila** [comment]
I do not see any ipynb file there, am I missing something?

**Comment by michaelaye** [comment]
So, `<center><img src='blah.png'></center>` works, but https://rise.readthedocs.io/en/maint-5.5/usage.html#other-notes says, we could also use `<center>![noimage](blah.png)</center>` which doesn't work for me in notebook 6.0.0

**Comment by michaelaye** [comment]
See also #498

**Comment by fgroupindonesia** [comment]
> I do not see any ipynb file there, am I missing something?

no i dont use ipynb file... I just use README.md
... the `<center>` tag is not working for my `<img>` element....

**Comment by parmentelat** [comment]
er, I also feel like I am missing something here…
can you please elaborate on why you see a relationship with the RISE project, whose purpose is to run a notebook as a slideshow ?

**Comment by fgroupindonesia** [comment]
> er, I also feel like I am missing something here…
> can you please elaborate on why you see a relationship with the RISE project, whose purpose is to run a notebook as a slideshow ?

ah... i see, i think i wrong bumping into this discussion.
