### ISSUE TITLE
release process

### ISSUE THREAD

**Issue by parmentelat** [damianavila/RISE#334]
Hi Damian - and happy new year ans all this :)

I just reinstalled my python env recently, and realized that one of the last changes that we made about keyboard shortcuts refactoring, and the look of the RISE icon as well, well these changes have been merged in the code but were not released as part of the version available at pypi (which is still my usual method)

So I guess I have 2 questions

* would it make sense to release something in the near future so that these changes become part of the mainstream release
* on a deeper level, should we not improve the release process a little bit ? at the very least we should adopt some rough numbering scheme and set tags, and a changelog would not hurt; so that at least one can see what's expected to be in the public release..

my $0.02 -- Thierry

**Comment by damianavila** [comment]
> Hi Damian - and happy new year ans all this :)

Hey Thierry, happy new year to you as well!

> would it make sense to release something in the near future so that these changes become part of the mainstream release

Makes sense... what about releasing in around 2 weeks?

> at the very least we should adopt some rough numbering scheme 

What you are proposing here? Something like semantic versioning?

> and set tags,

What do you specifically mean with tags?

> and a changelog would not hurt; so that at least one can see what's expected to be in the public release..

I completely agree.

**Comment by parmentelat** [comment]
in practical terms, I was thinking something really lightweight, just a little more than what is in place now. For example, I have this version installed 

```
$ pip3 freeze | grep -i RISE
rise==5.1.0
```
so I would propose that we just

* set tag '5.1.0' on the commit that was used to produce that version,
* and that some sort of `CHANGELOG.md` give a short summary of the new stuff in 5.0.1 as compared with the previously published release

the tag thing clearly is a really easy thing to do  
for the changelog I just found doc/changelog.rst that I had not spotted earlier, but well let's just says that it's not as helpful as I would have expected ;)

**Comment by damianavila** [comment]
> set tag '5.1.0' on the commit that was used to produce that version,

We have a git tag for 5.1.0: https://github.com/damianavila/RISE/releases/tag/5.1.0
Or am I missing something or misinterpreting you?

> and that some sort of CHANGELOG.md give a short summary of the new stuff in 5.0.1 as compared with the previously published release

+10

> for the changelog I just found doc/changelog.rst that I had not spotted earlier, but well let's just says that it's not as helpful as I would have expected ;)

:wink: yep, sorry about that...

**Comment by parmentelat** [comment]
oh, my bad, I failed to see that tag  
actually I was expecting to see it under github, which I didn't - not sure if it's because github doesn't show tags in the commits page or if it was too far below..
I also failed to see it in my local repo using sourcetree as the gui

anyway it is there indeed, so I guess this whole thread boils down to not much, .. except a kind request for a new release when you have chance :)

**Comment by damianavila** [comment]
> except a kind request for a new release when you have chance :)

Yep, planning into releasing what we have in the next two weeks, as I said before (indeed, I planned to make a release last week but I got sick (pharyngitis)... still recovering but much better know).

**Comment by parmentelat** [comment]
Any plan on a next release ? ;)

Thanks -- Thierry

**Comment by damianavila** [comment]
I pushed some docs updates early today. Testing tomorrow. Planning to release on Monday ;-)

**Comment by damianavila** [comment]
@parmentelat 5.2.0 is out, changelog included :wink:
Closing here.
