### ISSUE TITLE
Installed RISE 5.2 & Enter/Exit button disappeared (Windows)

### ISSUE THREAD

**Issue by Ram-N** [damianavila/RISE#341]
I installed RISE 5.2 today. Once I did that, I see that my Enter/Exit button. (It was working fine until I did the update.)

Here are some command outputs that might help.

**nbextension list**
```
$ jupyter-nbextension list
Known nbextensions:
  config dir: C:\Users\Ram\.jupyter\nbconfig
    notebook section
      rise/main enabled
      - Validating: ok
      jupyter-js-widgets/extension disabled
      contrib_nbextensions_help_item/main disabled
    tree section
      nbextensions_configurator/tree_tab/main disabled
  config dir: C:\Users\Ram\Anaconda3\etc\jupyter\nbconfig
    notebook section
      jupyter-js-widgets/extension enabled
      - Validating: ok
      nbextensions_configurator/config_menu/main enabled
      - Validating: problems found:
        - require?  X nbextensions_configurator/config_menu/main
      contrib_nbextensions_help_item/main enabled
      - Validating: ok
      rise/main enabled
      - Validating: ok
    tree section
      nbextensions_configurator/tree_tab/main enabled
      - Validating: problems found:
        - require?  X nbextensions_configurator/tree_tab/main

```

```
$ conda list rise
# packages in environment at C:\Users\Ram\Anaconda3:
#
# Name                    Version                   Build  Channel
rise                      5.2.0                    py36_0    damianavila82
```

**jupyter paths**
```
$ jupyter --paths
config:
    C:\Users\Ram\.jupyter
    C:\Users\Ram\Anaconda3\etc\jupyter
    C:\ProgramData\jupyter
data:
    C:\Users\Ram\AppData\Roaming\jupyter
    C:\Users\Ram\Anaconda3\share\jupyter
    C:\ProgramData\jupyter
runtime:
    C:\Users\Ram\AppData\Roaming\jupyter\runtime

```
**JS Console**
I tried to create a brand new Jupyter notebook. (Python 3 kernel)
In the JS console, I see the following "TypeError"

```
menubar.js:303 actions jupyter-notebook:find-and-replace does not exist, still binding it in case it will be defined later...
MenuBar.bind_events @ menubar.js:303
utils.js:60 load_extensions Arguments(2)
utils.js:37 Loading extension: rise/main
require.js:900 TypeError: Cannot read property 'help' of undefined
    at toolbar.js:101
    at MainToolBar.ToolBar.add_buttons_group (toolbar.js:115)
    at Function.setup [as load_ipython_extension] (main.js?v=20180205211631:953)
    at utils.js:39
    at Object.execCb (require.js:1690)
    at Module.check (require.js:865)
    at Module.<anonymous> (require.js:1140)
    at require.js:131
    at require.js:1190
    at each (require.js:56)
check @ require.js:900
utils.js:37 Loading extension: nbextensions_configurator/config_menu/main
session.js:54 Session: kernel_created (fdeeff65-4f89-4505-ba05-737abf23cec9)
kernel.js:459 Starting WebSockets: ws://localhost:8889/api/kernels/b945f478-f797-418c-8caf-78224915dc8f
kernel.js:103 Kernel: kernel_connected (b945f478-f797-418c-8caf-78224915dc8f)
kernel.js:103 Kernel: kernel_ready (b945f478-f797-418c-8caf-78224915dc8f)
```

Any help appreciated.

**Comment by damianavila** [comment]
Hi!

Some questions:
* notebook version?
* browser version?
* can you try hard-reloading your browser (some info here: https://www.getfilecloud.com/blog/2015/03/tech-tip-how-to-do-hard-refresh-in-browsers/#.Wnmm25M-dhE, to get rid of the cache)?
* can you try installing in a new environment without other extensions to get rid of possible interferences?

Btw, I am not sure the error in the js console is related with RISE. You seem to have a problem with the nbextension_configurator:

```
Validating: problems found:
        - require?  X nbextensions_configurator/config_menu/main
      contrib_nbextensions_help_item/main enabled
```

**Comment by Ram-N** [comment]
**Browser version:**
```
Nearly up to date! Relaunch Google Chrome to finish updating.
Version 63.0.3239.132 (Official Build) (64-bit)

```

**Notebook Version:**
```
The version of the notebook server is 5.0.0 and is running on:
Python 3.6.0 |Anaconda custom (64-bit)| (default, Dec 23 2016, 11:57:41) [MSC v.1900 64 bit (AMD64)]
IPython 5.1.0 -- An enhanced Interactive Python.

```
 I did try the hard-loading and also tried other browsers before raising the issue.

When I created a new `conda env` and installed RISE inside that, the Entry/Exit button showed up. Not sure what is blocking the button in my usual setup. I am going to update my nbextension_configurator next.

**Comment by damianavila** [comment]
> When I created a new conda env and installed RISE inside that, the Entry/Exit button showed up.

Good to know.

> Not sure what is blocking the button in my usual setup. I am going to update my nbextension_configurator next.

It would be nice to identify where is the clashing and against what... thanks for trying all the things I recommended. Will close this one for now because it does not seem a RISE, but feel free to keep commenting or re-open if you think otherwise.

**Comment by Saho12** [comment]
I installed RISE by using pip install RISE. but could not get “Enter/Exit Live Reveal Slideshow” icon.
My RISE is v5.6.1
Jupyter notebook v6.0.0

![Capture](https://user-images.githubusercontent.com/41981828/81454533-dd272300-918c-11ea-9c52-bdd12e88aa54.PNG)

Can somebody please help me.
