### ISSUE TITLE
How will RISE fit in with JupyterLab?

### ISSUE THREAD

**Issue by choldgraf** [damianavila/RISE#346]
Since JupyterLab has a different UI, will this pose a large problem to being able to launch a RISE slideshow directly from the lab? Just curious if there's a long-term plan for this, or if it'll be an obstacle from a coding standpoint

**Comment by damianavila** [comment]
@choldgraf check this: https://github.com/damianavila/RISE/issues/270
Closing here as dupe ;-)

**Comment by choldgraf** [comment]
👍
