### ISSUE TITLE
No such file or directory: rise.css

### ISSUE THREAD

**Issue by andreagrandi** [damianavila/RISE#353]
Hi, first of all thank you so much for this plugin!

I'm using RISE plugin for the first time and I've followed tha installation and usage instructions available here https://damianavila.github.io/RISE/installation.html

The plugin "works", meaning that I can show the slides, the animations work etc... but I see this error in the console where I started `jupyter notebook` from:

```
[I 16:36:37.660 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[I 16:36:48.416 NotebookApp] Kernel started: 862fe712-08c7-41cc-93a0-3cd6834ffe2e
[I 16:36:49.524 NotebookApp] Adapting to protocol v5.1 for kernel 862fe712-08c7-41cc-93a0-3cd6834ffe2e
[W 16:36:51.451 NotebookApp] 404 GET /notebooks/PimaIndiansDiabetes.css (::1): No such file or directory: PimaIndiansDiabetes.css
[W 16:36:51.462 NotebookApp] 404 GET /notebooks/PimaIndiansDiabetes.css (::1) 11.02ms referer=http://localhost:8888/notebooks/PimaIndiansDiabetes.ipynb
[W 16:36:51.463 NotebookApp] 404 GET /notebooks/rise.css (::1): No such file or directory: rise.css
[W 16:36:51.464 NotebookApp] 404 GET /notebooks/rise.css (::1) 1.39ms referer=http://localhost:8888/notebooks/PimaIndiansDiabetes.ipynb
```

I have no idea if the presentation is being rendered as expected or not.... do you know how can I fix that error? p.s: my code is running in a virtualenv and I've installed the required libraries in the same virtualenv.

If you need more information about the versions I'm using:

- Python 3.6.3
- jupyter==1.0.0
- nbconvert==5.3.1
- nbformat==4.4.0
- notebook==5.4.0

Cheers

**Comment by parmentelat** [comment]
Hi
These messages are a side-effect of the ability that you have to inject your own css stuff, either in a file named after your notebook, or on a per-directory basis (latter one being hardwired as rise.css)

You can safely ignore these messages; a more careful implementation would check for the files existence of course.

**Comment by damianavila** [comment]
OK, since @parmentelat answered your question, I will close this one now, @andreagrandi. 
Feel free to keep commenting if you need to.

**Comment by andreagrandi** [comment]
Thanks both for your reply :)
Yes, I agree we can close this issue.

p.s: maybe we (true, I could do a PR for the documentation, just asking if it's a good idea before doing it) could add this explanation to the documentation so other people will avoid asking in the future?

Cheers

**Comment by damianavila** [comment]
> p.s: maybe we (true, I could do a PR for the documentation, just asking if it's a good idea before doing it) could add this explanation to the documentation so other people will avoid asking in the future?

Sounds like a good idea. @parmentelat can you add this info to your docs PR?

**Comment by parmentelat** [comment]
Done

**Comment by damianavila** [comment]
Thanks @parmentelat!
Will try to review that PR today/tomorrow.

**Comment by kunalharia** [comment]
Thank you for this package ! I use it every day ! Did an update of my anaconda in December 2021, and started to experience the 404 GET issue.

@parmentelat - where has this been added in the docs?
