### ISSUE TITLE
Keep ? from popping up keyboard shortcuts?

### ISSUE THREAD

**Issue by lsst-epo-guest-12** [damianavila/RISE#354]
When I am in slideshow mode, if I type `?`, it pops up the Keyboard Shortcuts. Most of the other shortcuts only work in command mode (like `,`) but the `?` key pops up the shortcuts regardless of the mode I am in. This makes it quite hard (when in slideshow mode) to show the help documentation from a code cell (e.g. `float?`).

**Comment by damianavila** [comment]
Thanks for the report. We need to disable the pop up when you are in edit mode, I agree.

**Comment by parmentelat** [comment]
Plus, ? shows up the reveal help, which is not exactly accurate for our users I tend to think; IIRC I did something about that in #355, although it might not be completely right yet
