### ISSUE TITLE
readme in configurator

### ISSUE THREAD

**Issue by parmentelat** [damianavila/RISE#357]
Once the dust from #344 #347 #355 settles, it might make sense to revisit the doc displayed in the configurator, which for now is a dummy placeholder called `configurator.md`, but that could be fruitfully replaced with the main README.

**Comment by parmentelat** [comment]
referring to #377,

when we do the packaging for 5.3.0, we simply need to package the toplevel README.md file together with main.js and main.css and the rest of the static files

in that case it will be enough to 
* replace in `rise.yaml`  the reference to `configurator.md`  with  `README.md`
* and then remove `configurator.md` altogether from the git repo

**Comment by damianavila** [comment]
PR was merged, let's close this one.
