### ISSUE TITLE
Broken in Microsoft Edge

### ISSUE THREAD

**Issue by dobos** [damianavila/RISE#363]
Although this might be a reveal.js issue but slideshow is broken in Edge. I can start the slideshow, it looks different from what it looks like in other browser. When I click on the X icon the notebook comes back but the layout is messed up and cells are enlarged, not correctly centered.

**Comment by damianavila** [comment]
Need to check this out on a Win VM. Thanks for the report.

**Comment by kurtmckee** [comment]
Not able to reproduce on current Microsoft Edge. I recommend closing as stale.
