### ISSUE TITLE
No slide-show button

### ISSUE THREAD

**Issue by Alalalalaki** [damianavila/RISE#365]
Installed rise by conda but no button. I am sure it's not a version problem or reloading problem. 

$ jupyter-nbextension list
Known nbextensions:
  config dir: /Users/xxx/.jupyter/nbconfig
    notebook section
      nbextensions_configurator/config_menu/main  enabled 
      - Validating: problems found:
        - require?  X nbextensions_configurator/config_menu/main
      toc2/main disabled
      latex_envs/latex_envs disabled
      table_beautifier/main disabled
      autosavetime/main disabled
      rise/main  enabled 
      - Validating: problems found:
        - require?  X rise/main
    tree section
      nbextensions_configurator/tree_tab/main  enabled 
      - Validating: problems found:
        - require?  X nbextensions_configurator/tree_tab/main
  config dir: //anaconda/envs/py36/etc/jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
  config dir: /usr/local/etc/jupyter/nbconfig
    notebook section
      contrib_nbextensions_help_item/main  enabled 
      - Validating: OK
      nbextensions_configurator/config_menu/main  enabled 
      - Validating: problems found:
        - require?  X nbextensions_configurator/config_menu/main
    tree section
      nbextensions_configurator/tree_tab/main  enabled 
      - Validating: problems found:
        - require?  X nbextensions_configurator/tree_tab/main

Thanks for any help.

**Comment by damianavila** [comment]
@Alalalalaki, what is your `notebook` version? Can you try upgrading the version of your `notebook` package and see if the problem resolves? Thanks.

**Comment by xylph** [comment]
@Alalalalaki I had the same problem with notebook 5.0.0. Followed @damianavila 's suggestion and updated to 5.4.1. The button appears now.

**Comment by milcent** [comment]
I uninstalled Rise, updated everything (conda update --all) and reinstalled
Rise. It works now.

Em Qua, 25 de abr de 2018 6:41 AM, xylph <notifications@github.com>
escreveu:

**Comment by parmentelat** [comment]
everybody being happy now, I am closing this thread
