### ISSUE TITLE
"button_rise" is not defined

### ISSUE THREAD

**Issue by akloster** [damianavila/RISE#37]
In line 398 of main.js I get the error message "button_rise" is not defined.

https://github.com/damianavila/live_reveal/blob/master/livereveal/main.js#L398

I didn't find a button_rise function anywhere in this code. I may be missing something, otherwise I'd create a pull request with that line removed.

This is a very minor issue, of course...

**Comment by damianavila** [comment]
Probably porting the button_rise from my custom theme to RISE, targeting to 3.x compatibility.
