### ISSUE TITLE
mixup between `note` and `notes` 

### ISSUE THREAD

**Issue by parmentelat** [damianavila/RISE#371]
While testing notebook-5.5 for #367, I came across another issue but in our code this time.

I seem to have mixed up on several occasions between `notes` and `note`;  
as a result there are references to an action named`RISE:toggle-note` which should be `RISE:toggle-notes`.

Trying to bind a keyboard shortcut to that inexisting action of course won't work - even with notebook-5.5

**Comment by damianavila** [comment]
Thanks for the catch! Will look into the PR soon.

Btw, Github did not reply me back about your permissions in the repo. Do you currently have access to the Settings page?

**Comment by parmentelat** [comment]
nope, still no settings tab for me

no big deal though, as far as I am concerned

**Comment by damianavila** [comment]
> nope, still no settings tab for me

Grrr...

> no big deal though, as far as I am concerned

OK.

**Comment by damianavila** [comment]
But, do you have merge permissions?

**Comment by parmentelat** [comment]
> On 1 May 2018, at 16:11, Damian Avila <notifications@github.com> wrote:
> 
> But, do you have merge permissions?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

well I have not had a chance to try yet; but I was able to tweak some issues, so I guess I have some write permissions.

so, when you say ‘looks good to me’ do you expect me to merge stuff directly ?

**Comment by damianavila** [comment]
> so, when you say ‘looks good to me’ do you expect me to merge stuff directly ?

Yep, that's a correct interpretation!
If you have at least one positive review on the PR (and my LGTM accounts for that), feel free to merge it.
