### ISSUE TITLE
How to escape from slideshow mode?

### ISSUE THREAD

**Issue by hrsma2i** [damianavila/RISE#375]
I can't find the close button at the upper left in my slide. How do I escape from my slide?

**Comment by milcent** [comment]
Alt + r

Em Dom, 29 de abr de 2018 5:36 AM, hrsma2i <notifications@github.com>
escreveu:

**Comment by parmentelat** [comment]
This being said, if you can't see the close button it means that something is not working as expected.  
Does the slideshow behave as expected apart from that ?  

If not, and as a general rule, it is recommended to upgrade your environment to the latest jupyter, especially the notebook module that should be at least 5.4.1; you can inspect your current version with this command:

```
$ jupyter notebook --version
5.5.0.dev0
```

**Comment by CermakM** [comment]
Same problem here in `jupyter 5.7` ... the close button is missing and cannot close the slide show.

**Comment by parmentelat** [comment]
Does the keyboard shortcut work or not ?

**Comment by CermakM** [comment]
Well, by default the Alt + r is bound to execute a cell. When I rebind the shortcuts, it does work, but it only opens up the Slideshow. Instead of acting as a toggle, it acts as a switch and opens it up again and again.

**Comment by parmentelat** [comment]
> Well, by default the Alt + r is bound to execute a cell.
> 
How do you mean ? That’s not the classic notebook behavior out of the box, is it ?
> When I rebind the shortcuts,
> 
Out of curiosity, how do you rebind ?
Have you tried binding rise to another shortcut ?
> it does work, but it only opens up the Slideshow. Instead of acting as a toggle, it acts as a switch and opens it up again and again.
> 

Odd indeed; anything looking weird in the browser console ?

Sent from my iPhone

**Comment by CermakM** [comment]
> How do you mean ? That’s not the classic notebook behavior out of the box, is it ?

Nope, it's not.. no idea why it was set to begin with it.

> Out of curiosity, how do you rebind ?

The nbextension editor shortcut rebinding works weirdly, when I try to rebind the shortcut, it doesn't get set, so I used the default Jupyter key bynding editor

> Odd indeed; anything looking weird in the browser console ?

Yep.

```
Uncaught Error: trying to remove a non-existent shortcut
    at ShortcutManager.remove_shortcut (keyboard.js:519)
    at setupKeys (main.js?v=20190704130003:690)
    at Object.revealMode [as handler] (main.js?v=20190704130003:1040)
    at ActionHandler.call (actions.js:992)
    at ShortcutManager.call_handler (keyboard.js:554)
    at ShortcutManager.call_handler (keyboard.js?v=20190704130003:30)
    at KeyboardManager.handle_keydown (keyboardmanager.js:215)
    at HTMLDocument.<anonymous> (keyboardmanager.js:179)
    at HTMLDocument.dispatch (jquery.min.js:2)
    at HTMLDocument.y.handle (jquery.min.js:2)
```

```
Refused to apply style from 'http://localhost:8888/files/scenarios/example/rise.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

```
example.ipynb:1 Refused to apply style from 'http://localhost:8888/files/scenarios/example/example.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

**Comment by CermakM** [comment]
OK, got to the bottom of this ... there is a collision with [jupyter-vim-binding](https://github.com/lambdalisue/jupyter-vim-binding) extension. When I turn it off, everything works as expected.

**Comment by CermakM** [comment]
I also see these log messages before extensions are loaded:

```
Unknown action 'RISE:smart-exec' for shortcut alt - r; it may be defined by an extension which is not yet loaded.
keyboard.js:455 Unknown action 'RISE:smart-exec' for shortcut shift-r; it may be defined by an extension which is not yet loaded.
keyboard.js:455 Unknown action 'RISE:slideshow' for shortcut shift-p; it may be defined by an extension which is not yet loaded.
keyboard.js:455 Unknown action 'RISE:toggle-skip' for shortcut ctrl-0; it may be defined by an extension which is not yet loaded.
keyboard.js:455 Unknown action 'RISE:toggle-slide' for shortcut ctrl-3; it may be defined by an extension which is not yet loaded.
keyboard.js:455 Unknown action 'RISE:toggle-subslide' for shortcut ctrl-4; it may be defined by an extension which is not yet loaded.
keyboard.js:455 Unknown action 'RISE:toggle-fragment' for shortcut ctrl-5; it may be defined by an extension which is not yet loaded.
keyboard.js:455 Unknown action 'RISE:toggle-notes' for shortcut ctrl-6; it may be defined by an extension which is not yet loaded.
keyboard.js:455 Unknown action 'RISE:rise-nbconfigurator' for shortcut 0, shift-p; it may be defined by an extension which is not yet loaded.
load_extensions
...
```

**Comment by parmentelat** [comment]
ah; that's interesting ! I believe you just gave us valuable insight into a painful bug that has been nagging for a while

in `setupKeys`, we mess with some keybindings; specifically the intention is to redirect 'f' that ususally is bound to `jupyter-notebook:find-and-replace`, I assume because `f` is a valuable asset to `reveal.js`; the way this is done right now is wrong, this causes your first stack trace, and effectively ruins reveal initialisation; this will account for all these reports we've had from people who don't see the 2 '?' and 'X' icons

I'll see if I can easily issue a 5.5.n+1 with a patch about that


as to your latest post: these key bindings are not the ones that come with RISE, so I take it it's in your `custom.js` or related ?  in any case it seems like you're trying to establish keybindings too early, i.e. before RISE has been loaded  
please elaborate a little more on how exactly you do these bindings; 
probably an issue better addressed with the notebook community though

**Comment by CermakM** [comment]
Perfect, thanks for the effort!

Regarding the key bindings, I set them up using the native `Edit Keyboard Shortcuts` option in the `Help` sub-menu.

Glad I could be of some help and I am looking forward to see the problem fixed!

**Comment by parmentelat** [comment]
all right, there's a 5.5.1 version out there on pypi for you to try

please let us know if that solves your problem

**Comment by damianavila** [comment]
conda package should be available as well because of this one: https://github.com/conda-forge/rise-feedstock/pull/23.

@parmentelat we should update the docs and add the changes you made in the changelog we publish there.

**Comment by parmentelat** [comment]
I did update the changelog on the maint-5.5 branch; not sure what else to do from there though

**Comment by CermakM** [comment]
Woho, 5.5.1 tried and works! :+1:  Clapping!

Thanks for the quick fix!

**Comment by parmentelat** [comment]
good to hear, I'm closing this then

**Comment by damianavila** [comment]
> I did update the changelog on the maint-5.5 branch; not sure what else to do from there though

I have already redirected the root page to the maint-5.5 branch. Since the changelog was modified after the 5.5.1 tag, that one does not have the changelog modified.
