### ISSUE TITLE
how about we plan for issuing 5.3.0 ?

### ISSUE THREAD

**Issue by parmentelat** [damianavila/RISE#377]
For the record, what I believe is missing for this to happen:
* the packaging of the new files in `rise/static` for nbconfigurator;
* the few pending merge requests
* setting up the webhook between github and readthedocs, that I believe we haven't done yet

**Comment by damianavila** [comment]
I think you detailed the missing pieces. What do you think about May 15th as the release date? That should give us enough time to complete the missing tasks and start with the release procedure.

**Comment by parmentelat** [comment]
> On 1 May 2018, at 16:07, Damian Avila <notifications@github.com> wrote:
> 
> I think you detailed the missing pieces. What do you think about May 15th as the release date? That should give us enough time to complete the missing tasks and start with the release procedure.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

the thing is I do not know what will end up on my plate exactly, but I guess yes, that should be fine

**Comment by damianavila** [comment]
> the thing is I do not know what will end up on my plate exactly, but I guess yes, that should be fine

I can do the release tasks... but I will probably need some help if I found something not working related to the latest changes or with the readthedocs thing... I will ping you if that is the case.

Btw, I said two weeks, because the notebook 5.5 is about to be released in a few days and we depend on that for getting one of the latest fixes, IIRC.

**Comment by parmentelat** [comment]
for the record, I confirm that I can accept merge requests and push directly into your repo - which I just did for testing purposes with a innocuous change to the doc.

**Comment by damianavila** [comment]
> two weeks sounds about right, no big deal if it's a little more, but it feels like we should have this out well before the summer break IMHO

I agree.

> for the record, I confirm that I can accept merge requests and push directly into your repo - which I just did for testing purposes with a innocuous change to the doc.

Great. Thanks for the confirmation.

**Comment by damianavila** [comment]
> is there a good reason for not just using plain setuptools - and dropping distutils altogether ?

This issue will probably give you some historical context: https://github.com/jupyter/nbconvert/pull/352

Given the current state of `setuptools`, I would be inclined to use it with the `disable_bdist_egg` approach Min is mentioning in the issue I referenced above.

**Comment by parmentelat** [comment]
Oops I failed to see this coming, and came up with #379 in the meanwhile

this being said I did browse this other issue rapidly, but after that quick overview I failed to see why we should actually care

What I do retain is that the policy in the jupyter ecosystem has been for some time to resist using setuptools because of the way entry points are now handled - which admittedly is rather disruptive 

but now that - IIUC - setuptools is no longer considered evil, and given that OTOH RISE does not come with entry points, my feeling is that my proposal in #379 makes perfect sense. 

But as I said I'll wait for your green light on this one

**Comment by damianavila** [comment]
Release 5.3.0:

* [x] builds (conda and pip)
* [x] upload (damianvila82 channel and pypi)
* [x] docs (build and deploy)
* [x] test installation (conda, pip, py27, osx and win)
* [ ] blog post and other ANN

Addemdum:

* [] check conda forge PR https://github.com/conda-forge/rise-feedstock/pull/7 (not a blocker for the ANN)

**Comment by parmentelat** [comment]
cool, thanks !

once the announcement is out, I suggest we notify and close the following issues (and possibly others):

#367 #382 #384

**Comment by damianavila** [comment]
> check conda forge PR conda-forge/rise-feedstock#7 (not a blocker for the ANN)

Superseded by https://github.com/conda-forge/rise-feedstock/pull/10 and packages available at conda-forge as well.

**Comment by damianavila** [comment]
> once the announcement is out, I suggest we notify and close the following issues (and possibly others):

Yep, I closed those ones, I will revisit the whole list of issues later to see what other things we should close.

**Comment by damianavila** [comment]
And since this is complete, let's close it as well.
