### ISSUE TITLE
RISE can't work for Docker container, but can work for Bare metal using  same  operation 

### ISSUE THREAD

**Issue by iamyubin** [damianavila/RISE#382]
I install RISE using conda (pip and from source is tried), it works fine for the host machine.
When I install it using the same operations as following in docker container, but the button of RISE can't show in the notebook toolbar, and shortcut also can't work. 
1)  `docker exec -it container-name bash`
2)  `conda install -c damianavila82 rise`

Another question:
Before that, I installed jupyter_nbextensions_configurator, it shows RISE is not compatibility with it in its setup panel.  (the host have the same message in there, although it can open live slideshow.)
![image](https://user-images.githubusercontent.com/4337165/40048277-6a36c1ba-5864-11e8-8336-161a8a24835f.png)

I don't know how to solve it, please help me, thanks.

**Comment by parmentelat** [comment]
Hey there


> I install RISE using conda (pip and from source is tried), it works fine for the host machine.
> When I install it using the same operations as following in docker container, but the button of RISE can't show in the notebook toolbar, and shortcut also can't work.
> 
> 	• docker exec -it container-name bash
> 	• conda install -c damianavila82 rise

most likely you use different versions of the jupyter notebook in both environments
use the following command to probe for you installed version

    $ jupyter notebook --version
    5.5.0.dev0

you need version >= 5.4 for RISE to work fine


> Another question:
> Before that, I installed Jupyter-contrib/jupyter_nbextensions_configurator, and in the panel of nbextensions, it shows RISE is not compatibility with it. (the host have the same message in there, although it can open live slideshow.)

This feature is in version 5.3.x that has not yet been released - see #377 - ping @damianavila :)

**Comment by damianavila** [comment]
> This feature is in version 5.3.x (of RISE) that has not yet been released - see #377 - ping @damianavila :)

Yep, planning to release this week.

**Comment by iamyubin** [comment]
> most likely you use different versions of the jupyter notebook in both environments  

thanks @parmentelat  @damianavila , I fix it when I upgrade my notebook version. 
Look forward the new released version :-)

**Comment by damianavila** [comment]
@iamyubin 5.3.0 has been released.
