### ISSUE TITLE
multicolumn

### ISSUE THREAD

**Issue by gsemet** [damianavila/RISE#385]
Hello

Do you think it is feasible to format a given cell somehow to have 2 or more columns ? Not sure how to do it, maybe using "fragment", such as "column fragment" + css it can work. Having "left column" fragment and "right column" fragment would be ok as well.

Gaetan

**Comment by parmentelat** [comment]
what you can do is to use the regular split-cell notebook extension; 
with that you can already do simple 2-columns layouts, although it is admittedly limited

in any case, this type of functionality IMO clearly falls in an extension of its own, and should not be specific to RISE

**Comment by gsemet** [comment]
This will apply during a slideshow?

**Comment by parmentelat** [comment]
Yes

**Comment by parmentelat** [comment]
It just struck me that the demo readme notebook in binder, accessible here
https://mybinder.org/v2/gh/damianavila/RISE/master?filepath=examples%2FREADME.ipynb
illustrates that feature

of course there may be some setup required to activate the split-cell nbextension

feel free to re-open this issue if needed
