### ISSUE TITLE
setup.py is not installing the files in the manifest

### ISSUE THREAD

**Issue by damianavila** [damianavila/RISE#389]
cc @parmentelat 

I started to create the packages for the release, and I realized that when you are installing with pip (from a local package or the test.pypi index you referenced in #387), several static files are not installed which results in something like this:

<img width="1673" alt="screen shot 2018-05-27 at 4 10 55 pm" src="https://user-images.githubusercontent.com/1640669/40591579-a0b7ce74-61c8-11e8-9909-126f2eafc43d.png">

When I created the package with sdist, the files were there (in the .tar.gz file) because you have them in the MANIFEST but when you try to install it... those files are missing from the installation.

It seems the manifest is not enough... previously we use `package_data={name: paths},` without the need to specify the files in the MANIFEST, but we removed those pieces in the refrenced PR.

Now, I think we have 2 options:

1) revert part of the PR so we are using `package_data={name: paths},` again without specifying the files in the MANIFEST

or

2) use the MANIFEST approach but also the `package_data` one (duplication, maybe prone to errors).

Thoughts?

**Comment by parmentelat** [comment]
I am surprised because as I said in #387 I did a complete test using pip, so as far as I could tell we were all set

You could get this symptom if you forgot to:

    jupyter nbextension install --py rise

because the nbextension is now automatically enabled, but this installation step is still required

If that’s not the problem, can you please be more specific as to the exact commands that you run when you get this symptom ?

**Comment by damianavila** [comment]
Thanks for the hint... I thought I really run the nbextension install command but it does not seem the case... grrr... I should get some sleep and avoid during this test after a 24 hs trip. 

> because the nbextension is now automatically enabled, but this installation step is still required

ipywidgets get rid of this step using datafiles: https://github.com/jupyter-widgets/ipywidgets/pull/521
In the future, we could think about something like this (although it would be more complex because all the files we need to reference...)

OK, as you said, we are all set, I will be publishing the packages in few hours and write a short blog post to be published tomorrow.
