### ISSUE TITLE
Per-Cell toolbar still active when presentation starts

### ISSUE THREAD

**Issue by sonicarg** [damianavila/RISE#39]
There is a slight problem when presentation is shown on screen with any per-cell toolbar active ("Edit metadata", "Raw Cell" or "Slideshow") that makes the toolbar to be drawn when presentation is executed. Doesn't happen on "None" setting.
Here's a screenshot of what looks like:

![image](https://cloud.githubusercontent.com/assets/5818365/4758153/edb221ee-5adc-11e4-87a9-25b244df5163.png)

**Comment by damianavila** [comment]
As I said previously, this is interesting and useful... I will take a stab soon...
