### ISSUE TITLE
version id management

### ISSUE THREAD

**Issue by parmentelat** [damianavila/RISE#393]
the fact that the version id needs to be manually changed in a string of files - 4 if the develop page is right - is quite a pain

in addition, I would argue that this version id should be altered in develop branches; for example now that we just issued 5.3.0, the version id for the master should be something like `5.3.1.devel` or similar, anything that's **not** 5.3.0

adopting such a workflow would mean having to change this version id more often, but having to change it in 4 different locations is both tedious and error-prone

I am unsure what to propose specifically, but wanted to start a discussion on this matter; there might be standard approaches to that ? otherwise I can come up with a `npm run version` utility, or something similar.

**Comment by damianavila** [comment]
> the fact that the version id needs to be manually changed in a string of files - 4 if the develop page is right - is quite a pain

I agree.

> in addition, I would argue that this version id should be altered in develop branches; for example now that we just issued 5.3.0, the version id for the master should be something like 5.3.1.devel or similar, anything that's not 5.3.0

I agree as well.

> adopting such a workflow would mean having to change this version id more often, but having to change it in 4 different locations is both tedious and error-prone

Yep.

> I am unsure what to propose specifically, but wanted to start a discussion on this matter; there might be standard approaches to that ? otherwise I can come up with a npm run version utility, or something similar.

We should look for a unified approach, something like this: https://github.com/msarahan/state-adjacency-graphs/blob/master/conda.recipe/meta.yaml#L20-L23, but also including package.json and docs reference... maybe a script automating all these changes?

**Comment by damianavila** [comment]
Closed by #399, removal of the conda recipe will be done #405.
