### ISSUE TITLE
500 : Internal Server Error

### ISSUE THREAD

**Issue by Christoto7** [damianavila/RISE#396]
Got 500 : Internal Server Error when starting notebook

**Comment by lucasdurand** [comment]
Think this likely isn't a RISE issue, but something happening with the notebook server. 

Does the server launch normally and only give 500 when you open a notebook? Can you elaborate on this some more?

**Comment by Christoto7** [comment]
Yes, only when i open a notebook. I am guessing it's a installation error, I forgot to close  jupyter when I first installed RISE

**Comment by Christoto7** [comment]
fixed by updating anaconda
