### ISSUE TITLE
Displaying the slide show

### ISSUE THREAD

**Issue by Rainz86** [damianavila/RISE#398]
Hi Damianavila,

Great work on RISE! 
My issue is whenever I try to view the slides I've created, the Enter slideshow doesn't open the slides. I think something might be blocking it, could it be a port issue?

Regards,

**Comment by damianavila** [comment]
What is your notebook version?

**Comment by Rainz86** [comment]
Python 3.6.5 and IPython 6.4.0

**Comment by damianavila** [comment]
Are you with conda or pip? I am specifically looking for the `notebook` package version.

`conda list` or `pip list` should be informative...

**Comment by Rainz86** [comment]
@damianavila 
ipython (6.4.0)
ipython-genutils (0.2.0)
notebook (5.5.0)

**Comment by Rainz86** [comment]
additionally,
 ipywidgets-7.2.1 
jupyter-1.0.0 
jupyter-console-5.2.0 
qtconsole-4.3.1 
setuptools-39.2.0 
widgetsnbextension-3.2.1

**Comment by parmentelat** [comment]
What version of RISE is that ?
The latest stable is 5.3; if that's what you're using please post a screenshot, it might help
Have you tried also alt-r as a shortcut to de/activate slideshow mode ?

**Comment by Rainz86** [comment]
hi, I am using the latest RISE version. there is nothing to screen shot as nothing is displayed @parmentelat

**Comment by Rainz86** [comment]
@damianavila when I inspect the page it fails to load; simpl.css, rise.css, presentation.css and main.css (error 404)

**Comment by damianavila** [comment]
How did you install the extension, can you describe the steps?

**Comment by Rainz86** [comment]
First, installed reveal.js then using pip install , I've installed RISE, then installed the JS and CSS

**Comment by damianavila** [comment]
> First, installed reveal.js

You don't need to install Reveal.js, we ship it with our package

> then using pip install , I've installed RISE, then installed the JS and CSS

So, you did:
```
pip install RISE
```
and
``` 
jupyter-nbextension install rise --py --sys-prefix
```

Right?

What is the output of `jupyter nbextension list`?

**Comment by Rainz86** [comment]
Hi Damian,

Any solutions to the above?

Regards,

**Comment by parmentelat** [comment]
I do not think we are going to be able to be very helpful with only the fuzzy information that we have so far; we'd need you to elaborate on sentences like:

> First, installed reveal.js then using pip install , I've installed RISE, then installed the JS and CSS

what are the actual commands used to do that ? what is the exact version of rise ? is this jupyterlab or classic notebook (which would show on a screenshot mind you)

Please help us help you :)

**Comment by Rainz86** [comment]
So, I've deleted everything related to rise (so please ignore the above mentioned steps) and installed it in the following steps:
1) Installed RISE using the conda command i.e. conda install ....
2) However, I couldn't see the enter RISE button so installed the RISE package separately using Pycharm 
2) Opened Jupyternotebook on browser. Saw the enter RISE button clicked it but nothing happened. Please find the attached screenshot
[screenshot.docx](https://github.com/damianavila/RISE/files/2175821/screenshot.docx)

**Comment by parmentelat** [comment]
mhm; I don't know about installing through pycharm; I take it this would be a convenience layer on top of pip ?
in any case what you describe is weird; as per the installation instructions installing through conda should do the trick, while installing through pip requires the additional step of enabling the nbextension

what's the url on top of your screenshot ? can you please also send the javascript console (as a native png or jpeg as far as possible ?)

**Comment by Rainz86** [comment]
the url isL http://127.0.0.1:8888. the javascript console is attached. it gives bunch of css errors
![javascript console](https://user-images.githubusercontent.com/32161513/42451367-ed1320f2-837e-11e8-82b1-f203160ded58.jpg)

**Comment by parmentelat** [comment]
the missing css files are a red herring, never mind that

to be clear here is what I have when looking at the README notebook/slideshow in examples/ before and after I enter the slideshow; your url looks definitely odd

how do you start you jupyter notebook ?

![screen shot 2018-07-09 at 14 57 50](https://user-images.githubusercontent.com/4519227/42452110-6eefa320-8389-11e8-922e-5a43e2769630.png)
![screen shot 2018-07-09 at 14 57 55](https://user-images.githubusercontent.com/4519227/42452133-7fc782ee-8389-11e8-91f9-bafc1960846d.png)

**Comment by Rainz86** [comment]
I start the notebook from Pycharm i.e. I open Pycharm select jupyter notebook and then run it and use the html provided in Pycharm

**Comment by parmentelat** [comment]
> On 9 Jul 2018, at 15:13, Rainz86 <notifications@github.com> wrote:
> 
> I start the notebook from Pycharm i.e. I open Pycharm select jupyter notebook and then run it and use the html provided in Pycharm
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


can you please try and use raw `jupyter notebook` so that we can pinpoint the culprit here ?

**Comment by parmentelat** [comment]
I don't use pycharm myself; has anybody experience with using RISE from within pycharm ? could this be the reason for the issue experienced by @Rainz86 ?

**Comment by Rainz86** [comment]
I opened a raw jupyter notebook using anaconda prompt window. It opened http://localhost:8889/notebooks/Untitled.ipynb. However, now there isn't a open RISE button.
btw @parmentelat  you've been a great help much appreciate taking your time to help me.

**Comment by Rainz86** [comment]
@parmentelat I've managed to make it work! What I did was find the git folder I cloned and opened jupyter notebook there!

**Comment by damianavila** [comment]
>What I did was find the git folder I cloned and opened jupyter notebook there!

Which repo did you clone? I am not sure how you fixed the issue from your description.
