### ISSUE TITLE
RISE from conda not compatible with Python 3.7

### ISSUE THREAD

**Issue by datapythonista** [damianavila/RISE#406]
Not sure if it's just that Python 3.7 conda packages need to be built, or there is some more work to do. But seems like RISE 5.3.0 won't install in conda if Python 3.7 is used.

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - python=3.7
  - rise -> python[version='>=3.6,<3.7.0a0']
```

**Comment by damianavila** [comment]
> Not sure if it's just that Python 3.7 conda packages need to be built

Pretty sure that is the case.

**Comment by damianavila** [comment]
PR solving this lives here: https://github.com/conda-forge/rise-feedstock/pull/18.

Closing.
