### ISSUE TITLE
Issue install pandas-datareader

### ISSUE THREAD

**Issue by tkj80** [damianavila/RISE#407]
Hi,

I ran the following to install pandas-datareader

C:\Program Files\Anaconda3>conda install -c anaconda pandas-datareader

however, I got the following error message:
Could not connect to https://conda.anaconda.org/anaconda/win-32/conda-env-2.6.0-h36134e3_1tar.bz2

**Comment by damianavila** [comment]
And how this issue is tied to RISE?

**Comment by tkj80** [comment]
sorry, this is the first time I posted. It is on the wrong page.
