### ISSUE TITLE
RISE not working

### ISSUE THREAD

**Issue by Scienyu** [damianavila/RISE#420]
I use conda and pip install RISE but it just show a RISE button and no slide

**Comment by damianavila** [comment]
Did you check the usage section? https://rise.readthedocs.io/en/stable/usage.html

**Comment by Scienyu** [comment]
I am sorry that the reply is late. I am not in the company on weekends. I uninstalled RISE and used pip install again. This time I succeeded. But on the upper left corner has a ‘Exit RISE’ label and lower left Corner has a Reveal Shortcuts help and how to remove that two labels? thanks

**Comment by damianavila** [comment]
> But on the upper left corner has a ‘Exit RISE’ label and lower left Corner has a Reveal Shortcuts help and how to remove that two labels? thanks

Pressing `,` will toggle help and exit buttons

**Comment by Scienyu** [comment]
thank you very much, RISE really help me a lot!

**Comment by Scienyu** [comment]
sorry for another question, how to change the theme back to original white?

**Comment by damianavila** [comment]
> sorry for another question, how to change the theme back to original white?

https://rise.readthedocs.io/en/docs_hot_fixes/customize.html#choosing-a-theme, choose the `simple` theme to use the original white.

**Comment by jrglez** [comment]
Hello, I am having a similar problem. I installed raise using conda, but I cannot start the presentation.  The button is not showing and alt+r does nothing.
If I try to install rise again, it says it's already installed.
I am using notebooks 5.7.0 and rise installed using 'conda insatall -c damianavila82 rise'. The JS console says:


`main.min.js:46944 actions jupyter-notebook:find-and-replace does not exist, still binding it in case it will be defined later...
MenuBar.bind_events @ main.min.js:46944
main.min.js:24085 load_extensions Arguments(1)
main.min.js:47851 Loaded moment locale en
main.min.js:38179 Session: kernel_created (b140d964-9dfa-47e5-bf44-e633647fd641)
main.min.js:37335 Starting WebSockets: ws://localhost:8888/api/kernels/385d41ef-6374-47a3-b7cd-e1c9311ef059
main.min.js:24062 Loading extension: jupyter-js-widgets/extension
04_programming_with_python.ipynb:1 Access to Font at 'about:blank' from origin 'http://localhost:8888' has been blocked by CORS policy: Invalid response. Origin 'http://localhost:8888' is therefore not allowed access.
main.min.js:36979 Kernel: kernel_connected (385d41ef-6374-47a3-b7cd-e1c9311ef059)
main.min.js:36979 Kernel: kernel_ready (385d41ef-6374-47a3-b7cd-e1c9311ef059)`

Thanks

**Comment by Krulvis** [comment]
Hey I'm having the same issue as Scienyu mentioned a couple months back. However, simply restarting did not do the trick for me...
Jupyter version: 4.4.0
Python versoin: 3.5
RISE version: 5.4.1

This is what it looks like
![image](https://user-images.githubusercontent.com/21366036/56810318-43692e00-6836-11e9-8341-8ad21cc0bc4a.png)

**Comment by damianavila** [comment]
Notebook version?
Do you have anything in the browser console?
How did you install rise 5.4.1?

**Comment by Krulvis** [comment]
I installed it through pip: pip install rise
Notebook versoin: 5.7.4
There are some errors in the browser console:
![consoleLog](https://user-images.githubusercontent.com/21366036/56818312-a8794f80-6847-11e9-8d60-b8fa0e8f4beb.png)

**Comment by damianavila** [comment]
After installing with pip... did you run:

`jupyter-nbextension install rise --py --sys-prefix`

**Comment by Krulvis** [comment]
No, just ran and tried again. It did the trick :) Why is this not on the git readme? I never knew you had to also install plugins separately on jupyter-nbextension

**Comment by damianavila** [comment]
> Why is this not on the git readme?

Because the README is tracking master, and starting the next release (happening soon) that step will not longer be needed.

I would recommend to always check the stable docs: https://rise.readthedocs.io/, in the installation page it explicitly states this jupyter-nbextension step.

**Comment by Saho12** [comment]
I installed RISE 5.6.1 through pip install RISE. but still i cant find the 'Enter/Exit Live Reveal Slideshow' icon and shortcut of Alt-r not working.
My jupyter notebook 6.0.0 and i use IE. CAn anybody help me in this regard.

**Comment by parmentelat** [comment]
hi

can you post a screenshot of your javascript console with jupyter classic opened on your notebook ?

**Comment by Saho12** [comment]
> hi
> 
> can you post a screenshot of your javascript console with jupyter classic opened on your notebook ?

![rise5](https://user-images.githubusercontent.com/41981828/81475576-68e09400-920d-11ea-88f2-734c3aec3f61.PNG)

**Comment by Saho12** [comment]
> > hi
> > can you post a screenshot of your javascript console with jupyter classic opened on your notebook ?
> 
> ![rise5](https://user-images.githubusercontent.com/41981828/81475576-68e09400-920d-11ea-88f2-734c3aec3f61.PNG)

![rise6](https://user-images.githubusercontent.com/41981828/81475671-f91ed900-920d-11ea-899b-4c33ff44c8a8.PNG)

Hope this is the screenshot you are asking. else let me know.

**Comment by parmentelat** [comment]
hi again  
it is a little surprising that you **do not get any message** at all !  
I just checked again and with my setup, even though I get no error message indeed, I get 30 info messages..  
so, what browser is that exactly ? 
would you have a chance to use chrome and redo the same ? 

FYI here's what I get when opening the demo slideshow notebook from the rise repo
as you can see, when selecting all messages I get a line confirming that extension `rise/main` is being loaded

I suspect there is something wrong in your overall jupyter setup; have you several environments installed (virtualenvs or minicondas I mean) ? 


![image](https://user-images.githubusercontent.com/4519227/81476028-e1485480-920f-11ea-847a-dd9f46c63677.png)

**Comment by Saho12** [comment]
> hi again
> it is a little surprising that you **do not get any message** at all !
> I just checked again and with my setup, even though I get no error message indeed, I get 30 info messages..
> so, what browser is that exactly ?
> would you have a chance to use chrome and redo the same ?
> 
> FYI here's what I get when opening the demo slideshow notebook from the rise repo
> as you can see, when selecting all messages I get a line confirming that extension `rise/main` is being loaded
> 
> I suspect there is something wrong in your overall jupyter setup; have you several environments installed (virtualenvs or minicondas I mean) ?
> 
> ![image](https://user-images.githubusercontent.com/4519227/81476028-e1485480-920f-11ea-847a-dd9f46c63677.png)

I tried in chrome , and it is working . Thanks a lot. But not sure why it is giving issue in internet explorer

**Comment by parmentelat** [comment]
sorry about that; I don't think any of us is in a position to test with IE - let alone support it

can you report about using edge ? does that work ?

**Comment by damianavila** [comment]
@Saho12 if you can report about edge, that would be helpful!

Additionally, next time, it would be more effective to reach us if you just open one report/ticket. I saw a lot of new comments spread on several tickets about this same issues and it was difficult for me to prioritize them properly.

Thanks @parmentelat for providing @Saho12 with your feedback.

**Comment by Saho12** [comment]
Sorry damianavila , for raising request from all possible forums. what is
the edge, sorry i am new.
Thanks and Regards
Prasannajit Sahoo

**Comment by kurtmckee** [comment]
@Saho12 "Edge" refers to Microsoft Edge, which is a browser from Microsoft based on Chrome. It is Internet Explorer's replacement.

@damianavila I recommend closing this ticket. The original issue has been resolved.

**Comment by parmentelat** [comment]
@kurtmckee thanks for the heads up, closing
