### ISSUE TITLE
Markdown table rendering

### ISSUE THREAD

**Issue by kakila** [damianavila/RISE#425]
For some reason tables are rendered very small, I can zoom into them to see the content, of course, this makes other parts of the slide not visible.
Is there a way to increase the overall size (respect to headers, text, etc...) of rendered tables?

Seems related to #175 and #255

**Comment by eitanlees** [comment]
From the links you have posted I found that including a cell at the top of the notebook with 

```python 
%%HTML
<style>
.rendered_html table, .rendered_html th, .rendered_html tr, .rendered_html td {
     font-size: 100%;
}
</style>
```

seemed to fix table output.

**Comment by damianavila** [comment]
Thanks for the info, we can probably add this piece to the rise.css...

**Comment by kakila** [comment]
Thanks @eitanlees, but I am running IJulia. I guess that's a solution for python
In julia I get
```
UndefVarError: Markdown not defined

Stacktrace:
 [1] generic_magic_help(::SubString{String}, ::SubString{String}) at /home/juanpi/.julia/packages/IJulia/k5o7j/src/magics.jl:33
 [2] magics_help(::String) at /home/juanpi/.julia/packages/IJulia/k5o7j/src/magics.jl:22
 [3] execute_request(::ZMQ.Socket, ::IJulia.Msg) at /home/juanpi/.julia/packages/IJulia/k5o7j/src/execute_request.jl:165
 [4] #invokelatest#1 at ./essentials.jl:686 [inlined]
 [5] invokelatest at ./essentials.jl:685 [inlined]
 [6] eventloop(::ZMQ.Socket) at /home/juanpi/.julia/packages/IJulia/k5o7j/src/eventloop.jl:8
 [7] (::getfield(IJulia, Symbol("##12#15")))() at ./task.jl:259
```

**Comment by Flancis** [comment]
@kakila Would changing `%%HTML` to `%%html` work as suggested below?
https://github.com/damianavila/RISE/issues/255#issuecomment-323169667

**Comment by Roger-luo** [comment]
@kakila In IJulia you can use

```julia
HTML("""
<style>
.rendered_html table, .rendered_html th, .rendered_html tr, .rendered_html td {
     font-size: 100%;
}
</style>
""")
```

**Comment by chrish42** [comment]
I had a presentation with many Pandas dataframes displayed, and they were all coming out smaller than the text. The solution from @eitanlees above fixed my problem. Thank you!

Is this something that needs to be changed in Pandas, or in RISE? If the former, I could do a pull request if I had a bit better of an idea of what needs to be changed... If the latter, this is a problem that pretty much anyone building RISE presentations for notebooks that use Pandas will encounter.

**Comment by damianavila** [comment]
> Is this something that needs to be changed in Pandas, or in RISE?

IMHO, we should fix it on RISE, it is just a matter to include that css in the main.less (https://github.com/damianavila/RISE/blob/master/src/less/main.less) and check that we are not breaking other table-related stuff.

Happy to review a PR if you want to make a try!
