### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by NBwr** [damianavila/RISE#437]
Can settings be equally well customized in the Notebook metadata as well as in the JSON file (using python script)? 

I've tried both and to my surprise some commands only seem to work in the metadata. For instance, `"transition": "zoom"` works in both cases. 
While the commands `"header": "Header"` and `"footer": "Footer"` only seem to work in the Notebook metadata. 
Is it supposed to be that way? Am I doing a mistake?

**Comment by damianavila** [comment]
Can you post the notebook you are using? And the python script you are using to customize as well?

**Comment by kurtmckee** [comment]
I recommend closing this ticket as stale.
