### ISSUE TITLE
pip install rise should "just work"

### ISSUE THREAD

**Issue by jdemeyer** [damianavila/RISE#440]
Is there any particular reason why extra steps are needed after `pip install rise` to get it actually working? Ideally, one shouldn't need to run `jupyter-nbextension install rise`.

**Comment by jdemeyer** [comment]
This is more or less a duplicate of #389 but that was closed without resolution.

**Comment by damianavila** [comment]
In the last comment there some hints about this: https://github.com/damianavila/RISE/issues/389#issuecomment-392420887

Essentially, it is doable, but it is not a top priority thing right now... although PRs on this matter are more than welcome.

**Comment by jdemeyer** [comment]
> although PRs on this matter are more than welcome.

Great! That answers my question.

**Comment by damianavila** [comment]
Let's reopen the issue until I merge the PR.
