### ISSUE TITLE
Print to PDF doesn't show custom overlay (header)

### ISSUE THREAD

**Issue by mmuzzi** [damianavila/RISE#441]
I have followed the instructions at https://rise.readthedocs.io/en/docs_hot_fixes/customize.html#decorating-all-slides to add an image in the header of my slides. However, when trying to print the presentation to PDF using `nbconvert` (as detailed [here](https://rise.readthedocs.io/en/docs_hot_fixes/exportpdf.html#using-nbconvert)) the image doesn't show.

It seems from #151 that setting a theme also doesn't work when printing to pdf (although in that case it seems `nbconvert` wasn't involved).

Does anyone have any idea on how to fix this?

**Comment by parmentelat** [comment]
All the styling done through css goes to reveal and the browser, but the notebook data structure itself is not impacted, it has no specific knowledge of that, so it's not surprise that `nbconvert` ignores it.  
Getting this right is likely to require quite some changes, so I would not count on these features in the near future, unfortunately

**Comment by damianavila** [comment]
> Getting this right is likely to require quite some changes, so I would not count on these features in the near future, unfortunately

I would suggest using decktape: https://rise.readthedocs.io/en/docs_hot_fixes/exportpdf.html#using-decktape, in that way you will be generating exactly what the browser see...

**Comment by mmuzzi** [comment]
I appreciate the answers. I'll try to use `decktape`, although it was not working on Windows (but that is a different issue).

Thanks for the help. I think this issue can be closed.

**Comment by gforsyth** [comment]
I haven't identified the _cause_ of this, so I'm not sure what to offer as a "proper" fix for this, _but_:

When you run `jupyter nbconvert --to slides mypresentation.ipynb` the custom `css` from a `rise.css` makes it in to the `html` output, but there is also a default `@media print` section that gets added that does _not_ respect the custom css.

If you delete the entire `@media` section from the `html` file, then the browser you are using will fall back on to the custom css for use with print-to-pdf.

You want to find this in your output `html` and delete everything that the `print` directive encompasses (it's around 70 lines):

```
/*! Source: https://github.com/h5bp/html5-boilerplate/blob/master/src/css/main.css */
@media print {
*,
*:before,
*:after {
background: transparent !important;
box-shadow: none !important;
text-shadow: none !important;
}
...
```

then when you add the `?print-pdf` it will show up with the theme.

**Comment by damianavila** [comment]
Mmm... I thought that was already fixed on nbconvert at some time in the past (the @media stuff)... wondering which nbconvert version were you using @gforsyth?

**Comment by gforsyth** [comment]
> which nbconvert version were you using

Unfortunately I can't check as it was on a corporate laptop I've just had to swap out.  But my attempt to reproduce the error on a new machine has failed, so yeah, out-of-date `nbconvert` could definitely have been the culprit.

Sorry for the noise!
