### ISSUE TITLE
Unable to Remove rise (using conda remove)

### ISSUE THREAD

**Issue by konchada2** [damianavila/RISE#443]
I have manually deleted the rise package from site-packages under anaconda3 but still unable to remove it from environment. Kindly help in clearing the issue. 

![image](https://user-images.githubusercontent.com/26350788/52542758-121dad80-2d71-11e9-8003-ed153e0b40fa.png)

**Comment by damianavila** [comment]
@konchada2 can you please post more info about your case, such as OS, jupyter notebook and RISE versions, conda version, anaconda version. Thanks!

**Comment by kurtmckee** [comment]
I recommend closing this ticket as stale.
