### ISSUE TITLE
Update docs about nbconvert release for PDF export

### ISSUE THREAD

**Issue by TomDonoghue** [damianavila/RISE#445]
In the docs, there is a note about a work-around that one has to do to do PDF-export and work around an issue with the (at the time) current version of nbconvert. It seems that nbconvert has since made a new release, so I think this note in the docs could be updated to say that one should use the latest version of nbconvert (but if so, does not need to do any workarounds). 

I can make a quick PR to update this section if wanted - I just didn't want to jump straight into it incase I'm missing something here!

**Comment by lucasdurand** [comment]
That's great news!

**Comment by damianavila** [comment]
>I can make a quick PR to update this section if wanted - I just didn't want to jump straight into it incase I'm missing something here!

Sure, waiting for your PR!

**Comment by damianavila** [comment]
PR merged, closing this one.
