### ISSUE TITLE
add tablet support for full screen chalkboard and slide-local drawing

### ISSUE THREAD

**Issue by miwojc** [damianavila/RISE#447]
would be great to add tablet support for full screen chalkboard and slide-local drawing
i tried to use wacom pen tablet but it didn't work as expected. normally you could draw just drawing on tablet but here i had to press "right" button on my tablet pen.
thank you!

**Comment by parmentelat** [comment]
here again this would probably be more fruitfully discussed directly on the chalkboard-as-a-reveal-extension issues blog

https://github.com/rajgoel/reveal.js-plugins/issues
