### ISSUE TITLE
keep marker position in relation to displayed text in slide-local canvas mode

### ISSUE THREAD

**Issue by miwojc** [damianavila/RISE#448]
here's the example of what i mean.
i highlighted words 'Turn' and 'slideshows' in current view. But when i resize browser window then the highlights does't match the previously highlighted words. I wonder if it's possible to keep the highlights when resizing the browser viewport.

thanks!
![image](https://user-images.githubusercontent.com/32404415/54494693-5acf0600-48dd-11e9-8e0c-8abb00f8ad7a.png)
![image](https://user-images.githubusercontent.com/32404415/54494709-7b975b80-48dd-11e9-8c06-706c45f39825.png)

**Comment by parmentelat** [comment]
Hello there

IMHO this is something that should go to the chalkboard extension for reveal.js, as RISE does not interfere in this matter, so please redirect this issue accordingly:

https://github.com/rajgoel/reveal.js-plugins/issues
