### ISSUE TITLE
UP/Down keyboard arrow-key not working for Notebook on Windows

### ISSUE THREAD

**Issue by umar07** [damianavila/RISE#455]
I am able to move left-right to the next slide, but not able to move up down for subsidies using the Keyboard's arrow keys. Using the mouse to click on the up/down button on the slides works as expected.
The slideshow acknowledges the presences of sub-slide corrects but not it is getting executed via keyboard's up/down arrow keys.
When I am using the HTML presentation generated directly from nbconvert command the arrow-keys work as expected.

**Comment by parmentelat** [comment]
Hey there

in RISE the up and down arrow are for moving between cells - it's a notebook after all :)

the recommended way to move within your slides, subslides and fragments, is to use `Space` to move forward, and `Shift-Space` to move backward, and this will just *do the right thing*, i.e. move up or left as appropriate :)

let us know if we can close this issue

**Comment by umar07** [comment]
@parmentelat Thanks for the clarification, yes it is working as expected using `space` and `shift+sapce`.
