### ISSUE TITLE
notes section in speaker view

### ISSUE THREAD

**Issue by m-sperlich** [damianavila/RISE#456]
when in speaker view, the notes section does not only display the notes text but also includes a drop down menu for "slide type" and the raw notes text above the formatted text at the end.

**Comment by parmentelat** [comment]
hello there

I am not sure that I understand your point here
Is this something that does not work as expected, or that could use a better documentation ?

Thank you if you can elaborate a little :)

**Comment by m-sperlich** [comment]
hi,
thanks for your quick answer and sorry for being too brief. i would expect the notes section to only display the text written in the notes cell. The drop down menu does not seem to affect the cell and both the drop down menu aswell as the repetition of the text take a lot of space. i've attached a screenshot to illustrate my problem. In the bottom right NOTES section i would like only the text "This is a note" to appear once and without the slide type drop down. i'm sorry if i am missing anything here. thanks a lot for your help!
![screenshot](https://user-images.githubusercontent.com/30048132/55462744-bdbbdf00-55f7-11e9-8002-e1b955482e9b.PNG)

**Comment by damianavila** [comment]
Thanks for the report! We definitely need to upgrade the template rendering the notes so we avoid the text duplication.

**Comment by m-sperlich** [comment]
Great! Thanks you! RISE is awesome!

**Comment by damianavila** [comment]
Closed by #460.
