### ISSUE TITLE
CCS styling is not removed when we get into the notebook view

### ISSUE THREAD

**Issue by damianavila** [damianavila/RISE#462]
Here: https://github.com/damianavila/RISE/blob/master/rise/static/main.js#L496-L502

We are allowing to inject css stuff, and that css is applied when we enter the slideshow view, but when we go back to the notebook view, that css is still applied which could, in turn, make the notebook view look very weird depending on the css changes you introduced.
This can be actually checked with the current example/README.ipynb

cc @parmentelat, I am pretty sure you will be interested in this since you modified the example recently.

We could probably `disable` the `link` when we go out from the slide view.
Not a blocker for the release, but I found out this testing the example and I think it would be nice to fix it in the future...

**Comment by parmentelat** [comment]
that makes perfect sense indeed, I have never had to disable css code before, will be interesting :)

**Comment by parmentelat** [comment]
this should be fixed by now
