### ISSUE TITLE
Default transition flickers

### ISSUE THREAD

**Issue by mattharrison** [damianavila/RISE#471]
I'm hoping to use RISE on a video course I'm doing. When I transition between slides it looks like it flickers. This is quite jarring, and I won't be able to use it unless I figure out what is happening. I'm using a custom CSS to set the font/colors but otherwise, it is the default settings. The demos for reveal.js and the README example don't show this.

I'm going to debug this, but I thought I would file a bug in case others run into this.

My platform is Mac and I'm running on Chrome.

**Comment by parmentelat** [comment]
well if it's doable at all, try to share your stack of slides, so we can see if that happens on our end too, and maybe even help you figure out what's going on..

**Comment by mattharrison** [comment]
Hmm, I thought I had it pinned down to this CSS:

    .cm-s-ipython {
      font-family: "Roboto Mono";
    }

When I try to make a minimal reproducing notebook, the transition isn't even the same. But there is no "rise" key in either metadata. The transition where I'm seeing the flicker is a fade rather that sweep in from the right. Confused...

**Comment by mattharrison** [comment]
Ok, it seems to be the size of my notebook. (The jupytext python version has 1200 lines of python about 100 cells). Apparently, it is trying to do the sweep transition but failing.

**Comment by parmentelat** [comment]
how many slides is that in total ?  
have you tried other reveal transitions on this specific notebook, if only to see if that'd help ?

**Comment by damianavila** [comment]
> have you tried other reveal transitions on this specific notebook, if only to see if that'd help ?

That a good suggestion, there is `none` transitions that could help in this case...

**Comment by kurtmckee** [comment]
I recommend closing this ticket as stale.
