### ISSUE TITLE
move to reveal-3.8.0

### ISSUE THREAD

**Issue by parmentelat** [damianavila/RISE#474]
it's all in the title

preliminary tests have shown:

* something is wrong with themes; reveal themes - mostly backgrounds - are no longer rendered; after having digged into that for a while,  at this point I 
 actually wonder how reveal themes can have ever worked at all (see also #435 and #438); it's my feeling that we should take this chance to address the matter of themes rather thoroughly, which would reap among others dark themes..
* apart from that, at this point I have not yet seen any other major caveat; but I'm just starting, so..
* notes in particular seem to work just fine
* remember to check also for chalkboard..

**Comment by damianavila** [comment]
>  it's my feeling that we should take this chance to address the matter of themes rather thoroughly, which would reap among others dark themes..

Well, that's is actually a great idea. It would be really great if we can do some progress on this matter.

**Comment by parmentelat** [comment]
as a followup, I'm closing this as  it is now merged on master and is in 5.6.0.dev2
