### ISSUE TITLE
Console error MIME

### ISSUE THREAD

**Issue by BrunoGomesCoelho** [damianavila/RISE#477]
When opening the slideshow, I am getting the following error in my console log:

> The resource from “http://localhost:8889/files/experiments/rise.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).

The slideshow does open "normally" though as far as I am able to see, but I am unable to use "t" to open speaker note :(

I am running jupyter notebook version 5.7.8 and RISE 5.5.0, Firefox 67.

Tested with all jupyter nbextensions except RISE turned off in nbextensions.

Anyone have any ideas?

**Comment by parmentelat** [comment]
> On 3 Jun 2019, at 16:40, Bruno Gomes Coelho <notifications@github.com> wrote:
> 
> When opening the slideshow, I am getting the following error in my console log:
> 
> The resource from “http://localhost:8889/files/experiments/rise.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).

this is a red herring and can be safely ignored; it’s linked to the - rather rustic - way we load custom optional css 

> The slideshow does open "normally" though as far as I am able to see, but I am unable to use "t" to open speaker note :(

I’m unsure what may be happening here; do you also see this with the example/README.ipynb that comes with RISE ?
can you somehow expose your notebook so that others can try it ?

**Comment by BrunoGomesCoelho** [comment]
In the end it was all due to different extensions, closing.
