### ISSUE TITLE
Unable to set width

### ISSUE THREAD

**Issue by memeplex** [damianavila/RISE#484]
If I set width=800px, I get this:

![image](https://user-images.githubusercontent.com/2845433/60391068-8eb0ee80-9abc-11e9-8d03-aaffb22b7064.png)

If I set width=80%, I get this:

![image](https://user-images.githubusercontent.com/2845433/60391072-b1db9e00-9abc-11e9-9f91-68e17d97f4c0.png)

Here some part of the text seems to have been overwritten. Also equations are ill-aligned (very far to the right).

**Comment by parmentelat** [comment]
have you tried to **not set** width or height, and to only use the browser's zoom feature to adjust your content on a slide by slide basis ?

**Comment by memeplex** [comment]
I did, but this forces me to constantly upscale and downscale when switching from/to notebook/reveal because at normal scale rise will use 100% width with lines that wrap at a somewhat absurdly large number of characters. Also by scaling that way I only get a trade off between somewhat absurdly long lines and somewhat absurdly large font size, when the obvious solution is to add some margins to the slide.

**Comment by parmentelat** [comment]
What I often in this sort of case is to add line breaks myself; just like I'd do in powerpoint or keynote; in markdown you add a linebreak by inserting 2 spaces before a newline

another option could be to use CSS to manage your margins manually, but honestly I have never tried to dare into such muddy waters, as it might open up its own space of other problems

any chance you can share the notebook so i can get a better grip at the problem ?

**Comment by memeplex** [comment]
You can access a binder here with latest stable Rise installed.

https://mybinder.org/v2/gl/memeplex%2Fdhouse/master

Look for SGD/Presentación

**Comment by parmentelat** [comment]
So yeah this does not render as expected, everything seems too small; however I can't see how this binder instance is populated so it's hard to say what's going on

**Comment by memeplex** [comment]
Sorry, I'm not following you, what else do you need to know? It's all there, python packages and versions in requirements.txt, some deb packages in apt.txt, the document sources. I would provide anything else you need to debug the issue, but I'm unable to figure out what else could that be.

**Comment by parmentelat** [comment]
git repo url ?

**Comment by memeplex** [comment]
No problem, I'm sending it to you later, but the contents of the repo are exactly the contents exposed in the binder. AFAIK you can download everything you want from the jupyter GUI.

**Comment by damianavila** [comment]
There is a custom.css on that Binder:

```
jovyan@jupyter-memeplex-2ddhouse-2dgq0et2e1:~$ cat /home/jovyan/.jupyter/custom/custom.css
div.text_cell_render {
    font-size: 12pt;
}

/* Centra imágenes */
.slides img {
    display: block !important;
    margin: auto !important;
}

.slides p + ol, .slides p + ul {
    margin-top: 0em !important;
}
```

After removing that things start to look better. How that custom.css ended there?

**Comment by memeplex** [comment]
Ah, yes, it's a customization of mine, I forgot to remove that, sorry. But my first reports about problems with % and px width weren't using that stylesheet nor other one.

**Comment by kurtmckee** [comment]
I recommend closing this ticket for lack of updates and requested info.

**Comment by damianavila** [comment]
Let's close it. If this is still present I guess the original author will ping us here again.
