### ISSUE TITLE
Weird behaviour when exiting a presentation

### ISSUE THREAD

**Issue by srcoulombe** [damianavila/RISE#485]
Hi, I'm really digging RISE, and I'm trying to use it whenever I can to do presentations with live coding! I keep coming across a weird thing when I exit presentation mode though; the entire notebook seems to be shifted up & to the left - sorry for the poor description, this gif is a better explanation.

I'm using firefox btw.

![rise_exit_problem](https://user-images.githubusercontent.com/19175862/60391776-64fbc580-9ac4-11e9-8a4f-0a458d7698ab.gif)

**Comment by parmentelat** [comment]
thanks for reporting this

if you can, answers to the following questions may help pinpointing the issue

* a lot is going on in terms of upgrading the jupyter ecosystem right now, so what versions of notebook / rise are you using ?
* do you get this with any slideshow, or just that one ?
* if it's specific to a notebook, would you care to share it so we can try and reproduce ?
* also, out of curiosity, your dual-column layout is made with the splitcell extension, right ?
* do you see anything odd or suspicious in the javascript console ?

**Comment by srcoulombe** [comment]
python=3.7.0,
rise=5.5.0,
notebook=5.7.8,

I'm seeing this with all my notebooks that use RISE.

Yup, the "split cells notebook" extension is the one.

Sorry I've never looked at the javascript console :( If you have a tutorial/link that could show me how, I'd be super down to learn more about it and how to use it for debugging.

Here's a notebook with that weird behaviour:
https://github.com/srcoulombe/weird-rise-behaviour/blob/master/3.%20Collections.ipynb

Thanks a ton for your work man! I really really enjoy using RISE!

**Comment by parmentelat** [comment]
hey
thanks for the report

as far as the javascript console, on a mac you would toggle the developer tools with command-alt-i  
then look for the 'Console' tab  
there are plenty tutorials on the internet that, the information is really easy to find

I have been able to play the nb that you point at and could not reproduce the issue; well I'm using the devel version 5.6.0.dev3 instead of the stable 5.5.0 one, but I can't see any change in the meanwhile that could explain that

how exactly do you get out of the reveal mode ?

**Comment by srcoulombe** [comment]
I'd exit the presentation mode by clicking the (x) icon at the top left of the screen.

Ok I ended up deleting the notebook.json, rise.json, and reveal.json from my .jupyter/nbconfig directory and relaunching jupyter. Since that worked, I'm guessing that I'd messed up one of those files and that's why I was getting the error. All's good now, the notebook.json file was remade, and adding extensions through the Nbextensions configuration manager works as well. 

Thanks!
