### ISSUE TITLE
If closed once, notes window is not openable again

### ISSUE THREAD

**Issue by JocelynDelalande** [damianavila/RISE#488]
## Steps to reproduce :

1. open notes pressing <kbd>t</kbd>
2. close the notes window
3. press <kbd>t</kbd>

## Expected behavior

Notes window appears again

## Current behavior 

Nothing happens

**Comment by parmentelat** [comment]
Hi  
thanks for the heads up  
I'm not sure we do anything specific in this regard concerning the notes window; if you have a chance to observe the behaviour of plain `reveal.js` in this respect, it could turn out useful

**Comment by damianavila** [comment]
IIRC, plain reveal.js should follow the expected behaviour. We need to check if we can reproduce the issue. @JocelynDelalande can you please inform your browser, notebook and RISE version? Do you see some error message in the browser javascript console?

**Comment by JocelynDelalande** [comment]
Hi,
@damianavila Hi, thanks for your answer, here is the information :

```
$ pip freeze
attrs==19.1.0
backcall==0.1.0
bleach==3.1.0
decorator==4.4.0
defusedxml==0.6.0
entrypoints==0.3
ipdb==0.12
ipykernel==5.1.1
ipython==7.5.0
ipython-genutils==0.2.0
jedi==0.14.0
Jinja2==2.10.1
jsonschema==3.0.1
jupyter-client==5.2.4
jupyter-core==4.5.0
MarkupSafe==1.1.1
mistune==0.8.4
nbconvert==5.5.0
nbformat==4.4.0
notebook==5.7.8
pandocfilters==1.4.2
parso==0.5.0
pexpect==4.7.0
pickleshare==0.7.5
pkg-resources==0.0.0
prometheus-client==0.7.1
prompt-toolkit==2.0.9
ptyprocess==0.6.0
Pygments==2.4.2
pyrsistent==0.15.2
python-dateutil==2.8.0
pyzmq==18.0.1
rise==5.5.0
Send2Trash==1.5.0
six==1.12.0
terminado==0.8.2
testpath==0.4.2
tornado==6.0.3
traitlets==4.3.2
wcwidth==0.1.7
webencodings==0.5.1
```

Firefox 67.0.4 (64 bits)

**Comment by parmentelat** [comment]
I've had a chance to test this superficially on my 5.6.0.dev3 RISE, and have not been able to reproduce (now, 5.6.0 will use reveal 3.8.0 so that doesn't mean much for 5.5.0, but I have no easy way to test that stable version as of now)

@JocelynDelalande is this something that you observe on every single notebook ? 
what does the javascript console show when the problem happens (search for developer tools / javascript console for your browser if needed)

thanks for the report in any case

**Comment by parmentelat** [comment]
as an aside, how do you the notes window exactly ? do you use a keyboard shortcut, or just your browser/OS button to close a web tab, or ?

**Comment by kurtmckee** [comment]
I recommend closing this issue as stale.

**Comment by JocelynDelalande** [comment]
Fair enough, I am far from those issues now and cannot bring more input for now ; sorry.

**Comment by damianavila** [comment]
@JocelynDelalande feel free to re-open when you have some time and information, no need to apologize. Best!
