### ISSUE TITLE
Instruction to center Markdown image fails

### ISSUE THREAD

**Issue by michaelaye** [damianavila/RISE#498]
Trying this in Chrome on Mac (all newest versions):

It looks like this:
<img width="1100" alt="Screenshot 2019-07-24 20 47 13" src="https://user-images.githubusercontent.com/69774/61844478-6b2b5a80-ae54-11e9-8f92-4bac8fd55923.png">

using the code given here: https://rise.readthedocs.io/en/maint-5.5/usage.html#other-notes
<img width="1102" alt="Screenshot 2019-07-24 20 47 19" src="https://user-images.githubusercontent.com/69774/61844472-66ff3d00-ae54-11e9-8d79-5ae2ee1b328d.png">

Maybe this doesn't work with attachments?

**Comment by parmentelat** [comment]
Embedding the markdown markup inside html is a notoriously fragile practice; I advise that you replace the `![]()` thing with a `<img>` tag

**Comment by parmentelat** [comment]
You’re right that the documentation section that you are referring should be altered. If you feel like filing a PR it would be most welcome :)
