### ISSUE TITLE
Google fonts in slides

### ISSUE THREAD

**Issue by stoffprof** [damianavila/RISE#499]
Is it possible to use Google fonts?

I thought perhaps I could put this in rise.css but it doesn't work as expected:

```
@import url('https://fonts.googleapis.com/css?family=Lato&display=swap');

.reveal {
	font-family: 'Lato', sans-serif;
}

``` 
Thanks.

**Comment by parmentelat** [comment]
I’m not sure but you might need to use a more specific CSS selector

Like for any other page the javascript console and devel tools should give you valuable insights about the forces at work here

**Comment by stoffprof** [comment]
Thanks. This worked:

```
@import url('https://fonts.googleapis.com/css?family=Lato&display=swap');

.reveal h1,
.reveal h2,
.reveal h3,
.reveal h4,
.reveal h5,
.reveal h6 {
  font-family: 'Lato', sans-serif;
}
```
