### ISSUE TITLE
Hide navigation buttons

### ISSUE THREAD

**Issue by stoffprof** [damianavila/RISE#500]
I'd like to hide the navigation buttons and slide numbers.

Adding this to `rise.css` removes the navigation arrows

```
.reveal .controls .navigate-left,
.reveal .controls .navigate-right,
.reveal .controls .navigate-up,
.reveal .controls .navigate-down {
	display: none;
}
```

but this doesn't remove the slide numbers:
```
.reveal .slide-number {
	display: none;
}
```

and neither does this:
```
.rise-enabled .reveal .slide-number {
	display: none;
}
```

Looking at the CSS in developer tool, here's what I see:

![Screen Shot](https://user-images.githubusercontent.com/12434323/62317095-ec8f7800-b466-11e9-8f7f-457bea9a3ece.png)

Any ideas how to get this to work?

**Comment by parmentelat** [comment]
have you tried to set slideNumber to False in the config ?  
this is passed along to `reveal.js`

**Comment by stoffprof** [comment]
Thanks, that worked.
