### ISSUE TITLE
returning to slideshow mode slightly broken under 5.6.0-dev3

### ISSUE THREAD

**Issue by parmentelat** [damianavila/RISE#504]
with the devel release 5.6.0-dev3:

returning to slideshow mode after leaving it causes the selected slide to show up misplaced; most of the time it is way below its expected position

to work around that, it's enough to make any kind of a move, like going one slide back and forward; or to click twice on the 'w' key

this does not happen when entering slideshow mode for the first time, only when quitting and returning; slide selection is not affected and works as expected

**Comment by parmentelat** [comment]
I have been investigating this, and have experimentally determined that a call to `Reveal.sync()` is enough to put things back in order and have everything displayed at the right location

specifically, I could bind a keyboard event to `Reveal.sync()` and check that just pressing that key would fix the display

Everything points at a small regression between the 2 versions of reveal (3.5.0 and 3.8.0 IIRC)


I have not however been able to fix the issue properly, and I actually have a rather specific question for @damianavila; in `main.js` there are a few mentions of a `Reveal` variable; this of course references the `reveal.js` module, but at this point I can't for the hell of me figure out  how this binding happens.

The other kind of globals in the code, like Jupyter, are bound to corresponding module with that toplevel `define()`, that much I do get;

But it comes to `Reveal` I can see no sort of a declaration… 

To make things even worse, in some functions inside `main.js`, `Reveal` actually is defined, but in some others  it's not defined at all and raises `ReferenceError: Reveal is not defined`

I tried many different approaches to figure out some logic here; I played with the idea that `Reveal` would be defined inside the `require` bloc 
https://github.com/damianavila/RISE/blob/maint-5.6/rise/static/main.js#L503
but even that does not seem to work; 

I thought I had understood a few things about JS but that one beats me.
So I could really use some hints here; 
What I'd need primarily is to add a call to Reveal.sync() in revealMode() circa this line
https://github.com/damianavila/RISE/blob/maint-5.6/rise/static/main.js#L1052

mind you, it might not the exact right thing to do, it's the general method for accessing the reveal module that I need to clarify here


I'd love to fix this quickly as I am in heavy writing mode and am constantly switching back and forth between classic and slideshow mode, and this is a curse ;( so the sooner I can nail this down the better !

**Comment by parmentelat** [comment]
Hey Damian

Thanks for your answer; and sorry for the moving links, I’ll try to remember that 

First off I did add this timeout eventually after messing about for some time; I will admit  it is not nice, at all, but it does the trick for me, so as of 5.6.dev5 that I issued yesterday, the symptom is no longer there

I ‘d be interested to understand the root cause for the issue some day :)

Now in terms of my question, I still fail to understand  why the javascript variable that is bound to the module is called `Reveal` and not `foobar`; in the initial call to `define` we get to bind e.g. `Jupyter` when we load that module, I don’t see the same mechanism with Reveal
What am I missing?

**Comment by parmentelat** [comment]
Oh and btw I reiterate that we should issue 5.6 as the official release, especially as this was the last usability bug on the way, if you can please give it a thorough test

**Comment by damianavila** [comment]
> Thanks for your answer; and sorry for the moving links, I’ll try to remember that

No problem!!

> I ‘d be interested to understand the root cause for the issue some day :)

😉 

> What am I missing?

The Reveal object is returned at the end of reveal.js https://github.com/hakimel/reveal.js/blob/master/js/reveal.js#L6026.
When you require reveal.js here: https://github.com/damianavila/RISE/blob/master/rise/static/main.js#L503, you make that object available inside that function.

**Comment by damianavila** [comment]
> Oh and btw I reiterate that we should issue 5.6 as the official release, especially as this was the last usability bug on the way, if you can please give it a thorough test

I will test it during the weekend and we may release it after that, thoughts?

**Comment by parmentelat** [comment]
yes please, that would be great :)

**Comment by damianavila** [comment]
> yes please, that would be great :)

I did not forget about this... just trying to find one hour to do this right... but I was not able to find that hour yet ;-)
