### ISSUE TITLE
pass chalkboard settings along to reveal

### ISSUE THREAD

**Issue by rinnert** [damianavila/RISE#505]
It seems currently not possible to alter the chalkboard settings through `nbconfig/rise.json`. 

This a bit of a hindrance I discovered when trying to find a way to set `chalkboard.readOnly` to `false`.

The fix is quite simple, I will file a PR soon.  I mostly created this issue to have something to refer to.

**Comment by parmentelat** [comment]
Hi

Sounds great !
As a friendly note I’d suggest that you build your PR on top of the maint-5.6 branch, or maint-5.5 if you’re conservative, as the other ones are not exactly usable right now

The 5.6 dev release is currently available with

    pip install —pre rise

**Comment by rinnert** [comment]
Just submitted a PR for maint-5.6. The fix is so simple that I doubt it will conflict with any recent branch. I tested it with the masters of `reveal.js` and `reveal.js-plugins/chalkboard` -- seems all fine.

**Comment by parmentelat** [comment]
pr #506 is now merged, this is part of release 5.6.dev5 that just went out
thanks
