### ISSUE TITLE
Upscaling dataframes to fit screen

### ISSUE THREAD

**Issue by kelmouloudi** [damianavila/RISE#511]
Hi,

I love all the work you guys have done. I have a small issue with how tiny dataframes show up in full screen :

![image](https://user-images.githubusercontent.com/42188545/64745440-68192600-d4f7-11e9-8e03-9ced9a8ccd4b.png)

Is it possible for the dataframe to fit the screen and get a bit bigger for more visibility?

I have custom CSS here for added contrast between the data and the axes but I don't think that's relevant here.

(also I hate to double-dip, but is there a way to disable the border around both the input and output? It makes sense in the notebook but not really in a presentation methinks).

Thanks!!

**Comment by damianavila** [comment]
These things could be probably modified by some CCS hacking... could you share your ipynb file and the custom CSS you are using?

**Comment by kurtmckee** [comment]
I recommend closing this ticket for lack of requested information.

**Comment by kelmouloudi** [comment]
I'm very sorry I lost the files since then. I'm closing the ticket for now.
