### ISSUE TITLE
Slide with only figure shown - no code 

### ISSUE THREAD

**Issue by jpmorr** [damianavila/RISE#513]
In my notebook I have many cells that plot the results of what I've been doing, except there's many lines of code to create the sub-plots of 3 figures. When I'm I'm using RISE to make a presentation for this cell I would just like to show the output figure without the many lines of code used to plot it. 

I'm wondering if this is possible? To show the figure on separate slide? 
I've shown a very simple example below - whats I want to see is the figure - what I actually see is the code. This is my first attempt using RISE and I'm stumped at this part. For me, the figure is crucial in the presentation - it's the only thing that matters to most people viewing the presentation.

Grateful for any guidance on how to create a figure only slide with a large figure.

![image](https://user-images.githubusercontent.com/10863809/65429962-f7cfa600-de0e-11e9-9370-87dda92e6f56.png)

**Comment by damianavila** [comment]
There are some people using some other extension to hide the input.
You will find more info here: https://github.com/damianavila/RISE/issues/32.
