### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by jhgoebbert** [damianavila/RISE#514]
Hello,

the following line requires to have the system set to UTF-8.
https://github.com/damianavila/RISE/blob/80e58d0c1336bd376a153a7dd37783fe32cd6de6/package.json#L3

 If this is not the case it is not possible to install rise. The error which occures while installing on a non-UTF-8 system is:
Traceback (most recent call last):
```
File "setup.py", line 48, in <module>
content = package_json.read()
File "/gpfs/software/juwels/stages/Devel-2019a/software/Python/3.6.8-GCCcore-8.3.0/lib/python3.6/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 33: ordinal not in range(128)
(at easybuild/tools/run.py:501 in parse_cmd_output)
```

Best regards,
Jens Henrik

**Comment by parmentelat** [comment]
oh, I guess we are not often exposed to this sort of setup !

it looks more like a pip issue than a rise issue IMHO, (see e.g. <https://github.com/pypa/pip/issues/5016> or <https://github.com/pypa/pip/issues/761>)

this being said, one very simple way to solve this for good would be to project Damián's name into ASCII space and rewrite it as just Damian; but I'm not sure I would like it it were me :)
Damián how do *you* feel about that ?

**Comment by damianavila** [comment]
Ja... my name making trouble!!!

> this being said, one very simple way to solve this for good would be to project Damián's name into ASCII space and rewrite it as just Damian; but I'm not sure I would like it it were me :)
Damián how do you feel about that ?

Yep, let's rewrite it as just Damian, that's totally OK with me...

**Comment by parmentelat** [comment]
will be in 5.6.1 when released
