### ISSUE TITLE
Background Image Leaves a Margin to the bottom and right of Screen

### ISSUE THREAD

**Issue by PhillipDowney** [damianavila/RISE#515]
I have added through the nbextensions configuration a png file for the slide background but at the bottom and right hand side of the screen when in slide mode it shows a 1 inch margin of a blue background. anyone have any ideas on how to fix ?

**Comment by parmentelat** [comment]
> On 1 Oct 2019, at 07:23, Phil Downey <notifications@github.com> wrote:
> 
> I have added through the nbextensions configuration a png file for the slide background but at the bottom and right hand side of the screen when in slide mode it shows a 1 inch margin of a blue background. anyone have any ideas on how to fix ?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

not sure if I can help you, but I believe that a screenshot could be helpful; at the very least, what theme are you using ?

**Comment by PhillipDowney** [comment]
I am using the default simple theme, and the image is generated from a Power Point Slide exported asa jpg or png... seems to have something to do with the relative height and width of a images resolution when exported but  I have not been able to manipulate it to fill the full screen

**Comment by PhillipDowney** [comment]
![Screen Shot 2019-10-01 at 10 19 42 pm](https://user-images.githubusercontent.com/30096303/65961417-da977900-e499-11e9-982e-17c9bb1581b4.png)
here is an example using  the Star Wars file of GitHub, does not seem to want to stretch it over the page depending on screen resolution. I have 2 Acer 24 incm monitors and a 15 inch Mac

**Comment by damianavila** [comment]
At some time we had support for parallax... https://github.com/damianavila/RISE/blob/master/rise/static/main.js#L523

Ref: https://github.com/hakimel/reveal.js/#parallax-background

Not sure when we removed that and why?
I guess some custom CSS trick could help you in the meantime... but I guess you want parallax support...

**Comment by PhillipDowney** [comment]
Solved it, changed the RISE main.js file entry for back image Style to the below... stretches the Image to fit...
"let backimage_style = “top:0;left:0;position:fixed;min-width: 100%; min-height: 100%;“;"

**Comment by damianavila** [comment]
That should be customizable with CSS as well, I would probably suggest that instead of touching the js file, any reason you went on that direction @PhillipDowney? Just curious :wink:

**Comment by PhillipDowney** [comment]
I tried a few things in the CSS that did not work, but will try again. As I am not that familiar with the code it was also easier to to work out what the main.js was doing... Ideally I would want to not change the main code for such config changes. Would there be a way of building it into the notebook itself as a override of the defaults ?

**Comment by parmentelat** [comment]
Yo

Could you please send a screenshot so we can beter see what’s wrong ?
