### ISSUE TITLE
My button disappeared

### ISSUE THREAD

**Issue by EspinosaLeal** [damianavila/RISE#516]
Hi Damian,

Big fan of RISE here. I was trying to reuse some slides from some months ago and suddenly my RISE button doesn't show in the place where it used to be. Perhaps some upgrade in my conda environments changed something. I've been trying to fix this problem but any success so far. Any hint on how to solve it?

Thanks in advance!

Here some info from my terminal:

![bug](https://user-images.githubusercontent.com/17129627/66399990-45403b80-e9e9-11e9-8e4a-809a158608b1.png)

Some additional info:
notebook 6.0.0
rise 5.5.0
firefox 69.0.1

**Comment by parmentelat** [comment]
as stated on gitter : I suggest that you try installing the dev release of rise that is 5.6.something using

```
pip install -U --pre rise
```

this devel version works fine and has no known drawback, @damianavila we should decidedly find the time to issue it as the official release IMHO

**Comment by EspinosaLeal** [comment]
I tried in a different environment and there it works, uhmm, well I don't know, but thanks for all.

**Comment by damianavila** [comment]
> @damianavila we should decidedly find the time to issue it as the official release IMHO

Yep, I have already set aside time to release it during this weekend, most probably tomorrow.
