### ISSUE TITLE
embed a html page within a cell 

### ISSUE THREAD

**Issue by shahramjoon** [damianavila/RISE#518]
Hello

We have a html page and we want to embed it in a markdown cell that in slide mode, html page will be shown. 
nothing else is that slide. 

we have put the vis.html in data folder and we put this code in markdown cell 
it doesn't show anything. 

<object type="text/html" data="data/vis.html">
</object>

I appreciate your guidance

**Comment by damianavila** [comment]
Do you have any repo to look at and try to reproduce your steps?
Btw, in the past, to embed html in the notebook (and in the slideshow as well), I have used the IPython.display machinery: https://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html#IPython.display.HTML.

**Comment by kurtmckee** [comment]
It appears this ticket can be closed as stale.
