### ISSUE TITLE
Lines of text overlap

### ISSUE THREAD

**Issue by IanSudbery** [damianavila/RISE#519]
I am coming back to a set of presentations I use to give a series of lectures after a year, on a new system, and I am getting strange behavior from text in markdown cells - when a paragraph is longer than one line, the lines are too close together, and overlap. See:

![image](https://user-images.githubusercontent.com/5391758/67994542-a6041200-fc3d-11e9-9674-15e807478019.png)

I'm not using any custom styling or notebook metadata configurations. I've tried it on both chrome (78.0.3904.87) and firefox (70.0.01). RISE 5.4.1, jupter-core 4.5.0, notebook 5.7.0. python 3.7.

I'm about to starting giving this course, so any help would be very much appreciated!

**Comment by IanSudbery** [comment]
I've now confirmed that I have the same issue with RISE 5.5.1, notebook 6.0.1.

**Comment by IanSudbery** [comment]
I've "fixed" this by copying the content to a new notebook.

**Comment by damianavila** [comment]
> I've "fixed" this by copying the content to a new notebook.

Well, that's weird, any chance to get the old notebook to see if we can catch something retrospectively?
