### ISSUE TITLE
How can I change the CSS style definition for the MathJax_Display DIV?

### ISSUE THREAD

**Issue by halloleo** [damianavila/RISE#521]
I want to left align MathJax formua (instead of centering them).

In the HTML of a RISE slideshow i find a DIV like 

```
<div class="MathJax_Display" style="text-align: center;"
. . .
</div>
```

around the MathJax stuff. I think that modifying the style of the div to `style="text-align: left;" should give the result I desire. (I might than add some `margin-left` to indent it a bit as well.)

But the big question is: How can I change this CSS style?

**Comment by parmentelat** [comment]
your answer is in the doc here:
https://rise.readthedocs.io/en/maint-5.5/customize.html#adding-custom-css

**Comment by parmentelat** [comment]
I'm closing but feel free to re-open if needed of course
