### ISSUE TITLE
keyboard bindings need to be checked

### ISSUE THREAD

**Issue by parmentelat** [damianavila/RISE#532]
I am currently running 5.6.1-dev3; I use it within two similar environments (authoring and production) and I have noticed a different behaviour

* while writing on my laptop, some of reveal's default keyboard shortcuts won't work; particularly `w` to toggle preview mode, as well as `Home` and `End`; there might be others 

* on my production box however, these three keyboard shortcuts work as expected

---------
these 2 environments run the same version of rise, but exhibit several other differences
1. authoring setup runs has quite a few custom keystrokes defined for productivity (using vanilla Jupyter `set_shortcut()`)
1. authoring setup makes use of the configurator to redefine some of the default key bindings
1. authoring setup has more extensions enabled

I am suspecting item #2 to be the root cause, as a consequence of the #525 #526 combo, but have no hard evidence of that for now

I am in a rush and cannot investigate this further right now, so I figured I'd write down this braindump for the record

**Comment by parmentelat** [comment]
check done, everything is fine, I had changed my keymap in the configurator, behaviour is actually  as advertised

**Comment by damianavila** [comment]
Thanks for checking it!
