### ISSUE TITLE
Jupyter and Moodle

### ISSUE THREAD

**Issue by YorozuyaDev** [damianavila/RISE#533]
Is there a way or a plugin to integrate a Jupyter/RISE slideshow in a moodle?

**Comment by parmentelat** [comment]
FYI some colleagues in France are running a moddle instance as part of the m@gistere program, and have developped their own moodle plugin to connect to our notebook hosting platform based on https://github.com/parmentelat/nbhosting, so they can embed Jupyter notebooks; running RISE - or any other Python / Jupyter extension for that matter - at that point is just a matter of properly building your docker image.

**Comment by kurtmckee** [comment]
It appears that the answer to the question is 'yes' -- I'm seeing references online to some users doing this using something called ltiauthenticator.

Perhaps this ticket could be closed as it is about Jupyter and Moodle, not RISE specifically.

**Comment by damianavila** [comment]
> Perhaps this ticket could be closed as it is about Jupyter and Moodle, not RISE specifically.

I agree, closing it.
