### ISSUE TITLE
Rise for Jupyterlab 

### ISSUE THREAD

**Issue by Nayef-Abou-Tayoun** [damianavila/RISE#535]
Hi, 
I would like to use RISE in Jupyterlab. Is it possible to use it ? and if so, then how ? 

thanks

**Comment by damianavila** [comment]
@Nayef-Abou-Tayoun, we are restarting o working on that, there is a previous issue about this request here: https://github.com/damianavila/RISE/issues/270.

Closing this one as a duplicate. Thanks!
