### ISSUE TITLE
2.4 compatible version and release a 3.0 compatible version

### ISSUE THREAD

**Issue by damianavila** [damianavila/RISE#54]
* [x] Let's be sure that 2.x is still compatible with all the 2.4
* [x] Make master fully compatible with 3.0

**Comment by damianavila** [comment]
Since 2.x is compatible with IPython 2 series, there is no real need to maintain master compatible with 2.4, that introduces ugly hacks and since 3.0 is going to be released soon, let's make 3.x compatible wit IPython/Jupyter 3 series:

* [ ] don't support IPython 2 serie on master
* [ ] Release 3.x (when IPython 3.0 is released)

**Comment by damianavila** [comment]
OK, we need to release 3.x version soon... target is next week... I will review the open PR in the next days and testing over the weekend, then we can release a new version :wink:

**Comment by flothesof** [comment]
Hi there, 

I've just tried to install RISE and failed using the python setup.py install method.

The reason this happens is 

```
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from IPython.html.services.config import ConfigManager
ImportError: No module named config
```

I'm using IPython 2.4.1 and I guess this is the reason this hangs. Do I need to switch to IPython 3.0 to get RISE to work?

Thanks for your help.

**Comment by damianavila** [comment]
This tagged/released version: https://github.com/damianavila/RISE/releases/tag/2.x, will work with IPython 2.x, but if you want to use master, you need to update IPython to 3.0 or higher...

**Comment by flothesof** [comment]
Great! I'll try that out. Thank you!

**Comment by flothesof** [comment]
I've just tried it out and it works perfectly. Thanks a lot. 

The only thing I had a little trouble with at first was to find the right place to add the custom.js instructions too.

Great plugin!

**Comment by damianavila** [comment]
> The only thing I had a little trouble with at first was to find the right place to add the custom.js instructions too.

Since now we use the ConfigManager there is no need for those instructions... it can be a little annoying at first sight, I agree... Nice to know it works well for you too. Thanks.

**Comment by damianavila** [comment]
I tagged 3.x a few minutes ago... for Jupyter, we will have a proper release with conda packages,  a flit-based package too and the standard installation from source.
