### ISSUE TITLE
Remove overlay buttons 

### ISSUE THREAD

**Issue by j3ypi** [damianavila/RISE#543]
While one can remove the control buttons (arrows), I couldn't find a way to hide the exit and help buttons. Is there a way to do this? Those buttons might be especially distractive in the case of zooming more than 100% within the browser.

**Comment by parmentelat** [comment]
have you tried the `,` keyboard shortcut, which IIRC toggles these 2 on and off

**Comment by j3ypi** [comment]
Consider me blind. Thanks a lot, it works like a charm.
