### ISSUE TITLE
Shift+SpaceBar no longer working on Mac

### ISSUE THREAD

**Issue by wstomv** [damianavila/RISE#545]
I have always been relying heavily on SpaceBar and Shift+SpaceBar. Now, suddenly, Shift+SpaceBar no longer work (well, it works as if the Shift is not used, i.e. goes forward instead of backward). Very annoying (I need to lecture again these weeks).

I work on MacOS 10.14.6.

Any advice appreciated.  Any workaround?

**Comment by damianavila** [comment]
@wstomv could you please report:

RISE version
Notebook version
Browser name and version

Any logs in the browser (javascript) console?
Do you have installed any other extension that could be changing the hotkeys?

**Comment by wstomv** [comment]
RISE: 5.4.1
Jupyter Notebook:
* jupyter_client: 5.2.4
* jupyter_core: 4.4.0

Browser: Firefox 75.0
OS: MacOS 10.14.6

I am trying to update RISE, but `Solving environment` (from `conda update rise`) takes ages.

**Comment by wstomv** [comment]
It turns out that my `~/.jupyter/nbconfig/notebook.json` has this
```
  "keys": {
    "command": {
      "unbind": [
        "shift-space"
      ]
    }
  }
```

I am not sure whether it just got inserted when I tried to 'fix' shift-space using the keyboard shortcut editor. Anyways, removing this did not help. Nor did restarting of the browser help.

It must be something specific to Jupyter, because shift-space works in regular browser pages. I do not find any other places where shift-space is rebound. Maybe someone here has an idea?

**Comment by parmentelat** [comment]
rise-5.4 is *very* outdated; the other tools as well btw
I'd start trying to upgrade rise to the latest 5.6 version if that's an option

I'm not a heavy conda user myself, but I do use miniconda all the time
you do known that you can easily spawn a fresh miniconda to play with alternative versions, right ?

**Comment by wstomv** [comment]
Updated my installation to:

    rise                      5.6.1
    jupyter_client            6.1.2
    jupyter_core              4.6.3

But this makes no difference. The nbextension _Keyboard shortcut editor_ reports shift-space as scrolling up (but it doesn't; neither in notebook mode, nor in presentation mode).

**Comment by parmentelat** [comment]
the usual behaviour that has shift-space bound to 'previous-slide' is a native reveal.js feature that we do not supersede in any way; the code for rise does not do anything regarding the binding of shift-space

now the fact that you say that shift-space does not scroll up in notebook either makes the case even more compelling, that this has most likely not to do with rise

is it possible that some global system preference is precluding your keyboard from sending this particular sequence, or that it gets caught by something higher up in the foodchain like e.g. your window manager ?

**Comment by wstomv** [comment]
As stated earlier. shift-space does work for regular web pages in that same browser. So, my conclusion is that it is a **Jupyter issue,** and _not_ a RISE issue. Thanks for helping so far.

Please, drop me a line if you have further clues. For now, I am closing the issue.
