### ISSUE TITLE
RISE doesn't seem to respect media queries

### ISSUE THREAD

**Issue by prosoitos** [damianavila/RISE#556]
In traditional reveal.js presentations, media queries such as:

```css
@media screen and (max-width: xxx) {
...
}
```
allow to to resize elements dynamically. It is great because the font size that might work on a laptop screen may be tiny on a large screen and vice-versa.

Adding media queries to a css file in RISE does not seem to have any effect.

Thanks!

**Comment by prosoitos** [comment]
Actually, it is quite likely that it does and that I am just not using the proper syntax in the context of RISE.

If anyone knows how to properly use the `@media` rule in a css for RISE, I would be very interested!

Thanks!!

**Comment by prosoitos** [comment]
I figured it out. This works nicely:

```css
body.rise-enabled div.inner_cell>div.text_cell_render.rendered_html {
  font-size: 3.5vmin;
}
```
Credit goes to this post which really helped me: https://medium.com/myplanet-musings/building-a-responsive-reveal-js-theme-399179632cc6.

Now the font size automatically get rescaled if the screen resolution changes.

I'll close this issue.

**Comment by damianavila** [comment]
Thanks, @prosoitos for the issue and the resolution. 
Wondering if we should add some section in the docs with this kind of "tricks"...

**Comment by prosoitos** [comment]
Actually, something that I found very useful to get started was your Example section. So you could add this in one of the example.

Adding in the doc that looking at the default `rise/main.css` as a template for syntax might be useful. It should be obvious, but it took me some time to think of it lol.

**Comment by parmentelat** [comment]
Hey @prosoitos 

this is all good to hear, and I for one was unaware and would benefit from that knowledge !
so any additional example would definitely come in handy, and any PR to that effect would be most welcome indeed
should we start with a piece named `responsive` ? 

thanks for sharing !

**Comment by prosoitos** [comment]
Cool. I am quite busy preparing a workshop right now (hence all my issues lol), but I will try to add some examples after that :slightly_smiling_face:

**Comment by parmentelat** [comment]
of course there is absolutely no hurry, thank you if you can find the time to share your tips with the rest of us :-)
