### ISSUE TITLE
How to show two cells at once, without fragments?

### ISSUE THREAD

**Issue by drscotthawley** [damianavila/RISE#593]
(This is a cross-post and elaboration of the question I asked on Gitter:)  Wonderful utility RISE is!

 There's something I'm not understand, and not seeing described in the documentation: How do we get two or more cells to appear at the same time on the same slide, without having to advance through fragments?

Most of my slides are two parts, from two cells: A Markdown header with the slide title and a bit of text, and then below that a figure (picture/chart) generated by a code cell. 

Currently I'm setting the Markdown header as "slide" and the code cell as "fragment", but that means that I always have to press the space bar to reveal the slide and -- more importantly -- the "w" overview doesn't show any of my figures, making it harder to navigate.

How can we get two cells to display at the same time without having to step through "fragments"?   Perhaps there's an "auto-advance fragments" customization?  (but I didn't see any such thing mentioned. )  

(Or, I'd settle for fragments displaying in overview if not in the main-display mode.)

**Comment by drscotthawley** [comment]
From this reveal.js issue https://github.com/hakimel/reveal.js/issues/1784, it's possible to have it auto-show the first fragment (good enough for me!) by adding this to a "skipped" code cell at the top:

```Python
%%html
<script>
Reveal.addEventListener( 'slidechanged', function( event ) {
    Reveal.nextFragment();
} );
</script>
```
...this works! For me. Closing.

**Comment by drscotthawley** [comment]
...I spoke too soon.  That seems to work *some* of the time, but it's intermittent.  Some first fragments auto-show, others don't and you still have to press the space bar to see them.  Hmmm.

**Comment by parmentelat** [comment]
As mentioned on gitter, just don't add fragments at all and iiuc you will get the behavior that you want

**Comment by drscotthawley** [comment]
@parmentelat Thank you! Closing.
