### ISSUE TITLE
Can not delete overlay

### ISSUE THREAD

**Issue by DrSHendricks** [damianavila/RISE#601]
I set up the header, footer and background image along with overlay together, then realised that they shouldn't be active at the same time. I deleted and reset all settings of RISE, it's not working; then I disabled RISE, cleared cookies and browser data, and rebooted my laptop, but the overlay setting is still there even RISE is disabled and related code has been removed. I haven't tried to uninstall RISE yet, hope it is not my last resort. Can anyone help, please?

**Comment by damianavila** [comment]
Is there any chance that you have some setting defined in the notebook metadata?
Alternatively, I would look for duplicated config files in user vs sys-prefix space.

**Comment by DrSHendricks** [comment]
Hi,
Thank you. I reinstalled Jupyter Notebook, then the error disappeared.
