### ISSUE TITLE
chalkboard enabled + rise.css

### ISSUE THREAD

**Issue by gerrit593** [damianavila/RISE#620]
Hi

I work on jupyter notebook and use rise for a presentation - thank you very much for this initiative, I love it!

My problem is the following: Enabling chalkboard works, but once I have my rise.css included in the same folder as the notebook with the following code

```
* {background-color: #F2F2F2;
   font-family: Garamond}
```

the presentation is just flat white once chalkboard is enabled. Pressing Space shows the page numbers increasing, but everything else is just flat white without any of my content. Without the chalkboard, the rise.css applies just as wanted and the content of the presentation is also displayed as wanted.

Can someone help me out?

Best 
Gerrit

**Comment by parmentelat** [comment]
Hi

The first thing you want to try is to use `body` in your css selector instead of `*`

Use the web inspector to better understand how your rules, as they are, apply to all elements that do not have these properties set on themselves;
 you want to use inheritance, and not override `background-color`like you are doing here



> 
> Enabling chalkboard works, but once I have my rise.css included in the same folder as the notebook with the following code
> 
> * {background-color: #F2F2F2}
> * {font-family: Garamond}
> the presentation is just flat white once chalkboard is enabled. Pressing Space shows the page numbers increasing, but everything else is just flat white without any of my content.
> 
> 
>

**Comment by gerrit593** [comment]
Hi

thanks! 'body' didn't work but using the web inspector I managed 'div' to work. I think the problem was because of an overlay that the chalkboard creates of which I changed to color to grey. Maybe I was a bit hasty with my post here.
