### ISSUE TITLE
The slide does not adjust the height of a cell. Rather, it cuts down the view without enabling the scroll bar.

### ISSUE THREAD

**Issue by sanaatucd** [damianavila/RISE#628]
View in slide:
![screenshot-localhost_8888-2022 11 13-21_50_30](https://user-images.githubusercontent.com/116660903/201554299-96cb6af2-02c9-481b-a77f-1063c056b648.png)

Actual complete view expected:
![screenshot-localhost_8888-2022 11 13-21_51_13](https://user-images.githubusercontent.com/116660903/201554324-89833215-be13-4899-9215-d7ca7887f196.png)

Why is that so?

**Comment by aoeftiger** [comment]
Can you try to switch on the scroll bar in the metadata of the notebook?

https://rise.readthedocs.io/en/stable/customize.html#enable-a-right-scroll-bar

(similar issues: https://github.com/damianavila/RISE/issues/185 )

**Comment by sanaatucd** [comment]
The solution provided here https://github.com/damianavila/RISE/issues/185 worked for me. 

The changes I made in the metadata of the notebook did not work. I had to go to anaconda3/share/jupyter/nbextensions/rise directory and made changes in main.json file. Then, after restarting the notebook, the changes worked.

I am thankful for the response and feedback. I am closing the issue now.

**Comment by vmonteco** [comment]
> Can you try to switch on the scroll bar in the metadata of the notebook?
> 
> https://rise.readthedocs.io/en/stable/customize.html#enable-a-right-scroll-bar
> 
> (similar issues: #185 )

The link being dead, I'm taking the liberty to provide the one for latest rather than stable in order to make it more convenient.

https://rise.readthedocs.io/en/latest/customize.html#enable-a-right-scroll-bar
