### ISSUE TITLE
Is it possible to remove left padding from code output cells? 

### ISSUE THREAD

**Issue by max-poltora** [damianavila/RISE#630]
I would like to align my presentation slides, which are made of combination of markdown and code output cells. The markdown cell does not have a left padding, while code output cell does. This makes the presentation look unordered. I wonder, if it is possible to disabole left padding of code output cells?

**Comment by parmentelat** [comment]
I guess it must be possible through css styling
can you please post a screenshot or something, so as to be a little more specific ?
are you hiding the input part of you code cells ?

**Comment by max-poltora** [comment]
Here is an example of few slides.
First is the markdown cell:
![No padding](https://user-images.githubusercontent.com/66369466/202701515-b990d1fa-248c-4ab7-9611-24d1fb99ae15.jpg)
Here is the code cell (code is not hidden)
![With padding](https://user-images.githubusercontent.com/66369466/202701882-ba2e87ab-0c6d-489f-9961-2c2ded1db007.jpg)
And finally, the code cell with hidden code:
![With padding 2](https://user-images.githubusercontent.com/66369466/202702025-ffd93e56-2da2-4154-81fc-db7c202af996.jpg)

**Comment by max-poltora** [comment]
I tried to use the following code in the first cell of my jupyter notebook, but it does not remove this left padding, when clicking Rise slideshow button.
```
from IPython.display import display, HTML, Markdown

display(HTML("""
    <style>
    .output {
        margin-top: 1% !important;
        margin-bottom: 1% !important;
        margin-left: 1% !important;
        margin-right: 1% !important;
    }
    </style>
"""))
```

**Comment by parmentelat** [comment]
here's a stylesheet that I use, not everything is relevant to your question but it might give you inspiration

https://github.com/ue22-p21/web-intro/blob/main/css/in-out.css

**Comment by parmentelat** [comment]
another css rule that I found in one of my slideshows is this one, which again might help out

```css
div.cell.text_cell .prompt.input_prompt {
    display: none;
}
```

**Comment by max-poltora** [comment]
@parmentelat, thanks for your respond. After trying this and that, I was finally able to hide all the prompts in my notebook by running
```
div.prompt {
       display: none;
}
```
