### ISSUE TITLE
RISE & Jupyter Notebook 7

### ISSUE THREAD

**Issue by swenlaur** [damianavila/RISE#645]
Is it possible to use RISE with Jupyter Notebook 7. Differently form Jupyter Notebook 6 the Cell top menu is missing and there seems to be no way to activate RISE slideshow button. If it is possible you should explain how to use it in top readme.md or declare that this is impossible. I would save a lot time for many people.

**Comment by parmentelat** [comment]
there's what I thought was a non equivocal disclaimer on the landing page already here
https://rise.readthedocs.io/en/latest/

feel free to file a PR on the documentation if you believe this is not visible enough and have ideas about to improve the message
