### ISSUE TITLE
Should some slideshow options be embedded in the notebook?

### ISSUE THREAD

**Issue by takluyver** [damianavila/RISE#79]
At present, theme and transition are user-local settings stored in frontend config. Possibly there should be a way of embedding information like this in the notebook metadata, where it would override the user config.

**Comment by damianavila** [comment]
I agree... I thought about this before... we should find a way to provide the user with a nice UI in the notebook to config a lot of things... probably the notebook metadata is the place to embed this info... maybe under a slideshow_config key, or something else...

**Comment by juliohm** [comment]
Currently, what is the startup file responsible for theme configuration? I tried adding the code in the README under the `.ipython/profile_julia/startup/` directory but it didn't work. I think it's being executed before RISE, is that correct?

**Comment by damianavila** [comment]
You only need to run the snippet of code in the [README](https://github.com/damianavila/RISE#configure-your-own-options) once... with a python kernel... or in any python interpreter (we prefer ipython ;-). This will generate a JSON file in your default profile which stores the config you want, check `.ipython/profile_default/nbconfig/livereveal.json`

So you have to be aware that:

1. Use the default profile of modify the snippet to store the config in your desired profile (you can pass a profile parameter to the ConfigManager)
2. You could potentially write the snippet in Julia to write the needed config file, but it is easy just to use the python one...

Hope it helps and let me know if you need more assistance...

**Comment by juliohm** [comment]
@damianavila, thank you for the clarification. The file is created under `.ipython/profile_default/nbconfig/livereveal.json` but I cannot see any change when using the Python kernel and default IPyhon profile.

I passed a `profile` parameter to the `ConfigManager` but it doesn't affect the files under `.ipython/profile_julia/`. What I'm doing wrong?

**Comment by takluyver** [comment]
I think you need to pass it a path to `profile_dir` instead of just a profile name. We're getting rid of named profiles when we split the notebook parts to the name Jupyter anyway.

**Comment by juliohm** [comment]
Thanks @takluyver, I'm waiting for this transition to happen. The thing is that even for the Python kernel, the theme change is not taking effect.

**Comment by takluyver** [comment]
How are you starting the notebook? If you're running it with the julia profile, it won't load any config from the default profile. Kernels do not affect this.

**Comment by juliohm** [comment]
I'm starting the notebook as usual with `ipython notebook` assuming the default `reveal.js` themes are installed somewhere.

I can confirm the `livereveal.json` is under the `profile_default/nbconfig` directory.

**Comment by damianavila** [comment]
Can you post the content of the `livereveal.json` file?

**Comment by juliohm** [comment]
Sure, the content is:

```python
{
  "theme": "black",
  "start_slideshow_at": "selected"
}
```

**Comment by damianavila** [comment]
Well, can you try with other theme like `sky` or `serif`, the black themes are not compatible with RISE yet beceause of conflicting css between reveal.js css and ipython css...

**Comment by juliohm** [comment]
It worked, what is the list of all available themes?

**Comment by damianavila** [comment]
All the "whity" ones (simple, sky, serif, etc) should work without major problems... the "darker" ones needs probably some custom css to make them work...

**Comment by damianavila** [comment]
#156 closed this one.
