### ISSUE TITLE
Unable to change style from Julia kernel.

### ISSUE THREAD

**Issue by dpsanders** [damianavila/RISE#81]
I have tried to change the style from the Julia kernel via

```
using PyCall
@pyimport IPython.html.services.config as config 

cm = config.ConfigManager()
cm[:update]("livereveal", {
    "theme" => "sky",
    "transition" => "zoom",
})
```
(a direct translation of the Python code in the README),
but this does not seem to have any effect.

**Comment by dpsanders** [comment]
Hmmm, it seems that the settings persist and reopening the notebook solves the problem.

**Comment by damianavila** [comment]
That's interesting... maybe it would be nice to add a note in the README, requesting PR :stuck_out_tongue_winking_eye:
