### ISSUE TITLE
Undesired execution of cells with Alt + R shortcut

### ISSUE THREAD

**Issue by juliohm** [damianavila/RISE#85]
I understood the `Alt+R` shortcut is a switch into presentation mode. It's actually running all cells when I press it. If I click the icon in the toolbar instead, the presentation starts without any cell execution as desired.

**Comment by damianavila** [comment]
This is probably a bug... labelling as that, I will take a look...

**Comment by damianavila** [comment]
Well... I don't know... I don't see execution of cells with Alt + R, do you have any other extension doing that maybe?

**Comment by damianavila** [comment]
Probably runtools?

**Comment by juliohm** [comment]
Yes Damián, it's runtools that is causing the issue, could you please close
this thread?

Thanks.
