### ISSUE TITLE
Option to hide RISE buttons in presentation mode

### ISSUE THREAD

**Issue by juliohm** [damianavila/RISE#86]
How can I hide those `(X)` and `(?)` buttons in presentation mode?

**Comment by nehalecky** [comment]
Along with @juliohm, I also am dying to know. Thanks!

**Comment by damianavila** [comment]
Modifying this https://github.com/damianavila/RISE/blob/master/livereveal/main.css file to hide the buttons... something along this lines

```
#exit_b, 
#help_b {
  display: none;
}
```

should work.

**Comment by juliohm** [comment]
Hi Damián, so there is no plan to add an option somewhere? Some may find
the buttons distractive.

**Comment by damianavila** [comment]
I guess we can probably add a config option for that...

**Comment by juliohm** [comment]
That would be great or rethink the size of the buttons.

**Comment by damianavila** [comment]
Now in master you have the `,` (comma) key to toggle on/off the buttons. Closing as solved.

**Comment by stoffprof** [comment]
Would it make sense to have the comma also toggle the notes/chalkboard icons in chalkboard mode?

**Comment by damianavila** [comment]
> Would it make sense to have the comma also toggle the notes/chalkboard icons in chalkboard mode?

It makes sense, can you open a new issue for that @stoffprof? Thanks!
