### ISSUE TITLE
Explain how to configure theme in non-default profile

### ISSUE THREAD

**Issue by banbh** [damianavila/RISE#88]
The readme explains how to configure the theme via `ConfigManager().update('livereveal',...)`.  However it might be nice to mention how this interacts with profiles.  Perhaps something like `ConfigManager(profile_dir=locate_profile(get_ipython().profile))`.

The motivation for this is that when I installed livereveal I used the `--profile` option, but was then puzzled when the theme configuration had no effect.  It took me some time to realize that ConfigManager operates on the default profile unless you tell it otherwise.

**Comment by damianavila** [comment]
You are right about this... can you submit a PR with this addition to the README? If you can't, I can do it later, but as you faced the problem, you will probably have the best words to explain it :stuck_out_tongue_winking_eye:

**Comment by banbh** [comment]
Just created my first PR to close this.  In the end I made the change to the python code with no explanation in the text, as I felt that commenting on how ConfigManager deals with profiles would have been too much of a digression for a readme.  Feel free to tell me if you want explanation.

**Comment by damianavila** [comment]
Thanks, I will comment one the PR itself...
