### ISSUE TITLE
Support speaker notes

### ISSUE THREAD

**Issue by damianavila** [damianavila/RISE#99]
Currently if you enable the speaker notes, you will see the notebook, not the slideshow. We need to support he slide mode in the speaker notes too.

**Comment by torwag** [comment]
I would love to see a more flexible usage of the slide types, e.g. by letting people create their own slides-types. If slide-types could be assigned to certain views or exports, one could create a speaker slide type which will place additional infos to the speakers notes but not to the presentation slides.
Same would happen for PDF-type, HTML-type, etc. to export to PDF and static HTML

**Comment by damianavila** [comment]
Yes, this is somewhat discussed in the past and probably we can provide something like that in the future... in the long-term I am thinking in some kind of jupyter slides package to enhance the notebook with all the slides-related things, including themes, aggressive customization, and some other cool stuff, not only in the static slides but also in RISE...well, we sill see how these things evolve... but I just want to let you know that what you ask in on my mind since probably 1-2 years ago, and eventually, we will get there :wink:

**Comment by hakanjonsson** [comment]
How do I enable speaker notes?

**Comment by damianavila** [comment]
>How do I enable speaker notes?

Currently not supported.

**Comment by damianavila** [comment]
Duplicated here: https://github.com/damianavila/RISE/issues/174
Let's just keep one issue open. Closing.
